### ISSUE TITLE
🐛 Absolute path cannot resolve in vue->less import

### ISSUE THREAD

**Issue by ikasty** [parcel-bundler/parcel#1109]
From vue module, trying import less file with absolute path cannot resolved.

### 💻 Code Sample
directory:
```
┬ package.json
├ index.js
├ index.html
├ resource/
│   └ style.less
└ app/
    └ index.vue
```

from `index.js`,
```js
import Vue from 'vue';
import App from '/app';

new Vue({
  el: '#app',
  components: { App },
  render: h => h(App),
});
```

from `index.vue`,
```vue
<template>
  <p>test module</p>
</template>
<script></script>
<style lang="less">
  @import "/resource/style.less";
</style>
```

### 🤔 Expected Behavior
`style.less` should be loaded from `index.vue`.

### 😯 Current Behavior
`style.less` cannot be resolved. Parcel says:
`'/resource/style.less' wasn't found. Tried - /resource/style.less,/some/path/to/app/node_modules/resource/style.less`

Using `@import '../resource/style.less';`, it does not make any problem.

### 💁 Possible Solution
Fix 'path resolver' (or finder, or whatever the name is) for css/less, as same concept as other 'path resolver'.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0 |
| Node             | v8.9.4 |
| npm/Yarn         | Yarn 1.5.1 |
| vue                 | 2.5.16 |
| less                 | 3.0.1 |
| Operating System | Linux 4.4.0-43-Microsoft (WSL) |

**Comment by gnijuohz** [comment]
Just looked into it a bit, so the error `'/resource/style.less' wasn't found. Tried - /resource/style.less,/some/path/to/app/node_modules/resource/style.less` is actually given by less instead of parcel.

This error is easy to reproduce with the following structure

```
┬ resource/
│   └ style.less
└ app/
    └ index.less
```

with index.less being

```
@import "/resource/style.less";
```

and running `lessc index.less` or `lessc app/index.less` gives the same error. I don't think being in a `.vue` file should change how less process import, so perhaps this is not a bug?

**Comment by gnijuohz** [comment]
@ikasty (1) works because Parcel uses a custom path resolver for js assets, and `.vue` is considered a js asset (2) doesn't work because path resolving of .less assets was passed on to `less`.

Personally I feel `@import "/resource/style.less"` is not a valid usage in this context. We can wait and see what others think about this issue :)
