### ISSUE TITLE
🐛 Parcel adds dependencies in package.json file

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#1190]
**Choose one:** is this a 🐛 bug

### 🤔 Expected Behavior

With `npm install parcel-bundler --save` only Parcel Bundler will be added to package.json as dependency.

### 😯 Current Behavior

All the following dependencies are added as well:

-  "vue-hot-reload-api": "^2.3.0",
- "vue/component-compiler-utils": "^1.0.0",
- "vue-template-compiler": "^2.5.16",
- "webpack-dev-server": "^3.1.3"

### 💁 Possible Solution

Install them as depencies of Parcel Bundler itself only

### 🔦 Context

While installing Parcel Bundler

**Comment by DeMoorJasper** [comment]
This is autoinstall? You can disable it using --no-autoinstall. I'm pretty sure parcel's install script doesn't do this (why would we have a webpack dep)

**Comment by scriptPilot** [comment]
Hey Jasper, I tried again, loading a simple .vue component. --no-autoinstall is activated but the following is added to my package.json:

"devDependencies": {
    "@vue/component-compiler-utils": "^1.0.0",
    "vue-template-compiler": "^2.5.16"
  }

How can I prevent that?

**Comment by scriptPilot** [comment]
So, the autoinstall feature itself is nice, but it should not add dependencies required by Parcel itself to the project package.json in my point of view. What do you think?

**Comment by devongovett** [comment]
Those dependencies are required to build vue files.

**Comment by scriptPilot** [comment]
Mhm, I do not get the point why they are not part of Parcel as dependency so that parcel-bundler is the only dependency for other projects. And for vue-hot-reload-api, what is the reason to put it as dependency if it's only needed for the development?

**Comment by devongovett** [comment]
Because not all projects built with parcel are vue projects, so we don't want the bloat of needing to install the vue compiler for non-vue projects. Now think bigger and imagine if we had to install those kind of dependencies for every framework/language parcel supported and parcel would be huge. Instead, we install what we need on demand.

**Comment by scriptPilot** [comment]
Ok, but why is the installation not done without adding the dependencies to the projects?

**Comment by scriptPilot** [comment]
So - I like your way of doing the installation by demand, good think. But I don't want to list all what's required by Parcel in my project package.json .... then it ends up in a list like with Webpack ... or is there any reason for I do not see?

**Comment by devongovett** [comment]
They *are* dependencies of the project which need to be versioned like the rest of your deps. Parcel installs the latest version if you didn't already declare one in package.json, but maybe sometime later vue comes out with a new version that is a breaking change. You wouldn't want your project to break because Parcel installed the latest version again later rather than the one your project works with.

**Comment by scriptPilot** [comment]
OK. Valid point, I do not find that explanation in the docs, do I?

But, in that case with Vue, why is *vue-hot-reload-api* listed in the dependencies and *@vue/component-compiler-utils* and *vue-template-compiler* listed in the devDependencies?

**Comment by devongovett** [comment]
currently build dependencies are installed as devDependencies where as dependencies actually used in the built code are full dependencies (they are installed by separate mechanisms). I suppose that particular one could probably be a dev dependency since the HMR code isn't enabled in production, but we'd need some extra code to do it.

**Comment by devongovett** [comment]
the distinction between devDependencies and dependencies isn't super relevant for frontend apps IMO. the separation is only so npm can know to exclude devDependencies when installing a module as part of another app. for frontend apps, you probably won't be publishing to npm anyway, so will always install all dependencies.

**Comment by scriptPilot** [comment]
OK, thanks.
