### ISSUE TITLE
🐛 Registering ServiceWorker fails with weird path

### ISSUE THREAD

**Issue by matthiasbayer** [parcel-bundler/parcel#1205]
### 🎛 Configuration (.babelrc, package.json, cli command)

No configurations (see example repo)
Command: `parcel packages/a/examples/live/index.html`

### 🤔 Expected Behavior

Parcel should find calls to `navigator.serviceWorker.register` and resolve the given path correctly to a public http url accessible by the browser.

### 😯 Current Behavior

Parcel finds the `register()` call, but resolves the path wrong. The browser can not load the serviceworker file, therefore the registration fails.

The URL produced by parcel in the example repository is `http://localhost:1234/......%08sw.js`

Also note that the serviceworker file does not appear in the `dist` folder.

_Console output_
![image](https://user-images.githubusercontent.com/1780547/38869626-9d0fe71c-424b-11e8-9994-d5d501e8d4d3.png)

_Service Workers panel_
![image](https://user-images.githubusercontent.com/1780547/38869654-b048097c-424b-11e8-9ab1-5ab72dc2a173.png)

### 💁 Possible Solution

The path should point to the correct address of the file. Parcel should put the file into the dist folder to make it accessible to the browser.

### 🔦 Context

-> See example repository

### 💻 Code Sample

Repository to reproduce the bug: https://github.com/matthiasbayer/parcel-sw

Steps to reproduce:

- `yarn install`
- `parcel packages/a/examples/live/index.html`
- open http://localhost:1234
- check console and Application -> Service Workers panel

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.11.1
| npm/Yarn         | yarn
| Operating System | Win10 & Linux

**Comment by matthiasbayer** [comment]
#670 looks like a similar problem

**Comment by filly82** [comment]
I have a similar issue. My service worker file compiles into the build-Folder (but with a subfolder in it)


src/index.js
src/service_worker.js

after compile

build/src.XXXX.js
build/src/service_worker.js

index.js does following: navigator.serviceWorker.register('./service_worker.js')

in the compiled version the browser is trying to load https://localhost:1234/srcservice_worker.js but it actually should be https://localhost:1234/src/service_worker.js (which works)

i would prefer the non-subfolder, since the index.js is in the same directory as the service_worker but gets compiled into a subfolder

**Comment by filly82** [comment]
still does not work. I've updated parcel to the latest commits
