### ISSUE TITLE
Links not working after bundling - "File not found"

### ISSUE THREAD

**Issue by jsdev17** [parcel-bundler/parcel#1312]
# ❔ Question

I'm using parcel, preact and preact router. My site has 3 tabs: About | Skills | Books.
When I build and open the site, the default route/components (`<About default path='/about' />`) renders
with all of its content. But when I click on any of the two other tabs, I get a "File not found; Browser can't find the file at /path (whichever one I clicked on)".

I don't understand what's causing this behavior... can someone help me understand and possibly fix this?

## 🔦 Context

I'm trying to get this site deployed but can't without these "links" working :(

## 💻 Code Sample

Not getting any errors in the console but here's my `App.js` component

```jsx
class App extends Component {
  render(props) {
    return (
      <div id='main'>
      {/* Components outside of router persist
      throughout all pages */}
        <Header />
        <Nav tabs={tabs} />

        <Router>
          <About  default path='/about'   />
          <Skills path='/skills'  />
          <Books  path='/books'   />
        </Router>
      </div>
    )
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.1.3
| npm/Yarn         | 6.0.0
| Operating System | Mac OS X Yosemite & Ubuntu Linux

**Comment by DeMoorJasper** [comment]
Could u update to the latest version, this should work though as we tried to make our server very supportive of spa’s

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsdev17** [comment]
@DeMoorJasper Hi there. I updated to `v1.8.1` but still not working 🙁

**Comment by jsdev17** [comment]
@DeMoorJasper I am running `parcel build index.html --public-url ./`. 
And this is the body of `index.html`

```html
<body>
    <div id="root"></div>
    <script src="src.8aead666.js"></script>
</body>
```

**Comment by DeMoorJasper** [comment]
Build has nothing to do with the server?
This is probably either a misconfiguration with your server or you're running this through the filesystem which is impossible with spa routing

**Comment by jsdev17** [comment]
@DeMoorJasper I'm not using a server. Excuse me, I'm not sure what you mean by "or you're running this through the filesystem" ... Running what through the filesystem?

**Comment by DeMoorJasper** [comment]
By filesystem I mean a local file opened in the browser without a server, (file://<directory>/index.html) You can use parcel serve or just parcel than parcel sets up a server for you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsdev17** [comment]
Ok, so I'll clarify: I'm not using a server of my own. I'm relying on parcel's server.
With that said, I don't think I'm serving any files... In some components, I'm importing a `data.json` file which contain links to images. Even on my main page (which renders successfully), I'm importing a `.json` file, so I doubt that's the issue.

When I run on parcel's server, the site works fine and I'm able to switch between tabs. It's only when I open the built `index.html` that the content of the other components don't render... 

@DeMoorJasper Would you be willing to take a quick look at [my repository](https://github.com/jsdev17/personal-site/tree/master/src) ? I'm not sure what's going on and have no clue how to fix i!

**Comment by DeMoorJasper** [comment]
Well there is nothing wrong with parcel or preact if the serve command works for routing.

I'll try to explain with an example:
You open index.html in your file explorer.

You have routes pointing to `/skills`, `/about` and `/books`.

So if you click on books for example it redirect to the absolute path /books, chrome (or any other browser) than redirects you to the root of your entire filesystem searching for the file books which probably doesn't exist, resulting in failing. This is because of how these routers work. Servers for SPA's are configured to redirect all traffic to the index.html page to make this work. Browsers can't do this because it would defy their ability to navigate through the filesystem.

Hope this clears everything up and wasn't too long of a read.

I'll close this issue for now as I have tried to explain this to the best of my ability and are sure this is probably not a parcel bug.

**Comment by jsdev17** [comment]
@DeMoorJasper why does the SPA work when I run it on parcel's server, but not when I build?

**Comment by askesis** [comment]
@jsdev17 Hi, I faced with the same problem and here that I have learned
When you run `parcel build`, you get `<app_name><hash>.<extensions>` files and this is your built app.

You should have the server for handling your routes, because when you click on the link, url is changing but you haven't file with matched name. Therefore, you get the 404 error.

I added express server with several line of code, which give `index.html` at transition to any route and deployed this as node application on the heroku. 

That isn't beautiful solving, but I haven't other.
