### ISSUE TITLE
How can i ignore bundling of images?

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#1379]
Is there any way in parcel to ignore bundling of certain assets. I am running parcel on my html file and i only want to bundle my js files. Is there any way to achieve this?

**Comment by derolf** [comment]
All the referenced tickets contain some sort of workaround or special semantics to avoid having a configuration.

I think we are in a catch22 here — what is the lesser evil: special semantics, workarounds, or a configuration?

**Comment by sgf** [comment]
how Exclude some Modules such like Vue.js,i hope the parcel do not pack Vue in the Single Js output file.

**Comment by DeMoorJasper** [comment]
@sgf not sure if I understand, Vue is part of the app right?

Open up a new issue with examples and a more detailed description

**Comment by sgf** [comment]
@DeMoorJasper
yes but some time ppl need use CDN.
and i found the parcel Parse some dependencies is incorrect

**Comment by npulidom** [comment]
@nrgwsth, if you are using stylus, I resolved using [`embedurl`](http://stylus-lang.com/docs/functions.url.html) instead of `url` or `src` directives in your stylus files. Parcel will ignore that directive and stylus will replace that directive for `url`, keeping the relative path.
```styl
.my-class
    background embedurl('../images/icons/action/upload.svg') no-repeat
```

**Comment by revelt** [comment]
I think this ticket was closed prematurely and should be reopened. #144 is about `node_modules` and ignoring `React`. 

If it helps, let me describe the problem again.

Imagine a static website project (Eleventy) using Parcel to process `.pcss` files. That's PostCSS — it does need to be processed. However, images used there, as in `background-image: url("images/image.png")` — don't. That's because Eleventy is set up to copy all static assets directly to `dist/images/` and Parcel messes up the paths. And image optimisation is done manually, in PS.

As a temporary measure, I have to use absolute paths and hardcode `http://localhost`, then use another script to run during `prod` builds and rename that into real domain url...

If this challenge is somehow solved already (I saw vague [comments](https://github.com/parcel-bundler/parcel/issues/144#issuecomment-602136307) on #144 alluding it's solved on Parcel v2), then documentation needs to address this — this ticket is a great way to track *documentation* tasks like that.

Personally, I'd solve this by adding a [glob](https://github.com/sindresorhus/globby) whitelist on asset paths. Parcel would still try to resolve as usual, but it would skip user-supplied glob paths. For example, in package.json, user would add `parcel: { ignore: { "*/images/*"` and all paths in `.pcss` that Parcel tries to resolve would get skipped. It's easy to make a program to skip operations, isn't it?

**Comment by hash-bang** [comment]
This is a blocking issue for us moving to Parcel too.

To give a really easy example assume the following HTML:

```html
<img src="/assets/logo.svg"/>
```

Our web server handles the serving of everything from the `/assets` directory (properly cached and 304 handled). We don't want those resources bundling into Parcel but there is no way I can find of excluding them.

Having a glob list of excluding files as suggested by @revelt would be great.

**Comment by nikrowell** [comment]
> There currently is no way to ignore certain files.

@revelt @hash-bang I know this is an old discussion, but adding the following to the top of `Asset.addURLDependency`seemed to achieve to goal of ignoring certain files. Perhaps there is a way to do this through a plugin if someone is interested.

```js
if (url.endsWith('.svg')) {
  return url;
}
```

**Edit:** Basic plugin created - [parcel-plugin-ignore-assets](https://www.npmjs.com/package/parcel-plugin-ignore-assets) - I'm sure this overlooks a lot of use cases, but met my needs while using still using Parcel 1.x

**Comment by hash-bang** [comment]
@nikrowell, oh wow. Thanks for that.

**Comment by VladimirMikulic** [comment]
I've made a plugin that excludes assets from bundling in Parcel 2.
Check it out https://www.npmjs.com/package/parcel-resolver-ignore

1. `npm i parcel-resolver-ignore -D`
2. `.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-ignore", "..."]
}
```
3. `package.json`
```json
{
  "parcelIgnore": [
    "assets\/*.*"
  ]
}
```

It's good to go!
Let me all know what you think!
