### ISSUE TITLE
Production Files structre

### ISSUE THREAD

**Issue by itarafath** [parcel-bundler/parcel#1512]
# ❔ Question
How to get output like below folder structure
/dist/
   - index.html
   - js/my-web-site.61a00d0d.js
   - img/1.jpg
   - img/2.jpg 
   - css/my-web-site.5de2c0ee.css
## 🔦 Curretnt Folder Struncture
/dist/
   - index.html
   - my-web-site.61a00d0d.js
   - 1.jpg
   - 2.jpg 
   - my-web-site.5de2c0ee.css 

## 🌍 My Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.9
| Yarn         | 1.6
| Operating System | UBUNTU 18.04

**Comment by huixie** [comment]
ask too

**Comment by mohsen1** [comment]
Why you care about this? Those files are all considered "static assets"

**Comment by BenSapiens** [comment]
I have a similar question. For example, I have a directory structure like so:

/src/
* index.html
* index.js
* img1.jpg
* contact/index.html
* contact/index.js
* contact/img2.jpg

But after Parcel gets ahold of it:

/dist/
* index.html
* index.asdffdsa.js
* contact.asdffdsa.js
* img1.asdffdsa.jpg
* img2.asdffdsa.jpg
* contact/

This breaks when setting options.publicUrl to "./" (as seen on https://parceljs.org/api.html). `/dist/contact/index.html` can no longer access its index.js because it has the entry `<script src="contact.asdffdsa.js"></script>`, but `contact.asdffdsa.js` is now located in `/dist/`, not `/dist/contact/`.

Is this how it's supposed to work? And can I disable it?

**Comment by dfkaye** [comment]
Had this problem recently a week or two ago. The simple parcel command `parcel build entry-point` resolves everything to that point. To preserve the directory structure for certain assets, such as

```
entry-point.html
src/
    img/ (svgs and pngs here)
    style/ (css files here)
```

then, specify multiple entry points, as e.g., `parcel build entry-point.html src/img/**.svg src/img/**.png src/style/**.css`

(Note: assumes your html includes a script tag pointing to an entry/index.js that will be bundled up as well.)

**Comment by devongovett** [comment]
It will be possible in Parcel 2 by overriding the default namer plugin.
