### ISSUE TITLE
Parcel build does not read .env when enable no-source-map

### ISSUE THREAD

**Issue by minhchu** [parcel-bundler/parcel#1544]
# 🐛 bug report

In `.env` I have `DOMAIN=mydomain.com`
When I run `parcel build index.html --target browser --no-source-maps`, it generates `src.hash.js` file. 
I run `cat dist/src.hash.js | grep mydomain` to make sure it builds correctly but nothing returns.
When I remove `no-source-maps` option it works normally

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 6.14.2 |
| npm/Yarn         | 1.6.0 |
| Operating System | 16.04 |

**Comment by Strajk** [comment]
In my case, env vars exposing was working great but suddenly stopped, found this issue, tried to **add** `--no-source-maps` and it fixed the issue, when I removed `--no-source-maps` param it still worked...

Looks it's somehow caused by caching, cause deleting `.cache` folder made it work too.

Another issue https://github.com/parcel-bundler/parcel/issues/1625

**Comment by DeMoorJasper** [comment]
Adding and removing `--no-source-maps` would cause the options to change, so cache would be invalidated. Resulting in the same effect as clearing the .cache folder.

So this is probably a cache issue as @Strajk discovered

**Comment by minhchu** [comment]
I've just tested again so this is a cache issue. Should I close this ticket now

**Comment by DeMoorJasper** [comment]
@minhchu it would still be usefull to fix the cache issue, at least if we can pinpoint when this happens and why

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
