### ISSUE TITLE
Compare performance with fusebox

### ISSUE THREAD

**Issue by leonardoanalista** [parcel-bundler/parcel#156]
I m just curious to see the performance comparison with fusebox. It would be great if we had some numbers and please put on the readme under your benchmark heading.

Cheers Leo

**Comment by davidnagli** [comment]
This has actually already been proposed! See #10 

Unfortunately, we have decided that we aren't going to be adding any more benchmarks until we finish making Parcel the best it can be. We want to spend our efforts making it better rather than spending time comparing ourselves to others.

Also see: #61
