### ISSUE TITLE
stdout maxBuffer exceeded with Rust

### ISSUE THREAD

**Issue by remexre** [parcel-bundler/parcel#1573]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No `.babelrc`, using `parcel serve --no-hmr src/index.html` (via `npm run serve`).

```json
{
  "author": "Nathan Ringo <remexre@gmail.com>",
  "bugs": {
    "url": "https://github.com/remexre/evaltrees/issues"
  },
  "description": "The web port of evaltrees.",
  "dependencies": {
    "xterm": "^3.4.1"
  },
  "devDependencies": {
    "parcel-bundler": "^1.9.1"
  },
  "homepage": "https://github.com/remexre/evaltrees#readme",
  "license": "Apache-2.0 OR MIT",
  "main": "src/index.html",
  "name": "evaltrees",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/remexre/evaltrees.git"
  },
  "scripts": {
    "build": "parcel build --detailed-report src/index.html",
    "serve": "parcel serve --no-hmr src/index.html",
    "watch": "parcel watch src/index.html"
  },
  "version": "0.1.0"
}
```

## 🤔 Expected Behavior

Ideally it'd compile :P

## 😯 Current Behavior

When trying to build a Rust project, I get `stdout maxBuffer exceeded`:

```
🚨  /home/nathan/Projects/evaltrees/src/lib.rs: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
```

## 💻 Code Sample

`index.js`:

```
import evaltrees from "../../src/lib.rs";
import ui from "./ui.js";

console.log("test");
```

The Rust code is unchanged from [this commit](https://github.com/remexre/evaltrees/tree/2756a9f1cba214fb137aa9d8729f1ea3a3f4a8ed).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.1 |
| Node             | 8.11.1 |
| npm/Yarn         | npm 5.6.0 |
| Operating System | Arch Linux |
| rustc | 1.26.2 |
| cargo | 1.26.0 |

**Comment by cedric-h** [comment]
I'm still getting this

**Comment by rail-rain** [comment]
Most of the time the error `stdout maxBuffer exceeded` when using RustAsset caused by the execution of `cargo metadata` [here](https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/core/parcel-bundler/src/assets/RustAsset.js#L131) because `cargo metadata` emits every data.

I can think of three solutions:

1. Extending `maxBuffer` of `execFile`.
2. Using `spawn`, which doesn't have a buffer limit thanks to streams, instead of `execFile`.
3. Setting `no-deps` option in `cargo metadata`, which omits information about dependencies and significantly reduces the size of output.

Setting `no-deps` seems to have no disadvantages and be easy to do. However, RustAsset are being replaced and [the new one](https://github.com/parcel-bundler/parcel/issues/3365) might not have the problem somehow.
