### ISSUE TITLE
src/assets/SASSAsset.js auto add ./ to import path while import from node_modules

### ISSUE THREAD

**Issue by bung87** [parcel-bundler/parcel#1610]
# 🐛 bug report

upgrade to 1.9.3 because of need this patch https://github.com/parcel-bundler/parcel/commit/40fb76f8d12fe17b4e8e3eebe1a988d11d31e106
but face new issue,it does exist before upgrade to 1.9.3,then I checked the source found it may cause this problem.
https://github.com/parcel-bundler/parcel/commit/f536e8bf8d8212bb314328458c8da2b4bcd8c15f#diff-84c08db622e83576a023e956e4d3a635R1

``` shell
> s="somepackage/some.sass"
'somepackage/some.sass'
> /^(~|\.\/|\/)/.test(s)
false
> /^(~\/|\.\/|\/)/.test(s)
false
> 
```
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

correctly import `"somepackge/some.sass"`
correctly import `"@somenamespace/somepackge/some.sass"`
## 😯 Current Behavior
alwasy treats import path as relative path

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
This is due to how the css ecosystem has evolved to the following strange standard.

Relative:
`somedir/file.sass` or `./somedir/file.sass`
Node modules
`~module/file.sass` or `~@somenamespace/somepackge/some.sass`
Root
`/somedir/file.sass`

We've just updated this to be compatible with the current ecosystem.
