### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by cubeweb** [parcel-bundler/parcel#1688]
Hi,

I am getting an 'Unexpected end of JSON input while parsing near '...d-comments":"^1.1.2"' when I run the npm install -g parcel-bundler command, I tried with sudo and to install only on project dir but I get the same error

**Comment by KeineLimonade** [comment]
Can you provide a full stacktrace? By now it is only clear that there is an error parsing a file that should be valid `json`, but somehow is not.

**Comment by cubeweb** [comment]
I did an npm delete cache and now I don't get the error, I even reinstall node just in case and now I am stuck on  fetchMetadata: sill resolveWithNewModule babel-helpers@6.24.1 checking installable status.
It stays there forever, I am not sure if its something on my system that causes that.

**Comment by cubeweb** [comment]
FYI if I run npm install -g parcel-bundler again it goes to the next package and stays there now I am on loadDep:babel-types: sill resolveWithNewModule balanced-match@1.0.0 checking installable status for 5 min, should it take so long?

**Comment by cubeweb** [comment]
I manage to install with yarn, with npm no luck.

**Comment by DeMoorJasper** [comment]
Might be an npm bug, probably something with an invalid JSON (npm and yarn probably use a different parser).

As your bug originates from a package that's not Parcel it would probably be helpfull to get the fullname instead of `'...d-comments":"^1.1.2"'`

Probably best to look into their package.json and have a look what might be up (run it through a json validator if needed)
