### ISSUE TITLE
Is it possible to target electron-renderer? 

### ISSUE THREAD

**Issue by michaelchiche** [parcel-bundler/parcel#1738]
# ❔ Question

Hi, I am new to parcel, and I was wondering if there was a way to build with parcel and target for electron-renderer? I saw that there is a target electron, but it removed all the node_modules and then my app does not work anymore?

## 🔦 Context

I need build for electron-renderer/electron to be able to do:
```js
import { ipcRenderer } from 'electron';
```
I need access to this in my react app. Parcel worked perfectly to target the browser, but I can't completely switch to parcel until I can build both electron and web apps with it.

I saw that #1690, which looks like it _might_ be the solution to my problem?
because now, when I build with target electron, I get react not found.

Thanks for your help

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel         |  1.9.7 
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by Hammster** [comment]
`target: 'electron'` is exactly for this usecase, you probably did not seperate the building for your main (target: node) and render process (target: electron).

A little side advice since i wrote multiple electron apps with building tools in the past, you don't really need to build the main process files, electron understands ES6 and the new 3.0.0 beta can also use the import syntax ;)

**Comment by michaelchiche** [comment]
Hi @Hammster, thanks for the quick reply!

To explain what I am doing. maybe it is not the way it should be done?

I have an `index.web.js` and an `index.electron.js` file 

the `index.electron.js` needs access to `ipcRenderer`, but when I do that, it does not bundle react in the electron one.

Is this the way intended? or did I miss something?

**Comment by Hammster** [comment]
`ipcRenderer` is only available in `index.web.js` it is not meant to be accessed from the main process you would use `ipcMain` for that. 😉 

Feel free to contact me on the parcel slack, on mail, twitter (@hammster1911) or the new parcel spectrum channel, if you need further help, since this issue is not really parcel related ;)

**Comment by michaelchiche** [comment]
index.electron.js is imported in a index.electron.html, it is in the renderer process. I just sent you a DM on twitter. Thanks

**Comment by nocke** [comment]
> target: 'electron' is exactly for this usecase, you probably did not seperate the 
> building for your main (target: node) and render process (target: electron).

Hi @Hammster, just to verify and double-check with you:

* `main.js` should be `--target: node`
* `renderer.js` (“client-side”) should be `--target: electron`

Correct?

That would mean, [this boilerplate for example](https://github.com/shamofu/electron-react-parcel-boilerplate/blob/master/package.json#L14) is doing it wrong?

If that is true, perhaps we could make that more explicitly clear [in the api docs](https://parceljs.org/cli.html#target)?

Many people appear to run into a seeming [import/fs issue](https://github.com/electron/electron/issues/9920), which (if I understand correctly) is related...

**Comment by lukejagodzinski** [comment]
@Hammster are you sure I can use import syntax in the main process? I'm using Electron 4.0.1 and I get syntax error when I try to use import statement. How can I do that without building using parcel?

**Comment by Hammster** [comment]
You need to enable ESM support via the `--js-flags` see [here](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--js-flagsflags) and [here](https://nodejs.org/api/esm.html)

If you don't want to depend on the node flag for the main process since it is still marked as experimental, you can use the `esm` package to do it see [here](https://github.com/standard-things/electron-quick-start/commit/4c7db9ce472a6c102890e23241e57feab6152568)

**Comment by lukejagodzinski** [comment]
@Hammster using `--js-flags` doesn't work:

```
"main:start": "electron --js-flags='--experimental-modules' ."
```

throws error: `Error: unrecognized flag --experimental-modules`. And of course my main file is called `main.mjs` as documentation says.

I've used to use the `esm` package and it work pretty well but I don't like an idea of the extra file being referenced first.
