### ISSUE TITLE
Is there a release schedule available?

### ISSUE THREAD

**Issue by gkjohnson** [parcel-bundler/parcel#1871]
Hello!

I'm really liking the direction that parcel is going and there have been quite a few PRs over the last couple weeks that I'm looking forward to but unfortunately they still aren't available. Is there an expected timeline for the next release?

More broadly -- is there a release schedule or roadmap that we can use to keep track of when new features will be available? Some of the newer features will finally allow me to start to moving some older projects to parcel.

Thanks again!

_Edit_ Sorry if this isn't the right place to ask this -- I wasn't quite sure where to go!

**Comment by DeMoorJasper** [comment]
There is no real fixed release schedule for parcel.
Mainly because the core team are all volunteers, who can't reliably predict how much time they'll be able to spend on it every week/month. Every PR has to be approved by at least one member of the core team, so that takes time. Devon is the one doing the actual publishing to npm so npm releases are dependent on him finding the time to review the current state of the master branch and pushing an update to npm.

We are always welcoming new contributors to speed up development of parcel.

Hope this answers your question.

This is the right place to ask about next releases, we also have `spectrum.chat/parcel` for this kind of questions, but github issues are fine :)

**Comment by gkjohnson** [comment]
Hey @DeMoorJasper Thanks for the quick response!

That all makes sense and I'm sure you know how much we all appreciate the work that gets put in to the project.

Regarding more immediate plans, is there any estimate for the next release of parcel with the current features in master?

Thanks again!

**Comment by DeMoorJasper** [comment]
@gkjohnson probably next week

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
