### ISSUE TITLE
Why are there parcel and parcel-bundler packages in npm register?

### ISSUE THREAD

**Issue by Bludater** [parcel-bundler/parcel#1872]
# ❔ Question
Here they are:
- [parcel-bundler](https://www.npmjs.com/package/parcel-bundler)
- [parcel](https://www.npmjs.com/package/parcel)

**Comment by DeMoorJasper** [comment]
Because parcel on npm originally was something else and it got confusing for users of parcel-bundler. After releasing parcel we eventually got the parcel pkg as well. It’s just the same as parcel-bundler, note it will nog work with most plugins though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bludater** [comment]
I learned that the hard way.
→I installed parcel and plugin and it won't work.

**Comment by DeMoorJasper** [comment]
Yeah Idk if we should resolve that, it's just a matter of time before parcel moves into the parcel organisation on npm. (Probably parcel2+)

**Comment by peanutbother** [comment]
Could we put a NPM warning for install script when we're installing `parcel`instead of `parcel-bundler`?
like this:
```json
{
...
"install":"echo You are using the wrong package! Please use Parcel-Bundler instead!"
}

```

**Comment by DeMoorJasper** [comment]
might be a good idea

cc @devongovett
