### ISSUE TITLE
Elm minification is not two-phase

### ISSUE THREAD

**Issue by Janiczek** [parcel-bundler/parcel#2062]
# 🐛 bug report

To be most effective, Elm minification with `uglifyjs` should be [done in two phases](http://elm-lang.org/0.19.0/optimize). It is currently [done in one phase](https://github.com/parcel-bundler/parcel/blob/master/src/assets/ElmAsset.js#L89-L119).

## 🤔 Expected Behavior

The minification process does something analogous to this:
```bash
uglifyjs elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' --output=elm.phase1.js
uglifyjs elm.phase1.js --mangle --output=elm.min.js # phase 2
```

As seen in the [official Elm page](http://elm-lang.org/0.19.0/optimize):
> Note 1: uglifyjs is called twice there. First to --compress and second to --mangle. This is necessary! Otherwise uglifyjs will ignore our pure_funcs flag.

## 😯 Current Behavior

Currently the options passed to `uglifyjs` have both compress and mangle options set, and `uglifyjs` is only called once, as seen here: https://github.com/parcel-bundler/parcel/blob/master/src/assets/ElmAsset.js#L89-L119

Thus, there are gains to be ... gained! :thinking: :sweat_smile: 

## 💁 Possible Solution

Let's call the `uglifyjs` twice, with two different options, closely modelling the recommended CLI usage.

**Comment by kzc** [comment]
> To be most effective, Elm minification with uglifyjs should be done in two phases. It is currently done in one phase.

That's not required in Terser because `pure_funcs` works correctly with both `compress` and `mangle` enabled in the same `minify` invocation.

`pure_funcs` in `uglify-js` can also be made to work correctly with both `compress` and `mangle` enabled if the `rename` pass is disabled via `--no-rename`.

See:

* https://github.com/parcel-bundler/parcel/pull/1968#issuecomment-417700311
* https://github.com/rtfeldman/elm-spa-example/pull/54

However, the caveat is that `parcel` only performs Terser `compress` per JS asset and does not perform `compress` on the final bundle.  It would produce a smaller bundle if each asset were not minified individually, but instead only invoke minify on the final bundle - as webpack and rollup typically does.

**Comment by Janiczek** [comment]
Ah, thanks for clarifying!
