### ISSUE TITLE
Parcel 2: Extract Logger into its own package

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2134]
Extract the logger from Parcel 1 into its own package in the monorepo for Parcel 2, as `@parcel/logger`. It should go in the `packages/core/logger` folder. Parcel 1 should be updated to use the new package as well.

**Comment by webtaculars** [comment]
Hi @devongovett. I would be happy to help on this issue if you can guide me.

**Comment by devongovett** [comment]
@webtaculars awesome! I am working on setting the monorepo up today on master, and once that's done it's a matter of moving some files around and getting the new package set up. Will comment back here when ready. Thanks!

**Comment by devongovett** [comment]
@webtaculars ok, monorepo is set up!

So basically what needs to happen is this:

* Make a folder in `packages/core/logger`.
* Move `Logger.js` and other local dependencies (mostly utils) into `packages/core/logger/src`, and the tests into `packages/core/logger/test`. Looks like it's also dependent on the worker farm, which is being extracted into its own package in #2132. May need to wait for that one first...
* Create a `package.json` file for the `@parcel/logger` package in that folder. Add all of the dependencies of the `Logger.js` to that `package.json`.
* Setup a test script for that package using mocha.

Please comment back here if you have questions!

**Comment by webtaculars** [comment]
Hi @devongovett, I have created a pull request GH-2165. But I have a few questions

1. `@parcel/logger` uses `prettyError.js` and `emoji.js` utils. You asked me to move utils from the core but these two utils are also used by other modules. So I have replicated both utils functions in the logger package. Any other way to implement this that you can suggest?

2. Since you asked me to wait for the worker farm issue, I have created the PR by taking `workerfarm-package ` branch as the base. Should I create the PR from master?

**Comment by devongovett** [comment]
Awesome, thanks!

1. Hmm yeah. I'm not certain what we're going to do with these types of utils yet. Perhaps a `@parcel/utils` package? Or maybe in these two cases, they could be accessed as part of the logger package?

2. I merged that branch into master, so if you could rebase that would be great.

**Comment by webtaculars** [comment]
1. I was thinking to make both the utils functions as a part of logger package.

2. Rebase done

**Comment by devongovett** [comment]
Awesome, thanks for your work on this!
