### ISSUE TITLE
Parcel 2: CoffeeScript transform

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2160]
Create the `@parcel/transform-coffeescript` package in `packages/transforms/coffeescript`. This package is a Parcel 2 transform plugin for CoffeeScript. It will be based on the `CoffeeScriptAsset` from Parcel 1.

The `@parcel/transform-coffeescript` package is responsible for the following things:

* Transforming CoffeeScript to JavaScript
* Generating source maps.

**Comment by js-sapphire** [comment]
Hi, I want to pick this. I am new to OSS. Any pointers on how to begin?

**Comment by reebr** [comment]
I would like to contribute in this issues related of Parcel 2.
But I have the same question of @js-sapphire. Is there anything explaining how to begin @devongovett ?

cc @DeMoorJasper

**Comment by DeMoorJasper** [comment]
@reebr you can find an example for a v2 transform here (JS transform): https://github.com/parcel-bundler/parcel/tree/next/packages/transforms/js you can also have a look at the RFC
I'm not entirely sure if it's 100% up to date though.

I'd personally start of with an easier issue, something that's just extracting logic into a package (without rewriting a lot of code [maybe #2144 ?]) in the monorepo to get a bit of a feel of how parcel is structured (as parcel 2 is mainly design at the moment and largely still in the `next` branch).
Also I think the `next` branch should eventually end up in master so probably good to wait a bit until that happened before writing parcel 2 plugins, so you could also test it out properly.

**Comment by kwelch** [comment]
I believe with the merged PR(#3107) this is all set. If not let me know if there is any more I can do.

**Comment by mischnic** [comment]
I think source maps are missing?

**Comment by kwelch** [comment]
I think with that PR we should be set to close this.

**Comment by Leftium** [comment]
How are options passed to the Coffeescript transformer? (I would like to set the 'bare' option so the generated output works with Svelte.)

I think logic has to be added to this coffeescript transformer to support custom options, but I'm having trouble finding/understanding the base Transformer class.

It seems other transformers have a "getConfig()" method that specifies files that have custom options. For example: [Pug transformer](https://github.com/parcel-bundler/parcel/blob/cf6c31c7b35c67e0e23bd334d62aca375c18d712/packages/transformers/pug/src/PugTransformer.js#L9-L11)

Since the coffeescript transformer lacks this method, is there default transformer behavior that looks for custom option files based on the package name? (.coffeescriptrc, .coffeescriptrc.js, coffeescript.config.js)

Or can the custom options always be specified in package.json based on the name of the transformer? (in a field called "coffeescript")

**Comment by mischnic** [comment]
I think this the current way (`getConfig` is deprecated):
```js
async getConfig({config}){
  return await config.getConfig(
    ['.coffeescriptrc'],
    {packageKey: 'coffeescript'});
}
```
@padmaia ?
