### ISSUE TITLE
Would you consider not relying on deasync if it turns out that it's the only one with native dependencies?

### ISSUE THREAD

**Issue by xaduha** [parcel-bundler/parcel#2214]
I've grepped deasync and it doesn't seem terribly necessary. Only used here https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Asset.js#L122-L127

https://github.com/parcel-bundler/parcel/blob/75310e15f6fa3c8a0ce6593ada1bcca00240ea54/packages/core/parcel-bundler/src/utils/syncPromise.js

And it causes issues when installing on various platforms https://github.com/parcel-bundler/parcel/issues?utf8=✓&q=deasync

**Comment by DeMoorJasper** [comment]
Well yeah it's deprecated. We could remove it and then the getter should throw an error instead of warn. It would however be a breaking change in the API and that's also the only reason it's there.
Not sure if any plugins still use the old API though. You could do some research and open a PR if you can't find any plugins that use it.

**Comment by xaduha** [comment]
As long as it is going away at some point it's fine by me, v1.6.2 is good enough in the meantime.

**Comment by DeMoorJasper** [comment]
It'll definitely not be part of `Parcel 2` as the plugin API for that is gonna be totally different.

I'll close this for now.

**Comment by felixfbecker** [comment]
This is really painful when building Docker images. If you depend on node:alpine, it does not have Python installed. You need to install Python only for this dependency of Parcel.
