### ISSUE TITLE
 Could not load existing sourcemap in yarn v1.12

### ISSUE THREAD

**Issue by zanisis** [parcel-bundler/parcel#2266]
# ❔ Question
it's bugs or not i got something error like this: Could not load existing sourcemap of "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js"
when i try using yarn start and execute "cp .env.local .env && parcel public/index.html"
but in npm start is not warning error

## 🔦 Context

always running on .env.local can set periority where .env avail?

## 💻 Code Sample
```
"scripts": {
    "start": "npm-run-all -s env-local serve-local",
    "serve-local": "parcel public/index.html --port 11030",
    "env-local": "cp .env.local .env",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.10.3
| Node             | v10.13.0
| npm/Yarn         | yarn v1.12.3 npm v6.4.1
| Operating System | MacOS High Sierra 10.13.6

**Comment by devongovett** [comment]
`Could not load existing sourcemap` is a warning when Parcel cannot find a source map that is linked from a javascript file, in this case `mutationobserver.min.js`. This is probably a bug in the `mutationobserver-shim` package - they probably don't include the source map in the published files for the package. You could file an issue there instead, but you can also ignore the message since it's just a warning.

**Comment by saracura** [comment]
Hi. How could it be done to ignore the message if in the end comes the following output:

root@django-digio:/home/django/python3/projetos/chatCompleto/justchat/frontend# parcel index.html
Server running at http://localhost:1234
⚠️  Could not load existing sourcemap of "node_modules/mutationobserver-shim/dist/mutationobserver.min.js".
⠧ Building hmr-runtime.js...Killed
