### ISSUE TITLE
Does the cache get invalidated after node_modules is recreated?

### ISSUE THREAD

**Issue by etamponi** [parcel-bundler/parcel#2283]
# ❔ Question

As the title say: does the parcel cache (the one in `.cache`) get invalidated if I recreate my node_modules? If so, why?

## 🔦 Context

Sometimes on Glitch we need to recreate the node_modules for a project. This causes parcel to take way more time, and it looks like it just ignores the cache it has in `.cache`.

## 💻 Code Sample

1) Remix https://glitch.com/edit/#!/parcel
2) ~Open the Console (Status -> Console) and run `enable-pnpm`. This will cause the node_modules to be recreated~. Open the Console (Status -> Console), run `rm -rf node_modules/* node_modules/.* && refresh`. This will cause the node_modules to be recreated.
3) See in the Logs (Click again on Console): parcel takes around 60-70 seconds to build the bundle
4) Make a change to `watch.sh`: parcel now takes around 5-10 seconds, because it is using its cache (I think).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | any
| npm/Yarn         | pnpm (compatible with npm/yarn)
| Operating System | Linux

UPDATE: fix Code Sample

**Comment by devongovett** [comment]
I assume `enable-pnpm` reinstalls dependencies using pnpm instead of npm/yarn? Doesn't pnpm use a different directory layout for node_modules (ie lots of hard links and symlinks)? https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3

To answer your question, yes, this will require parcel to invalidate its cache since the location of the resolved modules changed.

Also, because of the strange directory layout that pnpm follows, the resolution process is possibly slower. There are a lot more directories to traverse in that layout. To verify, have you tried pnpm and parcel locally to see if there is a perf difference vs yarn/npm?

**Comment by etamponi** [comment]
Sorry, I described the issue wrong. I was _already_ using `pnpm`. Running `enable-pnpm` destroys the current node_modules and recreates it. So it's not because of different package location, they were already in the same places. Perhaps the cache takes package timestamps into account too?

**Comment by em** [comment]
That's expected because of the way the cache works. If any file's source.lastModified > cache.lastModified it rebuilds. Recreating node_modules means they all have new new lastModified dates.

I've been digging through that code and searching issues trying to find why it seems to rebuild everything randomly even when the last modified times are not affected. : \
