### ISSUE TITLE
Parcel 2: Tree Shaking

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2395]
Port the tree shaking code from Parcel 1 to run in Parcel 2. It would be super awesome if it were a separate package that could be tested outside the rest of Parcel as well.

TODO: fill in details

**Comment by mischnic** [comment]
> Parcel/Webpack/Rollup tree-shaking compatibilities: https://github.com/selfrefactor/tree-shaking-example.

In every listed test, rollup produces much smaller bundles 😕

**Comment by devongovett** [comment]
Hmm that’s a good resource for us to base our work on, though it’s a little suspicious that every single result from Parcel is 1.2Kb while the others change size. Seems like maybe something went wrong there.

**Comment by mischnic** [comment]
I've updated that repo (and the results): https://github.com/mischnic/tree-shaking-example
Not quite sure though if the webpack and rollup config can be optimized.

**Comment by devongovett** [comment]
Awesome, thanks for doing that. This is really useful!

Now the rollup ones seem kinda large. Any idea?

**Comment by mischnic** [comment]
Oops, rollup was missing terser. 🙈 Results are updated

**Comment by mischnic** [comment]
I guess this would become `@parcel/optimizer-***`

**Comment by mischnic** [comment]
In the Parcel 2 RFC `terser` is listed as optimizer, which "accept a bundle instead of a single asset". Currently, there are no optimizers implemented, is this a design change or not yet final?

It there were transforms and optimizers were available, there would be two possibilites:
- scope hoisting as a transform, directly integrate the concatenation and import/export checking (not possibile as a plugin?), tree shaking as a optimizer -- this would work exactly like Parcel 1
- scope hoisting as a transform, directly integrate the concatenation and import/export checking (not possibile as a plugin?), reuse a terser -- this would improve build size for a slower build time (see #2310)

**Comment by devongovett** [comment]
Well, optimizers run after packagers, so I think the concatenation phase of tree shaking would at least need to be a packager rather than an optimizer. The existing js packager wraps every module in a function, which is what we want to avoid with tree shaking.

In order to do the concatenation correctly, we actually need to re-parse the assets into ASTs and combine them together in AST form rather than string form. At that point, we might as well also run the dead code eliminator over the existing AST within the packager rather than do it in an optimizer, which receives a string as input instead of an AST.

**Comment by devongovett** [comment]
Closed by https://github.com/parcel-bundler/parcel/pull/2967
