### ISSUE TITLE
更改css

### ISSUE THREAD

**Issue by jeasoncc** [parcel-bundler/parcel#2443]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by jeasoncc** [comment]
更改css不自动刷新。控制台报 clear all console

**Comment by dandv** [comment]
What makes you think we read Chinese?

**Comment by mischnic** [comment]
Google translate says that hot reloading CSS doesn't work.
But there's nothing we can do without a code sample.

**Comment by Hammster** [comment]
@dandv because it is not a given that everybody knows English, well enough to open up a issue or check the result of google translate to be correct? Also there is a huge Chinese community on GitHub so there will be plenty of people be able to translate, and parcel is no exception. Also i think its very unpolite to thumbdown him just for that.

@jeasoncc (翻译) 你能分享你的项目吗？

**Comment by dandv** [comment]
@Hammster 

> because it is not a given that everybody knows English, well enough to open up a issue or check the result of google translate to be correct?

Do we know Chinese well enough to read the issue or check the result of Google Translate to be correct?

> Also i think its very unpolite to thumbdown him just for that.

It was also for mangling the issue template and is it polite of him to simply post in Chinese in an English community? Why would *each of us* spend time Google Translating and wondering about the correctness of the result, when the OP could Google Translate *once*?

Don't get me wrong, I appreciate the Chinese culture and contributions to the world, am not a native English speaker either, but whether we like it or not, [the lingua franca of the Internet is English](https://en.wikipedia.org/w/index.php?title=English_language&oldid=410578433#Significance). I've written [extensively](https://wiki.dandascalescu.com/essays/english-universal-language) about this issue, and [particularly in open source communities](https://github.com/coreinfrastructure/best-practices-badge/issues/230#issuecomment-411641565).

**Comment by Hammster** [comment]
@dandv It is simpler for us to figure out if the translation is actually right or not since we are at the receiving end and would know if the sentence is off 😉. As a polyglot with background in language science I actually know how devastating scary it is to write in a language which you're unfamiliar with. And this is even more true for Chinese who still are not 100% capable to even access all open source communities.

Also i don't want to argue on a issue on GitHub, feel free to write me on twitter or by mail if you want to discuss the topic further, if you want to. But you're right that he should have tired to make the issue properly (even if it was fully Chinese)

**Comment by yordis** [comment]
@Hammster el problema es que por quere se inclusivo con un grupo, te vuelves exclusivo con otro grupo por naturaleza cuando se trata de este tema porque fuerzas a otros a ser parte del grupo que intentas apoyar, porque en realidad, no estas siendo inclusivo en absoluto, solo estas cambiando el grupo afectado.

Si todos hablamos nuestras lenguage maternas la friccion en comunicacion incrementa eventualmente creando un caos como muchas comunidades que siguen estos pensamientos terminan haciendo.

Si todos ahora tomamos la obligacion de aprender Chino or Mandarin, o cualquier otro lenguage que quieres que otros aprendan simplemente porque todos deberian de escribir en su language materna, pues llegaremos a un punto donde todos se vuelve exclusivo y simplemente conversan con personas de su lenguage.

Un ejemplo de esta situacion es canal de Discord llamado Vue Land donde la mayoria de las veces asiaticos prefieren simplemente hablar entre ellos o espanoles simplemente porque es mas facil para ellos.

A consecuencias de esto, la mayoria de las veces nadie puede ayudar a esas personas que no habla en ingles, consequentemente volviendose exclusiva la comunidad y dejando a esas personas a la berida o en caso de Vue que usado en Asia muuucho mas que otro lugar, nosotros estamos a la berida.

Ahora, muchos de los que hablan espanol leeran esto y se daran cuenta que existen errores ortograficos, errores que existen que solo los hablantes espanoles podra identificar, errores que potentialmente personas que personas que no hablan Espanol no podran indentificar. Errores que estan ahi porque llevo 5 anos sin escribir espanol u otros porque simplemente podrias ser una persona hablante espanol que no sabe escribir algunas palabras porque no somos perfecto.

Si todos cometemos errores escribiendo Ingles, incluso aquellos que aun estan aprendiendo ingles podras identificar si ellos ya cometieron ese error en el pasado, porque por lo menos todos estamos intentando hablar el mismo lenguage asi que todos nos apoyamos unos a los otros.

Si el objectivo de cualquier persona en estos comentarios es ser mas inclusivo, simplemente apoyan a los que no saben hablar ingles e intenten compreder que cuando ellos cometen errores otrograficos posiblemente es porque no saben hablar ingles, asi que los hablantes de ingles nativo tienes una responsabilidad de tener paciencia y ensenar a otros, y nosotros como personas que no hablamos Ingles nativamente tenes la responsabildiad de intentar hablar un mismo lenguage por el bien de nuestra communidad de ingenieros.

Si crees que @dandv esta siendo rudo, mas rudo es que tu empiesas a conversar con una persona en un lenguage que ni idea tengo cual es excluyendo a todos los que no saben hablar en lenguage, eso es aun mas rudo, porque todos sabemos que los contribuidores hablan ingles o que ciencias de la computacion y en projectos de codigo abierto se habla ingles.

Si quieres hablar de exclusividad, ves a cualquier project en Chino y veras que te ignoraran simplemente porque decides usar el lenguage universal con se trata de ciencias de la computacion, eso es ser exclusivo.

Porque de la misma forma que tu decides hablar en su lenguage, es de la misma forma esa persona pueden intentar hablar en ingles.

Y de nuevo, nuestra responsabilidad es apoyarlos.

Me parece que es un poco injusto que @dandv como una de las personas que mantiente la herramienta tenga que hablar todos los lenguages simplemente porque ustedes quieren imponer sus creencias (en 2019 porque esto no hubiese sido un problema par de anos atras)

Dicho esto, si queremos mantener multiple traducciones de la documentacion oficial o del website es algo que todos podemos apoyar, pero GitHub Issues, GitHub Pull Requests no son el lugar donde deberiamos de simplemente ignorar la regla de intentar hablar un lenguaje comun.

@dandv I am sorry I wrote it in Englis, I am sorry I misspelled some words so have fun with the translator even when probably Google Translate will do a good, for the most part, I didn't include a sentence that could be potentially outraged sentence after translation from Google, hopefully, welcome to translation life.

And to be clear as Hispanic, I do support @dandv, we should all speak a common language.

**Comment by dandv** [comment]
@yordis, thank you for the support. It's refreshing after everyone in [the locked issue](https://github.com/parcel-bundler/website/issues/94) freaked out.

Thank you for the examples.

What I liked most about your post was this (automated translations):

> If we all speak our native language in communication increases friction eventually creating chaos like many communities that follow these thoughts end up doing.

I also agree with this:

> A consequence of this, most of the time no one can help those people who does not speak English, consequently BECOMING an exclusive community

I've seen this myself in forums that have an "English" section, then a section in the language of the author of the software. What happens is that the community gets split, and nobody helps people in the other half. Also, answers in one language aren't searchable in the other, so knowledge is lost, and the same question gets asked in both languages, wasting everyone's time.

Making an effort to write in English helps everyone,

1. With accessing the information/documentation/help itself, which becomes accessible to all who understand English (and English is the most popular language in open source projects, as you pointed out, and as I showed [here](https://github.com/coreinfrastructure/best-practices-badge/issues/230#issuecomment-412376730))
2. With learning English. Practice, practice, practice.

**Comment by devongovett** [comment]
@dandv "What makes you think we read Chinese?" is not a very nice thing to say. Please be inclusive and welcoming to everyone on the issue tracker. This is a requirement of our [Code of Conduct](https://github.com/parcel-bundler/parcel/blob/master/CODE_OF_CONDUCT.md).

We've also been over this before on another issue: knowing english is not a requirement for using Parcel or engaging with our community. No one is arguing that learning english can help, but it is a nice to have, not a requirement. Others in the community can help translate, along with automated machine translation. While this issue was short on detail, it was not because it was written in Chinese, but because it was actually short on detail. Please stop commenting on issues related to this or you will be blocked.

**Comment by Hammster** [comment]
@dandv @yordis IMHO you just proved my statement, we can read understand and even comment about texts in foreign languages with ease, while it is close to impossible to write in a language you don't know while beeing sure it is correctly translated.

This is a result where i translated German to English:

> At our meeting today, our package project could not load my preprocessor style files. I tried to delete the stored or generated data. Also from the browser pages. But do not curse that. I also tried updating the dependency lock file, but it got stuck.

To be honest, some things are correct but i have no idea why it turned parcel into package. Also funny it the `But do not curse that.` and `but it got stuck`. To get to the core issues, you can't be sure that what the translator gives you is correct, and english is not a language that is well taught in a lot of countries. Especially China, Russia, Korea and Japan are on that list of countries and they do account for way more people on the globe that the English speaker. I mean the most spoken language is Mandarin and not English.

While i do agree that the main communication language on the web, and not only in Informatics is English. I disagree very hardly with the exclusion argument, i do also write in german on the german vue-land discord channel. But we talk about country specific events, companies or give help to youngsters that still lack the necessary skills for a complex discussion in a foreign language.

@dandv your comment on the linked issue and also your blog in general. Is pretty much just extremistic opinions that you try to litter down on everyone. They are neither helpful nor useful to the community. You exclude a lot of people and just want to force people upon a specific language just because you think it is the golden hammer to all solutions. 

Also @yordis if you think this is such a urgent matter to pull a close to dead issue from 2 month rest, open another issue to address your concerns on-topic.

@devongovett @DeMoorJasper i think this issue will not be processed any further besides off-topic talk.

Vote for close.

**Comment by yordis** [comment]
@Hammster Espanol por favor, estas siendo exclusivo hablando en Ingles, eres un poco rudo, decides comunicarte con @jeasoncc en Chino pero decides ignorar el hecho de que hablo espanol y prefiero comunicarme en Espanol.

Todos podemos jugar a este juego que a nadie ayuda.

@devongovett talvez el esta siendo un poco directo y rudo, pero de la misma forma que decides que siendo directo y honesto es rudo y exclusivo, the la misma forma que @Hammster prefiere ignorar el hecho de hablar en Espanol, aun cuando decide hablar en Chino.

No ves el problema? Porque en mi perscepcion personal, el que deberias de bloquear es a @Hammster  que esta siendo exclusivo con la habla hispana, si decidimos jugar a este juego.

**Comment by devongovett** [comment]
Closing due to lack of information on this ticket, and locking the discussion because it is off topic. @jeasoncc if you would like to provide more information about your issue, please open a new ticket for further discussion.
