### ISSUE TITLE
Parcel does not keep file extension when creating source maps

### ISSUE THREAD

**Issue by RPDeshaies** [parcel-bundler/parcel#2460]
# 🐛 bug report

When using the following command, the source maps generated by parcel doesn't keep the file extension which makes debugging impossible using VSCode.

`parcel build src/index.ts --target node`

Parcel generates two file `index.js` and `index.map`

The reason why I know this is indeed the problem with my debugger is because if I rename `index.map > index.js.map` and change the last line of `index.js` to `//# sourceMappingURL=/index.js,map`, then the debugger works like a charm

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// ts config
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "lib": ["es2015"],
    "jsx": "react",
    "sourceMap": true
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["**/*.test.ts", "**/*.test.tsx"]
}

// vscode launch.json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run-script", "debug"],
      "port": 9229,
      "sourceMaps": true,
      "outFiles": ["${workspaceFolder}/bin/**/*.js"]
    }
  ]
}

```

## 🤔 Expected Behavior

I should be able to use my launch config from VScode to be able to debug my NodeJS typescript program

## 😯 Current Behavior

VSCode is not able to connect to the typescript files break points because it probably uses a pattern to match only js file extension even for the source map.

## 💁 Possible Solution

Add a cli option to keep file extension when building source maps OR always include them since I don't see why they were removed in the first place 

## 🔦 Context

I'm building a project with apollo server + typescript + serverless with Parcel to have a blasing fast bundler and minimum payload

## 💻 Code Sample

n/a

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.11.0
| Node             | 8.11.2
| npm/Yarn         | 6.5.0 (npm)
| Operating System | Mac OS high sierra

**Comment by DeMoorJasper** [comment]
@RPDeshaies I haven't updated that code in a lil while as it has been pretty stable, so not sure who changed that but as far as I can tell it's probably with the addition of Vue and the Pipeline.

However if this is causing issues we should probably resolve this, hopefully it's a pretty minimal change so we can still do this in Parcel 1. Otherwise we'll have to keep this in mind for Parcel 2 when we implement sourcemaps there.

Gonna have to have a better look once I get some more time again.

Happy holidays 🎄

**Comment by RPDeshaies** [comment]
So is it considered an "expected behavior" ? or could we consider adding an option to support the two use cases ?

**Comment by DeMoorJasper** [comment]
@RPDeshaies if it’s causing issues as you said we should probably fix this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kirillrogovoy** [comment]
I've googled about the preferable format of source maps and found out that:
1. You can name your source map files any way you want as long as `sourceMappingURL` references the right file.
2. Naming the source map files as `source_file_name + '.map'` is the recommended convention.

Spec: https://sourcemaps.info/spec.html

It seems to me that VSCode relies on this convention too much, since debugging works just fine in browsers.

On the other hand, Parcel doesn't follow this convention, which is not critical but can be improved.

As far as I understand, #1148 didn't break anything on its own: it doesn't decide on the name of the source map file but instead just uses one that's already had been decided.

Which means we should probably find the code that chooses the name of the source map file in the first place.

Going to look it up...

**Comment by DeMoorJasper** [comment]
@kirillrogovoy like I said in the pr and comment it had to do with the new naming strategy. The PR was indeed just a bugfix. So perhaps you can look at the filenaming PR as it’s probably in there somewhere.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kirillrogovoy** [comment]
Guess you're referring to #1025. Will look into that.
