### ISSUE TITLE
Autoinstalling react: Unexpected token

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2519]
# 🐛 bug report

Autoinstalling react doesn't work in a "completely clean" project.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babelrc, no package.json

## 🤔 Expected Behavior

Parcel should install react, react-dom and then bundle.

## 😯 Current Behavior

Parcel doesn't recognize the JSX syntax?
```
🚨  ...../index.js:5:1: Unexpected token (5:1)
  3 |
  4 | const MyComponent = () => (
> 5 | 	<button>Hello</button>
    | ^
  6 | );
  7 |
  8 | ReactDOM.render(<MyComponent />, document.getElementById("root"));
```

## 💁 Possible Solution

Workaround: install `react` as a dependency. Running `parcel index.html` will then corretly install `react-dom`and build successfully.

## 💻 Code Sample

index.js
```jsx
import React from "react";
import ReactDOM from "react-dom";

const MyComponent = () => (
	<button>Hello</button>
);

ReactDOM.render(<MyComponent />, document.getElementById("root"));
```
Command:
```js
parcel index.js
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |38df513
| Node             |11.6.0
| npm/Yarn         |
| Operating System |macOS 10.13.6

**Comment by lustoykov** [comment]
I think if it was `index.jsx` as opposed to `index.js` it should work. Having that in mind - looks ok to me?

**Comment by lustoykov** [comment]
For the protocol, using a normal `.js` extension, without JSX syntax, works fine too.

```js
import React from 'react';
import ReactDOM from 'react-dom';

const MyComponent = () => (
  React.createElement('div', null, 'Hello')
);

ReactDOM.render(
  React.createElement(MyComponent, null, null), 
  document.getElementById('root')
);
```

**Comment by lustoykov** [comment]
I think babel is not even able to generate `AST` currently, because the condition to add `@babel/plugin-transform-react-jsx` fails.

https://github.com/parcel-bundler/parcel/blob/6566e160affa161daa6d5486139e6059f685ba3a/packages/core/parcel-bundler/src/transforms/babel/jsx.js#L40

So one possible (but pretty ugly) solution would be to add additional check if the contents of the asset include `from react/preact/etc` or `require('react/preact/etc)` to the condition above.

This would enable `jsx` compilation. If I interpret correctly, as a result babel would be able to generate `AST`, collect depdendncies and set the correct pragma.

Do you see some better options?

**Comment by mischnic** [comment]
> Do you see some better options?

Always using @babel/plugin-syntax-jsx ?

**Comment by lustoykov** [comment]
@DeMoorJasper, 

> Dependencies have been collected before transform runs

my bad, that's correct, however parcel fails on `pretransform` due to missing plugin, not on `transform`. Since `collectDependencies` is a visitor, it relies on `AST` being generated (but babel ast generation fails).

---

Here is what I see - an asset starts with `process()`

https://github.com/parcel-bundler/parcel/blob/6566e160affa161daa6d5486139e6059f685ba3a/packages/core/parcel-bundler/src/Asset.js#L191

There we can see in order

```js
// See (*). Fails there due to babel transform with missing plugin
await this.pretransform(); 
await this.getDependencies(); // Only then parcel collects dependencies
await this.transform();
```

`pretransform() // fails due to missing plugin` 👇 (*) 
https://github.com/parcel-bundler/parcel/blob/6566e160affa161daa6d5486139e6059f685ba3a/packages/core/parcel-bundler/src/assets/JSAsset.js#L156

**Comment by DeMoorJasper** [comment]
@lustoykov you're right forgot for a second Babel can't create an ast with jsx by default.

Than I'm not sure how to fix this, besides from catching errors and retrying after the install finished which parcel should kinda already though.
Perhaps it doesn't reload the `package.json`

**Comment by mischnic** [comment]
The PR added autoinstall (that part works), but on the invocation where react is installed, several similar errors are printed (console and server):
```
🚨  /Users/niklas/.../react/Users/niklas/.../react/node_modules/react/index.js: ENOENT: no such file or directory, open '/Users/niklas/.../react/Users/niklas/.../react/node_modules/react/index.js'
Error: ENOENT: no such file or directory, open '/Users/niklas/.../react/Users/niklas/.../react/node_modules/react/index.js'
```
The path is somehow duplicated.
