### ISSUE TITLE
Import * as m not working

### ISSUE THREAD

**Issue by FrontMage** [parcel-bundler/parcel#2525]
# 🐛 bug report

I'm using parcel bundler with mithril.js and typescript. With `import * as m from 'mithril'` it will complain that `m is not a function`. But with `import m from 'mithril'` it works.

But with `import m from 'mithril'` the typescript checker would complain about `mithril has no default export`.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "dependencies": {
    "@types/echarts": "4.1.1",
    "@types/es6-promise": "^3.3.0",
    "@types/express": "^4.16.0",
    "@types/express-session": "^1.15.11",
    "@types/materialize-css": "^1.0.6",
    "@types/mithril": "^1.1.14",
    "@types/mithril-global": "^1.1.1",
    "@types/node": "^10.12.0",
    "@types/paper": "^0.11.1",
    "acorn": "^5.7.3",
    "browser-sync": "^2.24.7",
    "bunyan": "^1.8.12",
    "chalk": "^2.4.1",
    "d3": "^5.7.0",
    "echarts": "^4.1.0",
    "flyd": "^0.2.8",
    "github-markdown-css": "^2.10.0",
    "jieba-js": "^1.0.2",
    "materialize-css": "^1.0.0-rc.2",
    "mithril": "^1.1.6",
    "ngraph.centrality": "^0.3.0",
    "ngraph.graph": "^0.0.14",
    "ngraph.pagerank": "^0.1.4",
    "parcel-plugin-handlebars": "^0.4.4",
    "spectre.css": "^0.5.3"
  },
  "devDependencies": {
    "cssnano": "^4.1.8",
    "sass": "^1.15.2",
    "typescript": "^3.2.2"
  }
}
```

## 🤔 Expected Behavior

Expect to work with `import * as m`.

## 😯 Current Behavior

Not working.

## 💁 Possible Solution

Maybe has something to do with typescript module resolve.

## 💻 Code Sample

Can't do that

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.11.0
| Node             |v11.6.0
| npm/Yarn         |6.5.0
| Operating System | Arch linux 4.19

**Comment by lustoykov** [comment]
I think it works as expected, namely that 

```js
import m from 'mithril'
````

is the correct syntax since the module has only a single default CommonJS export 

```js
if (typeof module !== "undefined") module["exports"] = m
```

and parcel uses [--esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) flag which means that `m` from the `import` would equal this one default export.

I don't know what typechecker you use, but since `--esModuleInterop` is not the default option, the typechecker thinks it's not enabled and complains about having no default export. I guess you'd have configure the typechecker with `--esModuleInterop: true`

**Comment by FrontMage** [comment]
@lustoykov vscode + typescript language server works, but ncm2 does not.
Thanks a lot
