### ISSUE TITLE
[RFC] Parcel 2: AssetGraph and BundleGraph APIs

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2535]
This issue is to discuss what we want to expose to plugins on the AssetGraph and BundleGraph interfaces. This is just to get the conversation started - I don't have a concrete proposal just yet.

## The problem

Currently, both `AssetGraph` and `BundleGraph` are subclasses of `Graph`. `AssetGraph` in particular is also used for several different purposes: building an asset graph in core, passed to `Bundler` plugins, and stored as part of `Bundle` objects. Given this, the current API is a hodgepodge of different methods for various purposes, all on one object and accessible to anyone. While un-typed, plugins can technically reach in and access the data structure for the nodes and edges directly, and call "private" methods meant for use in core. This could create problems down the road if we ever want to change those things. We need to consider what we expose carefully in order to allow flexibility for plugin authors, but while not creating maintenance problems for ourselves.

## API design principles

The following are some principles of API design that I think we should adhere to. I'm open to discussion and additions of course.

* Expose an API, not the underlying data structures which may easily change.
* Design multiple contextual APIs rather than trying to support all features in one.
* Simplicity for the user is more important than simplicity of implementation (but there's a limit).
* Flexibility is important to allow plugins to do things we haven't thought of. We don't want to expose too little.
* At the same time, we don't want to expose too much and make our lives more difficult down the road to maintain.

## Node types

One distinction between the main asset graph and asset graphs within bundles is the node types that are allowed/needed. One possibility is to remove nodes that are not useful in a particular context so that the graph is easier to process, for example transformer requests and file nodes aren't useful in bundles. Currently used node types are listed below.

### Main asset graph

* `dependency`
* `transformer_request`
* `asset`
* `file`

### Asset graph within a bundle

* `dependency`
* `asset`
* `asset_reference`
* `bundle_group`
* `bundle`

## Current interfaces exposed to plugins

Below are the current interfaces exposed to plugins. As you can see, there is currently a strange mix of methods which have been added in order to implement the builtin plugins (e.g. default bundler, namer, runtime, etc.). The current API is probably too limiting for general usage, and perhaps has things that are too specific to the current implementation of the builtin plugins. Perhaps we can come up with some more general methods which could be used to implement some of the ones we have now, and then decide which more specific ones to keep in core.

```typescript
export interface TraversalContext {
  skipChildren(): void;
  stop(): void;
}

export type GraphTraversalCallback<T> = (
  node: T,
  context?: any,
  traversal: TraversalContext
) => any;

// Graph methods currently used by plugins (with $FlowFixMe)
export interface Graph {
  hasNode(id: string): boolean;
  traverse(visit: GraphTraversalCallback<Node>, startNode: ?Node): any;
  traverseAncestors(startNode: Node, visit: GraphTraversalCallback<Node>): any;
  merge(graph: Graph): void;
  getSubGraph(node: Node): Graph;
  getNodesConnectedFrom(node: Node): Array<Node>;
}

// AssetGraph methods used in plugins (bundler, namer, runtime, packager)
export interface AssetGraph extends Graph {
  traverseAssets(visit: GraphTraversalCallback<Asset>): any;
  createBundle(asset: Asset): Bundle;
  getTotalSize(asset?: Asset): number;
  getEntryAssets(): Array<Asset>;
  removeAsset(asset: Asset): void;
  getDependencies(asset: Asset): Array<Dependency>;
  getDependencyResolution(dependency: Dependency): ?Asset;

  // not currently implemented - uses the transformer runner to produce an asset graph
  // from the transformer request, and merges it into this asset graph. Needed for runtime plugins.
  addRuntimeAsset(node: Node, req: TransformerRequest): void;
}

export interface BundleGraph extends Graph {
  addBundleGroup(parentBundle: ?Bundle, bundleGroup: BundleGroup): void;
  addBundle(bundleGroup: BundleGroup, bundle: Bundle): void;
  isAssetInAncestorBundle(bundle: Bundle, asset: Asset): boolean;
  findBundlesWithAsset(asset: Asset): Array<Bundle>;
  getBundles(bundleGroup: BundleGroup): Array<Bundle>;
  getBundleGroups(bundle: Bundle): Array<BundleGroup>;
  traverseBundles(visit: GraphTraversalCallback<Bundle>): any;
}
```

## Interface used by core

Parcel core uses some additional methods on `AssetGraph` and `Graph` to build the main asset graph and other operations. I'm not going to list them all here, but I think we should consider splitting them out into a separate object that isn't exposed to plugins. That way we can change things internally as needed without breaking third party code or needing to bump a major version.

In addition, it is questionable whether the underlying `Graph` data structure and methods should be exposed to plugins. I think the data structure definitely shouldn't since we may need to change it out under the hood, but even the more generic graph methods are questionable. Most of them rely on a `Node` data structure which is an `{id, type, value}` object, and an `Edge` which has `{from, to}`. I wonder if we want to expose those or if we can come up with methods specific to the data types contained in the graph.

## Summary of Questions

* Do we want to remove unused node types from bundle asset graphs so that they are only in the main asset graph?
* Should we separate the interfaces for the main asset graph and an asset graph within a bundle?
* Do we want to expose graph `Node` and `Edge` objects, or only their values? If only values, then how would you e.g. traverse a graph and handle objects of varying types?
* Do we want to expose the underlying `Graph` at all or only specific interfaces for each usecase?
* What should the actual interfaces look like?

I would love to hear what you think! Please leave comments and proposals below. 🙏

**Comment by devongovett** [comment]
* Remove unused node types prior to passing graph to bundler plugin. Therefore, bundle asset graphs will also not have any of those nodes.
* Create a proxy graph object which would be used by plugins instead of the graph directly. The main asset graph would only be used by parcel core.
* Definitely don't expose edges. The interface for traversing nodes is questionable.
* Don't expose the graph itself.

**Comment by wbinnssmith** [comment]
I've been thinking about this and exploring a number of different approaches in the past week.

In short, I think @devongovett's exploration in the `wip/graph-api` branch strikes a good balance between maintaining a bunch of use-case-oriented apis and having something far more open like we did before. I think we should expand having mutable and immutable flavors of our core structures throughout the api. 

**Most of these opinions are from observing how these structures are used in current v2 plugins. I'm probably making assumptions based on not having seen other things plugins can do, but I'm erring on the side of being conservative.** We should begin broadening things as use cases appear.

I think we should split up the interfaces for the asset graphs found in bundles and the interface for the main asset graph (which cannot have bundle nodes in it). The overlap in their actual usage is pretty limited:

```
interface AssetGraph {
  getDependencyResolution(dependency: Dependency): ?Asset;
  traverseAssets<TContext>(
    visit: GraphTraversalCallback<Asset, TContext>
  ): ?TContext;
}

// Always read-only.
interface MainAssetGraph extends AssetGraph {
  createBundle(asset: Asset): MutableBundle<BundleAssetGraph>;
  traverse<TContext>(
    visit: GraphTraversalCallback<
      DependencyNode | AssetNode, 
      TContext
    >
  ): ?TContext
}

interface BundleAssetGraph extends AssetGraph {
  getBundleGroups(): Array<BundleGroup>;
  getBundlesInGroup(BundleGroup): Array<Bundle>;
  getDependencies(asset: Asset): Array<Dependency>;
  getEntryAssets(): Array<Asset>;
  getTotalSize(?Asset): number;
}

interface MutableBundleAssetGraph extends BundleAssetGraph {
  addRuntimeAsset(
    BundleGroup,
    TransformationRequest
  ): Promise<void>;
  merge(AssetGraph): void;
  removeAsset(Asset): void;
}
```

Graph nodes are only exposed directly in one case: the main asset graph. So far only bundle plugins receive this, and they only use dependency and asset nodes, so I limited it to that. We should continue limiting things as much as possible here as these are an implementation detail of Parcel.

One of my concerns is that `addRuntimeAsset` feels really specific to runtime plugins, but `Bundles` are everywhere. Is there any other occasion we'd need this? Is it much of a risk allowing non-runtime plugins to inject runtimes? I explored some use-case oriented apis just for runtimes but it complicated things a lot.

Second, we'll likely need to create another proxy to Bundles, as having access to their inner Graph structure is necessary to implement other apis. These implementations would hold the inner "core" bundle (the one stored in the graph) and expose versions with the public `BundleAssetGraphs` on them. The public versions of a Bundle could look like this:

```
interface Bundle {
  +id: string;
  +type: string;
  +env: Environment;
  +isEntry: ?boolean;
  +target: ?Target;
  +filePath: ?FilePath;
  +stats: Stats,
  +assetGraph: BundleAssetGraph,
}

interface MutableBundle {
  filePath: ?FilePath;
  isEntry: ?boolean;
  +assetGraph: MutableBundleAssetGraph,
}
```

We could consider version of `Bundle` with mutable graphs and versions of `MutableBundle` with immutable graphs, as there are number of use cases for these, but that feels like it overcomplicates things.

We should probably split up `BundleGraph` into mutable/immutable versions, as bundler plugins need a mutable graph while things like reporters do not. The read-only `BundleGraph` could hand out read-only `Bundle`s too.

Namer plugins should get the completely sealed, public `Bundle`s since all they do is examine bundles and suggest names.

Runtimes would receive `MutableBundle`, since they add runtimes into its graph.

Packagers and optimizers would also receive a sealed `Bundle` since they just return a string of source text given a bundle.

**Comment by wbinnssmith** [comment]
Another thing we could do is just merge the `BundleAssetGraph`s onto the bundles themselves. This would cut the number of AssetGraph interfaces just down to the `MainAssetGraph`. This would make things simpler for the user, at the cost of duplicating some of the interface:

```js

// Always read-only.
interface MainAssetGraph extends AssetGraph {
  getDependencyResolution(dependency: Dependency): ?Asset;
  traverseAssets<TContext>(
    visit: GraphTraversalCallback<Asset, TContext>
  ): ?TContext;
  createBundle(asset: Asset): MutableBundle<BundleAssetGraph>;
  traverse<TContext>(
    visit: GraphTraversalCallback<
      DependencyNode | AssetNode, 
      TContext
    >
  ): ?TContext
}

interface Bundle {
  +id: string;
  +type: string;
  +env: Environment;
  +isEntry: ?boolean;
  +target: ?Target;
  +filePath: ?FilePath;
  +stats: Stats;
  getDependencyResolution(dependency: Dependency): ?Asset;
  traverseAssets<TContext>(
    visit: GraphTraversalCallback<Asset, TContext>
  ): ?TContext;
  getBundleGroups(): Array<BundleGroup>;
  getBundlesInGroup(BundleGroup): Array<Bundle>;
  getDependencies(asset: Asset): Array<Dependency>;
  getEntryAssets(): Array<Asset>;
  getTotalSize(?Asset): number;
}

interface MutableBundle {
  filePath: ?FilePath;
  isEntry: ?boolean;
  addRuntimeAsset(
    BundleGroup,
    TransformationRequest
  ): Promise<void>;
  merge(Bundle): void;
  removeAsset(Asset): void;
}
```

**Comment by devongovett** [comment]
As discussed, I think the second option of exposing APIs directly on the Bundle is the way we should pursue. In addition:

* All Parcel core types should be wrapped and only expose a public interface. This includes nodes (include type/value), assets/dependencies (only expose methods in transformers), bundles, etc.
* `addRuntimeAsset` needs to be re-thought.
* It's annoying that `filePath` on a bundle is optional once it is named. Not sure how to solve this other than making separate types.
