### ISSUE TITLE
Tree shaking fails for npm module `polished`

### ISSUE THREAD

**Issue by r0skar** [parcel-bundler/parcel#2646]
# 🐛 bug report

I have included a test repository to showcase code and config.

## 🎛 Configuration (.babelrc, package.json, cli command)

See test repo @ https://github.com/r0skar/polished-tree-shaking

## Reproduction

1. Clone the test repo @ https://github.com/r0skar/polished-tree-shaking
2. Run `yarn build`.
3. Compare parcel and webpack bundles in `/dist`.

## 🤔 Expected Behavior

Parcel should strip all unused modules from `polished` and be more or less the same size as the webpack bundle.

## 😯 Current Behavior

Parcel includes the whole `polished` bundle.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 11.9.0
| Yarn         | 1.13.0
| Operating System | Linux 4.20-7

**Comment by mischnic** [comment]
You need to enable minification for tree shaking to work. Without `--no-minify`, I get 12.34 KB with your example.

**Comment by r0skar** [comment]
You are right, the bundle size is drastically decreased when not using `--no-minify`, however if you look at the file, you will see that there is a lot of unused stuff still included. Also, the webpack version is about 10 times smaller at 1.8KB.

**Comment by garthenweb** [comment]
Is this maybe related to #2650? Not because of the environments but because of the dependencies that are loaded even if they are unused?

**Comment by mischnic** [comment]
This is caused by Parcel's (current) tradeoff for build speed instead of bundle size (as already discussed in #2310)

This can be fixed by making Parcel run terser on the final output bundle instead, actually yielding better results than webpack! :
```
1.3K parcel.modified.js
2.9K webpack.js
 16K parcel.current.js
```
You can try this yourself by using the experimental Proof-of-Concept `@mischnic/parcel-bundler` instead of the `parcel-bundler` package.

@devongovett, in that issue you said:
> There also wasn't a very big difference in output size that I saw, but perhaps you've run into something.

Here's an example
<br>

PS: Also, don't rely on the reported build size (normal or `--detailed-...`) by Parcel when using scope hoisting, it doesn't take tree shaking into account.
