### ISSUE TITLE
.babelrc is not picking up NODE_ENV?

### ISSUE THREAD

**Issue by tiborsaas** [parcel-bundler/parcel#2678]
# ❔ Question / Bug?

Should this `.babelrc` work? Parcel doesn't seem to pick up the plugin I've specified.

I simply run it as

`parcel ./index.html --open`

If I place the `plugins` key to the root of the JSON, then it starts working, but I want to avoid it because for Jest I don't want that plugin to run.

Doc says it should work: https://new.babeljs.io/docs/en/next/babelrc.html

```json
{
    "env": {
        "production": {
            "plugins": [
                [
                    "@babel/plugin-transform-runtime",
                    {
                        "corejs": 2
                    }
                ]
            ]
        },
        "development": {
            "plugins": [
                [
                    "@babel/plugin-transform-runtime",
                    {
                        "corejs": 2
                    }
                ]
            ]
        },
        "test": {
            "plugins": [
            ]
        }
    },
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.5
| npm/Yarn         | 6.1.0
| Operating System | Win10

**Comment by tiborsaas** [comment]
The problem was that I probably had conflicting babel packages installed, so I removed all babel reference from `package.json`, deleted node_modules and added support for only the latest browsers.

https://github.com/parcel-bundler/parcel/issues/1762

**Comment by dusty** [comment]
I ran into this issue as well and the plugins were not run in the specified environment.  In my case I had only one plugin and it was isolated to the production environment.  

Looks like the cause was found in PR #2840.  As soon as I added an additional plugin to run in all environments (outside of the env property) it started working.  As it appears that parcel is skipping running the plugins if no global plugins are defined or they are empty, but its not checking to see if there are plugins related to env.
