### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by subhero24** [parcel-bundler/parcel#2698]
# 🐛 bug report

When running parcel on this code:

```javascript
import x from './x';

export default function(x) {}
```

It errors with 'Duplicate declaration "x"'

I think this is valid code however, as node has no problem executing the file (with esm)

**Comment by mischnic** [comment]
Wow, actually caused by Babel: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBADzgMyhEcDkA6A9AzAbgChiBTBSWOAEzOQEMBXAG3mSYDsBjGYCTgAoEASjgBvAL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=Node-6&version=7.3.4

 > I think this is valid code however, as node has no problem executing the file (with esm)

Works with Rollup as well.

**Comment by subhero24** [comment]
Oh, didn't think of testing it with babel directly. Thank for verifying. Will submit the bug in the babel repo.

**Comment by mischnic** [comment]
> Oh, didn't think of testing it with babel directly. Thank for verifying. Will submit the bug in the babel repo.

PS: 3rd bug in the @babel/traverse/scope code I've found in recent time. All of them still not fixed...
