### ISSUE TITLE
@ on import for root path

### ISSUE THREAD

**Issue by ManzDev** [parcel-bundler/parcel#2776]
In webpack using `@` for root src folder:

```
import Home from '@/components/Home';
```

When try use '@', Parcel try install "@/..." package with npm. I use Windows.
I want some similar in parcel for avoid things such as "../../../" or similar, depends component path. Options?

- [Root path import](https://github.com/parcel-bundler/parcel/issues/1975) not clear my question
- [Tilde resolutions](https://en.parceljs.org/module_resolution.html#~-tilde-paths) don't works for me
- [Aliases](https://en.parceljs.org/module_resolution.html#aliases) don't works neither

Recommends?

**Comment by DeMoorJasper** [comment]
Parcel supports `/` and `~/` they are documented in the docs. They have pretty similar results. (I think `~/` will be removed in parcel 2 though)

we dont and will not support `@/` afaik because parcel 1 has been feature locked and because it’s non standardised. You’ll be able to write your own resolver for parcel 2 if there is a need for `@/`

Try / and see if it works

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManzDev** [comment]
@DeMoorJasper correct!

Fast summary, for users for this issue:

| Import path method | Comments | Parcel support |
|------------------------|-------------|-----------------|
| `import Component from '@/components/Home'` | non standard | no |
| `import Component from '~/components/Home'` |  | yes, maybe removed in Parcel 2 |
| `import Component from '/components/Home'` |  | **yes** |

Thanks!
