### ISSUE TITLE
Resolve node_modules from html tags

### ISSUE THREAD

**Issue by nevir** [parcel-bundler/parcel#2808]
# 🙋 feature request

I think it'd be pretty helpful to support resolution of scripts/css/etc from HTML sources, following node's resolution rules.

---

For example, with https://github.com/necolas/normalize.css as a node dependency

`index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="normalize.css">
</html>
```

I'd expect:

```html
<link rel="stylesheet" href="normalize.css">
```

to be equivalent to 

```html
<link rel="stylesheet" href="./node_modules/normalize.css/normalize.css">
```

(This also implies support for the `style` key in package.json to figure out which file to resolve in a `link rel="stylesheet"` context)

**Comment by mischnic** [comment]
> `<link rel="stylesheet" href="normalize.css">`

These links in browsers are resolved as relative urls. There is no way for Parcel to distinguish relative imports of local files (other than forcing the use of `./`) or packages.

The only syntax Parcel resolves specially is this (`~` will always be the folder with `node_modules`, might be useful if you have html files in subfolders):
`<link rel="stylesheet" href="~/node_modules/normalize.css/normalize.css">`

> This also implies support for the style key in package.json

-> https://github.com/parcel-bundler/parcel/issues/432

**Comment by nevir** [comment]
Ah! Hmm, I wonder if introducing something like a uri scheme might satisfy? (or is just getting too fancy)

```html
<link rel="stylesheet" href="npm:normalize.css">
```

**Comment by ric2b** [comment]
> The only syntax Parcel resolves specially is this (`~` will always be the folder with `node_modules`, might be useful if you have html files in subfolders):
> `<link rel="stylesheet" href="~/node_modules/normalize.css/normalize.css">`

This isn't working for me, if I have an entry point in a `src` directory (`parcel build src/index.html`), `~` refers to the `src` directory, not the parent that also contains `node_modules`.

**Comment by mischnic** [comment]
@ric2b Actually, that's "per spec": https://parceljs.org/module_resolution.html

> `~/foo` resolves `foo` relative to the nearest **package root** or, if not found, the **entry root**.

> **entry root**: the directory of the entrypoint specified to Parcel, or the shared root (common parent directory) when multiple entrypoints are specified.

In your case, the entry root is `src` (Parcel never searches "above" the entry root). Though I'm not sure why it does that.
@devongovett ?

**Comment by bbenne10** [comment]
I have managed to resolve this issue by specifying `~/../node_modules/normalize.css/normalize.css` rather than `~/node_modules/normalize.css/normalize.css`. I suspect that this is biting those of us with `src/` subdirectories in our projects more than others. I fully support a specific manner in which we can address the nearest `node_modules` subdirectory directly, but am unsure how one would implement such a scheme. For now, walking a directory upin my `<link />` isn't any trouble.

**Comment by devongovett** [comment]
For Parcel 2, we are considering supporting an `npm:` URL protocol to resolve node_modules instead of as a relative path. For example:

```html
<link rel="stylesheet" href="npm:normalize.css">
```

Without the `npm:`, it would resolve the same as `./normalize.css`, since it is a URL.

See https://github.com/parcel-bundler/parcel/issues/3492#issuecomment-529120998 for more details.

**Comment by mischnic** [comment]
Please follow #3492 for updates
