### ISSUE TITLE
Bundle into single big minified js file?

### ISSUE THREAD

**Issue by AAverin** [parcel-bundler/parcel#2868]
# ❔ Question

Is it possible to minify to a single js file? Also, ignore some folders?

## 🔦 Context

I would like to better obfuscate my code.
At the moment I have many js files, some of which are libraries that don't need minification/obfuscation.

After building with parcel I get many minified js files.
I would like to have a single big js file that has all my other js code inside

Could be related to #1370

**Comment by mischnic** [comment]
> I would like to better obfuscate my code.
At the moment I have many js files, some of which are libraries that don't need minification/obfuscation.

I don't quite understand what's the issue here. Do you want to exclude some libraries from minification?

> After building with parcel I get many minified js files.
I would like to have a single big js file that has all my other js code inside

When possible, only one JS file should be generated.
Reasons for multiple JS files: 
- you have multiple JS entrypoints (e.g. have specified multiple `<script>`s in your entry html file)
- use dynamic imports
- you use Workers

**Comment by AAverin** [comment]
@mischnic I already figured that due to the nature of my project it's not possible to have a single big js file.
How can I exclude some folders from being processed by parcel? Also, some asset types too

**Comment by mischnic** [comment]
> How can I exclude some folders from being processed by parcel? Also, some asset types too

You'd need to be more specific. But generally: no.

**Comment by AAverin** [comment]
Specific example: I could have libraries added as <script> in my index.html that are already minified and don't need to be re-parceled.
Additionally, what if I only need to parcel js files, but would like to keep my css and svg intact?

**Comment by mischnic** [comment]
> I could have libraries added as <script> in my index.html that are already minified and don't need to be re-parceled.

> Additionally, what if I only need to parcel js files, but would like to keep my css and svg intact?

Both cases are currently not possible, and the first is particularly unusual.
