### ISSUE TITLE
Feature: Go Support (golang)

### ISSUE THREAD

**Issue by tracker1** [parcel-bundler/parcel#2903]
# 🙋 feature request

Similar to Rust support, it would be nice/interesting to see Go (golang) support.

## 🤔 Expected Behavior

import { foo } from 'file.go'

## 😯 Current Behavior

Currently unsupported

## 💁 Possible Solution

I'm not familiar enough with internals to know where to start, should build using Go model, but the injection points should be similar to Rusts's wasm file usage.

## 🔦 Context

It's not something that is directly impacting me currently.  Given the communication models in Go, it may be a great fit. 

## 💻 Examples

N/A

**Comment by lucacasonato** [comment]
I have actually tried to implement this before, but failed at importing the WASM modules as they are laid out differently than Rust (rather than exporting functions, it sets variables on the global object). Go also needs a JS loader file which is not currently supported afaik.

The building is actually way easier to implement than Rust. If I should make a PR to implement building the WASM modules, please let me know.

**Comment by graingert** [comment]
looks like that ticket got closed, see https://github.com/golang/go/issues/25612

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
