### ISSUE TITLE
Aliases in Bundler API?

### ISSUE THREAD

**Issue by Kelin2025** [parcel-bundler/parcel#3080]
# ❔ Question

It seems that Bundler does not have `alias` option, so we can only take aliases from `package.json`

## 🔦 Context

The problem is that I use 2 instances of Parcel for building Electron main and renderer processes and they need different aliases.

I was also looking for using babel plugin for aliases but as I understand from #2902 we can't set babel config in bundler options

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.3 |
| npm/Yarn         | 6.8.0 |
| Operating System | Windows |

**Comment by Kelin2025** [comment]
Also it seems that programmatic API does not use `.env` files too 😢

**Comment by skourismanolis** [comment]
any plans on supporting aliases on the API ?

**Comment by khang-hoang** [comment]
any update on this ?

**Comment by krutoo** [comment]
it is possible to use aliases in 2+ version of parcel?

**Comment by aheissenberger** [comment]
Is there any reason why alias are not supported by the api (parcel v2)?

**Comment by everdimension** [comment]
I have a similar need, I want to have a different bundle for component testing, and for this bundle I wish to mock some of the dependencies, e.g.:

```
"alias": {
  "webextension-polyfill": "./webextension-polyfill.mock.ts"
}
```

But for my "main" bundle I do not need this mock.

The problem is that even if I create a separate package.json (in a subfolder) with its own "alias" field, it seems to be ignored. I guess it's because parcel resolves the package.json file going up from the imported source file.

**Comment by devongovett** [comment]
This is possible via a custom Resolver plugin in Parcel 2
