### ISSUE TITLE
Cannot set property 'fileName' of undefined

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#3132]
```Cannot set property 'fileName' of undefined```
Console logs:
```
Server running at http://localhost:37557 - configured port 1234 could not be used.
⠙ Building landing.html...addDependencyTo is deprecated in favor of
result.messages.dependency; posthtml-loader >= v1.0.1 will
automatically add your imported files to webpack's file watcher.
addDependencyTo is deprecated in favor of
result.messages.dependency; posthtml-loader >= v1.0.1 will
automatically add your imported files to webpack's file watcher.
🚨  /src/pages/landing.html: Cannot set property 'fileName' of undefined
    at Pipeline.process (/node_modules/parcel-bundler/src/Pipeline.js:30:22)
addDependencyTo is deprecated in favor of
result.messages.dependency; posthtml-loader >= v1.0.1 will
automatically add your imported files to webpack's file watcher.
addDependencyTo is deprecated in favor of
result.messages.dependency; posthtml-loader >= v1.0.1 will
automatically add your imported files to webpack's file watcher.
```
[1559749197535.zip](https://github.com/parcel-bundler/parcel/files/3257921/1559749197535.zip)

**Comment by w-biggs** [comment]
This is happening for me whenever there's _any_ error in the pipeline, such as a posthtml error; Parcel tries to report the error, but there's an error in the error reporting function itself.

https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/Pipeline.js#L30

This is making debugging issues a major pain; I'm having to manually add `console.error(err)` before the erroring line in order to get a sense of what the error _actually_ is.

**Comment by samuelgozi** [comment]
I have this issue too.
@w-biggs thanks for the tip, it helped me find out what the underlying issue is.

**Comment by namse** [comment]
In my case, I set wrong file name in index.html.

**Comment by FDiskas** [comment]
![giphy](https://user-images.githubusercontent.com/468006/77045907-c2c19c00-69ca-11ea-9940-358e5c145a89.gif)

**Comment by KilianKilmister** [comment]
also very much interested in this
