### ISSUE TITLE
Extended .parcelrcs should resolve plugins relative to the config that declares them

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#3210]
Currently, all Parcel 2 plugins are resolved relative to the most authoritative .parcelrc (either the user provided one or the default config). However, if a parcelrc extends another, the plugins referenced in any given config in the chain should be resolved relative to that config file.

**Comment by DeMoorJasper** [comment]
I've been working a lil on this issue and wasn't entirely sure how to fix it.
I thought it would be relatively easy and straightforward but seems like it's actually a pretty significant change.

I've tried one method which just crashed Parcel and that's resolving all packages when loading in the config. It crashed the resolver when loading in the bundler for some reason, didn't really debug it too much. Didn't really seem like a good wat to solve this thinking about it afterwards.

I've also tried another method where each plugin is stored as an object `{plugin, resolveFrom}` but the unfortunate thing about this is that it would require a lot of code changes. This seemed like the easiest and possibly best way to solve this to me.

Didn't wanna waste too much time on this due to the vaste amount of changes this would require so kinda just wanna have some feedback on how anyone else would tackle this and if you think the second approach seems like a good idea.

**Comment by devongovett** [comment]
I think there are two possibilities:

1. Don't actually merge the config objects, but instead store a chain of configs (e.g. `{config: ParcelConfig, extends: ParcelConfig[]`) and resolve the extending at lookup time.
2. Still merge the configs, but store each plugin as `{plugin, resolveFrom}` as you suggested.

Either way, there will be code changes. We might be able to mitigate it a bit by trying to expose the config to the public API the same way it is today, e.g. continue returning `Array<string>` from `getTransformerNames` etc. That way pretty much only `ParcelConfig.js` will be touched.
