### ISSUE TITLE
What's up parceljs?

### ISSUE THREAD

**Issue by idanilt** [parcel-bundler/parcel#3237]
# ❔ Question
What going on with this project?
- Releases aren't being released
- What, where and when the "V2" that we are seeing activity
- Why your pipeline is broken?
- Why it so hard to contribute to your project?
- Why you are not supporting es6 modules? es models are part of our world it's time to progress

**Comment by FDiskas** [comment]
And not closed issues looks very scary. :)

**Comment by DeMoorJasper** [comment]
Parcel isn't fully funded as a result most of the contributors don't work on Parcel full-time...

V2 is in full development and a first alpha will be released very soon.

The pipeline is broken because Elm is unstable. This is outside of Parcel's control.

How is it hard to contribute to Parcel? Parcel 1 is feature locked but feel free to open PRs for Parcel 2.

ESModules are gonna be supported in Parcel 2 at some point afaik.

Releases are still going through, just a bit slower than before due to our focus being at Parcel 2

**Comment by mischnic** [comment]
> ESModules are gonna be supported in Parcel 2 at some point afaik.

ES modules output are only possible with scope hoisting (not using the standard module wrapper). Scope hoisting will be the default in Parcel 2 (and not be marked "experimental" anymore).

**Comment by damianobarbati** [comment]
FYI @DeMoorJasper @devongovett this project is amazing, thanks so much for your efforts guys.

**Comment by devongovett** [comment]
We're moving full steam ahead on Parcel 2 at the moment, which is why releases for v1 have stopped. You can track our progress on the [v2](https://github.com/parcel-bundler/parcel/tree/v2) branch. Commits are going in quite frequently there. You can also check https://isparcel2readyyet.com to see the progress of passing tests for v2.

> Why you are not supporting es6 modules?

I think you mean outputting es6 modules? We already support reading them. Outputting will be in parcel 2 as others have stated.

Closing, because I think this has been answered.
