### ISSUE TITLE
How to keep filename hashing when use .js as entry point?

### ISSUE THREAD

**Issue by shvets2kirill** [parcel-bundler/parcel#3279]
# ❔ Question
How I can keep filename hashing when I use my JavaScript file as entry point? It works only when I use HTML file.

## 💻 Code Sample
In package.json:
```
"scripts": {
  "watch:main": "parcel watch sources/packs/main.js -d static/dist/main/"
}
```

In main.js:
```
import './main.scss'
```

In main.scss:
```
.class {
  background-image: url('../assets/images/some.png');
}
```

Expected output:
```
static/
  dist/
    main/
      some.[hash].png
      main.[hash].css
      main.[hash].js
```

But:
```
static/
  dist/
    main/
      some.[hash].png
      main.css
      main.js
```

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |10.16.0
| npm/Yarn         |npm 6.9.0
| Operating System |Mac OS

**Comment by mischnic** [comment]
Entrypoints don't get named with a hash because then it wouldn't be straightforward to reference them.

You can add one using a shell command: `mv index.js index.$(md5sum index.js | cut -c1-6).js`

Not sure why main.css doesn't have a hash though... @DeMoorJasper ?

**Comment by wbinnssmith** [comment]
> Entrypoints don't get named with a hash because then it wouldn't be straightforward to reference them.

Despite this inconvenience, there are still benefits to this, like serving these files with `Cache-Control: Immutable` or using a long `Max-Age` since the name guarantees the content of the file hasn't changed.

With webpack, tools like the HTML plugin can generate pages that include these names with digests. Also, in situations where another system is generating webpages (including at runtime like in Django or PHP), webpack (maybe through a plugin) can externalize a mapping of entry source to the complete bundle name, including the digest. These system can read that in and write the results into a script tag.

One thing we could explore in Parcel 2 that I've been thinking about is producing one of these maps through a reporter, or even using a file indexing these entries as a single entrypoint to Parcel. Here's a thought:

Given `app.parcelmanifest.json`:

```
{
  "src/a.js": null,
  "src/b.js": null
}
```

Running `parcel build app.parcelmanifest.json` could produce `dist/parcelmanifest.json`:

```
{
  "src/a.js": "a.0a87f76e.js",
  "src/b.js": "b.9e7236b.js"
}
```

This could all be done through the existing transformer infrastructure in Parcel 2 and avoid using a reporter or creating any new logic in core.

**Comment by mischnic** [comment]
> This could all be done through the existing transformer infrastructure in Parcel 2 and avoid using a reporter or creating any new logic in core.

Probably also with Parcel 1. WebManifest does something very similar: https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/assets/WebManifestAsset.js#L13-L19.

Anyway, closing this because in favour of a dedicated issue: #3307
