### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by crapthings** [parcel-bundler/parcel#3299]
i've setup an express server and its port is binding to 3000.

my parcel project is set out put dir into ../server/static.

> parcel src/index.html --out-dir ../server/static.

when i open localhost:1234 its working fine

but not localhost:3000

i got "Uncaught SyntaxError: Unexpected end of input" after hmr

there're two settings

HMR Hostname
HMR Port

should i set these two options?

**Comment by mischnic** [comment]
> Uncaught SyntaxError: Unexpected end of input

This usually happens when the reload happens too early (when only some part of the output files are written to disk).

If your server serves the static files like parcel would (at `/`), it should work just fine.
If you do some custom routing, you should set the `--public-url` option.
HMR Hostname and Port are only needed if your server is running on a different machine and/or the proxy server redirects between these ports.

**Comment by crapthings** [comment]
i've did set public-url like this

> "dev": "parcel ./src/index.html --out-dir ../server/static --public-url .",

> "dev": "parcel ./src/index.html --out-dir ../server/static --public-url /",

but i still got "Uncaught SyntaxError: Unexpected end of input"

**Comment by crapthings** [comment]
the "Uncaught SyntaxError: Unexpected end of input" goes after i add these to line with empty function body, why?

if (module.hot) {
  module.hot.dispose(function() {})
  module.hot.accept(function() {})
}

**Comment by mischnic** [comment]
> goes after i add these to line with empty function body, why

This essentially says: I handle HMR myself (in the callbacks you provide); in this case: do nothing.
