### ISSUE TITLE
.terserrc does not work in conjunction with `--experimental-scope-hoisting`

### ISSUE THREAD

**Issue by haywoood** [parcel-bundler/parcel#3322]
# 🐛 bug report

I have a .terserrc file in my project to keep license comments around
```Javascript
{
  "output": {
    "comments": "/license/"
  }
}
```

This works as intended when I don't have `--experimental-scope-hoisting` enabled. When it's enabled the comments are stripped. Monitoring the `outputCode` for each file during compilation, I can see the correct output but each file seems to go through multiple compilation steps, one of which removes the comments.

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command `node_modules/parcel/bin/cli.js build resources/web/docs_js/index.js -d out/ -o docs.js --no-source-maps --experimental-scope-hoisting`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12
| Node             | 10

**Comment by mischnic** [comment]
This is caused by these options for babel generate: https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/scope-hoisting/concat.js#L375-L380

Without scope hoisting, the `comments` option is left at the default:
https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/assets/JSAsset.js#L144-L149

**Comment by mischnic** [comment]
I doubt that it was intentional. The most common usecase is that terser strips all comments (and Parcel also emits some comments during scope hoisting -- this is likely the main reason for the comment stripping)

**Comment by haywoood** [comment]
Would a fix detecting and merging the `customConfig` be agreeable?
