### ISSUE TITLE
`require` resolves to wrong module

### ISSUE THREAD

**Issue by fongandrew** [parcel-bundler/parcel#3387]
# 🐛 bug report

When bundled with Parcel, a `firebaseui` require resolves to dialog-polyfill instead. This only happens with Parcel. I haven't been able to repro with Webpack or plain Node.

I haven't encountered this with any other modules yet and don't know what's special about those modules. I've filed an issue with`firebaseui` here (https://github.com/firebase/firebaseui-web/issues/618), but since I can't repro with Webpack, I suspect `firebaseui` exposes some edge case where Parcel is doing something it's not supposed to do.

## 🎛 Configuration (.babelrc, package.json, cli command)

Just import `firebase` and `firebaseui` and `require('firebaseui')`. See minimal repro below.

## 🤔 Expected Behavior

`require('firebaseui')` should return an object with an `auth` property. 

## 😯 Current Behavior

It returns an object that looks like the output of `require('dialog-polyfill')`.

## 💻 Code Sample

Minimal repro here: https://github.com/fongandrew/parcel-firebaseui

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.8.0 |
| npm/Yarn         | 6.2.0 |
| Operating System | Windows 10 |

**Comment by LuudJanssen** [comment]
A couple of things I found out about this:
- The issue seems to be caused by the file being imported (`dist/esm.js`) containing both `module["exports"] = dialogPolyfill` as well as `export { auth }`.
- A temporary workaround is to import `dist/npm.js` instead
  `import * as firebaseui from "firebaseui/dist/npm";`
  That's because this file only contains `module.exports` declarations in which the last declaration overrides the earlier `dialogPolyfill` export. 
- I don't know if this is Parcel's problem or Firebase UI's problem since FirebaseUI is publishing a file with two exports, but Parcel is not adhering to the order. A possible solution for Parcel could be that in case we are resolving the `module` file as defined in `package.json`, we should only watch for the `export` keyword. After all, it's explicitly stated as being an ES module.
I'll reference these findings in the Firebase UI repository.

**Comment by LuudJanssen** [comment]
Opened PR https://github.com/firebase/firebaseui-web/pull/623 to fix this issue.

**Comment by LuudJanssen** [comment]
FYI: My PR for FirebaseUI was just merged, so it should be fixed in the next release!

**Comment by dawogfather** [comment]
So this will be in firebaseui 4.3.0?
