### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [parcel-bundler/parcel#3473]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Comment by devongovett** [comment]
cc @xdamman @piamancini does OpenCollective support something like this?

**Comment by xdamman** [comment]
It would be up to the fiscal sponsor (in this case oscollective.org) to generate an ethereum (or bitcoin or whatever) address for your collective. /cc @alanna 

We don’t support this natively in the open collective platform (yet), but since we support manual donation methods, if the host is up for it, they could offer it (they would just have to manually confirm once the payment has been received, that’s what the hosts do today for wire transfers for example).

@lastmjs great to hear that you are working on something like that. You might want to check https://github.com/opencollective/BackYourStack as there might be synergies here.

**Comment by alanna** [comment]
Open Source Collective doesn't currently offer the service of receiving contributions in cryptocurrency. We would love to. We went pretty far down the track of trying to get it set up, but were ultimately stymied by AML/KYC regulatory requirements. We could take it up again, but in order to justify the time and expense I think we'd need to understand if crypto contributions were actually waiting to come in. 

I am aware of a couple other initiatives in this space for crypto contributions, like sustainus.io - maybe it would make more sense for us to partner with a service like that so they could handle the crypto side and we could handle the fiat side. When Collectives need to pay expenses they will probably need access to fiat, and just like we're not set up for crypto most crypto solutions aren't set up well for fiat, eg. dealing with the world of invoices, taxes, and bank accounts.

**Comment by oliviertassinari** [comment]
If you are interested in benchmarking with the other projects, you can explore some of the discussion in https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Alastmjs+funding .

**Comment by lastmjs** [comment]
@alanna I'm behind Sustainus, I'd love to discuss. The beauty of the model that Sustainus takes is that it is non-custodial, so everything happens on the client's machine, and Sustainus hold no funds for the user. This relieves Sustainus of money transmission laws and essentially all legal liability that I know of. Fiat on and off ramps are where the legal issues are, and yes dealing with invoicing and taxes and such become the sole responsibility of the user of Sustainus, so an organization dedicated to dealing with those issues might be very useful

**Comment by alanna** [comment]
@lastmjs - Great, let's talk! Sounds like we serve exactly complementary roles. We hold funds on behalf of projects and specifically take on the legal liability, and handle invoicing, taxes, etc. Can we continue on email to not derail this issue? Send me your thoughts: alanna@opencollective.com :)
