### ISSUE TITLE
When site.webmanifest file that is not in root directory, icons paths are incorrect

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#3588]
# 🐛 bug report

1. Take a look at [this project](https://github.com/mrcoles/test-parcel-webmanifest), which builds a simple html file + site.webmanifest with parcel@1.12.3
2. The manifest is at the path `static/site.webmanifest` ([code](https://github.com/mrcoles/test-parcel-webmanifest/blob/master/src/index.html#L4))
3. When it gets built, it references the file at `/static/site.webmanifest` ([code](https://github.com/mrcoles/test-parcel-webmanifest/blob/master/dist/index.html))
4. The "icons" within that file links to the image at `test-webmanifest.2044b095.png` ([code](https://github.com/mrcoles/test-parcel-webmanifest/blob/master/dist/static/site.webmanifest)) — which should be relative to the webmanifest inside `static/`
5. But the actual image is placed in the root of the `dist/` foldr ([dist directory](https://github.com/mrcoles/test-parcel-webmanifest/tree/master/dist))

## 🎛 Configuration (.babelrc, package.json, cli command)

See the above [repo](https://github.com/mrcoles/test-parcel-webmanifest).

## 🤔 Expected Behavior

I would expect the `test-webmanifest.2044b095.png` file to end up in the `static/` directory.

According to the examples ([Google Developers Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest), [MDN Web Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest)) for the manifest of a PWA, the "icons" file paths should include the paths to files.

Albeit, this is different from browser extensions manifests ([MDN extension manifest docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons))

## 😯 Current Behavior

I would expect the `test-webmanifest.2044b095.png` file is placed in the root of the `dist/` directory.

## 💁 Possible Solution

It seems like linked assets in a webmanifest file should be placed in the proper relative directory.

As a workaround, I just moved everything to the root directory of my static app.

## 💻 Code Sample

See the above [repo](https://github.com/mrcoles/test-parcel-webmanifest).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 12.9.0 |
| Yarn         | 1.6.0 |
| Operating System | OS X 10.14.6 |

**Comment by nevir** [comment]
Still an issue

**Comment by timreichen** [comment]
Ran into the same problem.

**Comment by bmeunier1974** [comment]
The issue is related to the wrong build method being use for the webmanifest. If you use 'parcel build' you get the un-minified manifest with path to the un-renamed image. If you use 'parcel' to build on the dev server you get the minified webmanifest with link to the renamed images on the root.,  I'm guessing there is a '!' missing somewhere.

**Comment by nettum** [comment]
I'm also getting a minified webmanifest in a subfolder with link to the renamed image on the root.
Should the site.webmanifest be copied to `dist/`-root (and hashed) on build instead of going into it's own subfolder?  

I have `index.html` at root and site.webmanifest + all other icons in a `static`-folder. 

![image](https://user-images.githubusercontent.com/798156/87942504-f86fb200-ca9c-11ea-831c-40f9fb1515db.png)

![image](https://user-images.githubusercontent.com/798156/87943153-e6424380-ca9d-11ea-8e48-b7a6675b2a55.png)

![image](https://user-images.githubusercontent.com/798156/87943005-b7c46880-ca9d-11ea-8423-1a04791c59e4.png)

![image](https://user-images.githubusercontent.com/798156/87943307-1ee21d00-ca9e-11ea-8ab7-ed7e39c7bbf0.png)

![image](https://user-images.githubusercontent.com/798156/87943615-92842a00-ca9e-11ea-80ff-4e68ea5d1d0c.png)

![image](https://user-images.githubusercontent.com/798156/87945235-c2343180-caa0-11ea-84a3-cee5810820f9.png)

**Comment by Rock-n-Roll-CRC** [comment]
Still an issue.
