### ISSUE TITLE
It's time to talk about 'parcel.config.js'

### ISSUE THREAD

**Issue by hyingreborn** [parcel-bundler/parcel#365]
webpack  100 lines
parcel       0 lines
I need       10 lines

Zero configuration is an impossible desire，people like simple ，but project need configurability

**Comment by shawwn** [comment]
It would be helpful to list a few scenarios that this config file should support. Maybe we can either make it unnecessary or at least do the absolute minimum configuration.

Note that we need to put a *lot* of thought into this. It's important not to just ship a half-baked solution for one or two cases. Whatever we do here will affect all parcel users, and a lot of people are starting to use parcel now.

**Comment by TheLarkInn** [comment]
I thought that kind of goes against the value proposition. Or is this more to approach this in a _really sensible way_. (BTW we are challenged in the same way with this at webpack). It all boils down to the maintainibility and "surprise" level of the API.

**Comment by yeskunall** [comment]
From the tagline:

>  Blazing fast, zero configuration web application bundler

... and I quite like that it's _zero configuration_. That's what caught my eye in the first place.

But like @shawwn said, this needs to be discussed in great lengths before we make a decision.

**Comment by rondonjon** [comment]
Stay strong, resist the temptation.

As I understand it, parcel was meant to be different. If that works out, it is a true benefit.

There are plenty of alternativew available for edge cases.

**Comment by DeMoorJasper** [comment]
In my opinion the only config we would need is a .parcelignore, this way we could also specify packages the parser can skip.
Which could contain the following:
```
node_modules/jQuery // Ignore this entirely
!node_modules/some_package // Parser can skip this and just bundle it as is
```

**Comment by devongovett** [comment]
I would like to avoid adding a parcel specific config. Once we add it, it's a slippery slope to end up like webpack. If there are specific configurations you need, please open issues for those and we will discuss them case by case, but usually configurations can be limited to ones that are specific to related tools like `.babelrc`, `.postcssrc`, etc.

**Comment by eavichay** [comment]
in the context of custom elements, babel requires a custom plugin `transform-class-properties` in order to work properly. But this breaks the source maps config. Can the source maps method be changed in parcel somehow? Switch from `inline-source-maps` to `eval` and vice versa?

**Comment by davidnagli** [comment]
@eavichay No, there's no way to configure source maps currently. Please open a new issue if the way source-maps work is causing any problems.

**Comment by Javiani** [comment]
I really tried to use Parcel, but that no configuration philosophy doesn't quite match reality.
The last plugin I tried to use was nunjucks plugin, but I coudn't configure it at all, like adding globals, filters, and that makes it quite useless if you can't extend it.

Documentation is also pretty poor...

I got several cases where I coudn't make a simple application to work due to its inflexible nature.

I'm really impressed to see that it has more than 22,000 likes.. It's not mature, the most available plugins are quite amateur ... It might be  useful for some presentations or simple apps, but it's seems not meant to be used in most production apps...

To have a bundler with no configuration is the same as create an application using only functions with no arguments. It's a really strange way of thinking for me...

Gulp still has the most smart way of doing things...even though it's not a bundler...

**Comment by eavichay** [comment]
@Javiani I Agree partially. Zero configuration is just like using webpack with all the defaults. I think that configuration simplicity is (i.e. optional tweaks) is mandatory in a bundling tool.

If at least it would load .babelrc, .babelconfig, .loaders ... as optionals I would say it could help but in real life you need tweaks to meet developer requirements.

**Comment by Squeegy** [comment]
Parcel is _not_ zero config, really, if you consider the CLI options as configuration.

I currently have these scripts in my package.json to make parcel work with an electron app.

```
    "parcel:build": "parcel build src/renderer/index.html src/main/index.js --target electron --public-url .. --out-dir dist --cache-dir .parcel-cache",
    "parcel:watch": "parcel watch src/renderer/index.html src/main/index.js --target electron --public-url .. --out-dir dist --cache-dir .parcel-cache"
```

It sure would be nice if at least the CLI options could be abstracted to a `.parcelrc` or something.

**Comment by olstenlarck** [comment]
@Squeegy Exactly

**Comment by gaui** [comment]
👍 for `.parcelrc`

**Comment by dubyajaysmith** [comment]
Ditto. Have similar in package.json testing out with Cordova -- which uses a script tag with `src="cordova.js"`, not loading the correct one until `cordova build [platform]` / after parcel build. To quick fix, I made a dummy file so parcel build kept calm then set the `src` attribute's value back to `src="cordova.js"`. It's still a great pairing with ease of use and html entry.

**Comment by dandv** [comment]
I want Parcel to *not* do any transpilation, because I'm only targeting Chrome. If I do that [via `.babelrc`](https://github.com/parcel-bundler/parcel/issues/1762#issuecomment-430572126), I get an error that Parcel

> Failed to install babel-core

Well, that's the point, *I don't want babel-core*.

**Comment by devongovett** [comment]
@dandv you can use browserslist to disable transpilation. Just add `”browserslist”: [“last 1 Chrome version”]` to your package.json. By adding a babelrc file, you are explicitly *enabling* Babel.

**Comment by n0v1** [comment]
@devongovett the config file should be named either `browserslist` or `.browserslistrc`. You missed the s in browser**S**list.

**Comment by AntonioRecaldeRusso** [comment]
All it takes is one cigarette.. Next thing you know, you're smoking 2 boxes per day

**Comment by cvsguimaraes** [comment]
In a ideal scenario when you know you're dealing with big/complex project and eventually will need to fine tune your build process, you go ahead and make the rational decision of picking a feature rich blunder like Webpack. In that case things like Webpack's `mode` adds more confusion than it helps newcomers since many gets configured for you to get started, but almost always you end up undoing or modifying all these "convenient" configurations and the result we all know: frustrated users using complex features unknowingly with no idea were they should look in the vast documentation to achieve some specific behavior or fix some issue.
Long story short, Webpack's zero-config attempt gives the false impression that the tool is child's play and everyone that really **needs** to use it would be much better off if they took the time to learn it's basics from scratch.

The same goes for Parcel in the sense that it's a convention over configuration tool and you have to deal with it. So much like with Webpack, you have the responsibility to ensure its the best tool for the job and adapt to the peculiarities of the tool you picked (like having a Bachelor's Degree in Webpack Configuration), with Parcel you need adapt to the fact that the tool isn't designed to cover very specific scenarios like the ones posted in this thread, period.

I'm really glad that Parcel keeps avoiding configurations and I think the CLI options should be kept minimal and become simply conventions eventually (for example removing `-o` since the entry point filename already acts as an implicit configuration).

Parcel response for the demand of specific use cases, if any, should be making its plugin system better and easier to implement so more and more users can break free from the tooling addiction we see today in the node ecosystem. 
</rant>

**Comment by GeorgeTaveras1231** [comment]
Would be nice to get parcel to work in monorepo environments. I like to use the `babel` option `rootMode: upwards` to maintain one central babel config at the root of my repository. On top of that, parcel doesn't support the babel `extends` option which would allow me to compose my babel configs. My current work around is to duplicate my babel configs for each project using parcel within the repo.

**Comment by rkingon** [comment]
+1 for CLI options as .parcelrc 👍

**Comment by fengzilong** [comment]
In my case, I need to `use a script to figure out the publicPath` from `process.env.[variable]` and git branch name

Without config file, I **have to use the nodejs api** of parcel-bundler

```js
const Bundler = require('parcel-bundler')
const options = {
  publicUrl: 'path_calculate_from_env_variable_and_branch_name',
}
new Bundler(entryFiles, options).bundle()
```

cli options is good, but any chance to leave user more choices?

honestly I wouldn't like to write to much in npm scripts

I think **bundling app out-of-box with parcel-bundler is the advantage of it, but not `no config file`**

We don't need the flexibility like webpack, but need a js file to save cli options, it doesn't violate parcel's design principle

**Edit:** I see a .parcelrc in parcel-bundler v2, but didn't find the cli options configuration

**Comment by rkingon** [comment]
fyi, i have since started to pretty much solely use the `parcel-bundler` and found it to handle just about everything that i've come across... it's really pretty simple and gives (as ops mentioned) that "10 lines of code"

**Comment by Qix-** [comment]
Parcel assumes all web apps use React, so if any JSX shows up and parcel is, for whatever reason, not picking up the plugin that _should_ compile the JSX, it just falls back to React - which is incredibly aggravating.

For this reason, I **need** a configuration directive to tell Parcel "no, React doesn't exist here - if you can't find something to handle jsx, please die instead and tell me what you tried to do".

Debugging Parcel problems is a joyless experience.
