### ISSUE TITLE
Using with gulp?

### ISSUE THREAD

**Issue by kovirolik** [parcel-bundler/parcel#388]
Just a little question. I want to use Parcel with Gulp. How I can do it? Just run parcel command with gulp?

**Comment by kovirolik** [comment]
Ah, I an use it programmaticaly.

**Comment by dartess** [comment]
Need more information ....

**Comment by kovirolik** [comment]
@dartess idk lol

**Comment by Hfimy** [comment]
what? gulp-parcel is didn't work

**Comment by VicPopescu** [comment]
For anyone that needs to run `parcel for production`, without the watchers, and then use gulp to move the files or do another tasks, you can use native node `child_process` to run parcel with `exec` or `spawn`, like in the example below. 
But for `parcel develop mode`, even if you can run it in parallel with other gulp tasks, you won't see any output logs from parcel because the output is logged only when the child process is finished.
```js
const { exec } = require('child_process');

/**
 * Build solution using parcel
 */
const parcelBuild = () => {
    return exec('parcel build index.html', (error, stdout, stderr) => {
        if (error) {
            console.error(`exec error: ${error}`);
            return;
        }
        console.log(`stdout: ${stdout}`);
        console.log(`stderr: ${stderr}`);
    });
};

const task1= () => {
    return gulpTask1;
};

const task2 = () => {
    return gulpTask2;
};

// "gulp prod" will execute parcel build first, then after parcel is finished, run parallel gulp tasks
exports.prod = series(parcelBuild, parallel(gulpTask1, gulpTask2));
```
