### ISSUE TITLE
Web worker inside npm package built with parcel

### ISSUE THREAD

**Issue by ameerthehacker** [parcel-bundler/parcel#3959]
Hey how I can embed web workers inside a npm package.  The problem Im facing is when I import my npm package for a demo it is trying to dowload the web worker from the public path of the dev server which does not exists

**Comment by mischnic** [comment]
Parcel will automatically parse `new Worker("./myworker.js")` calls, both inside and outside of node_modules.
Please provide a concrete code example if you need more help.

**Comment by ameerthehacker** [comment]
This is the place in my npm library I'm using worker and it gets bundled in the dist

<img width="969" alt="Screenshot 2020-01-05 at 4 57 19 PM" src="https://user-images.githubusercontent.com/15448192/71779495-cf923e80-2fdc-11ea-894c-48706b763517.png">

but when I use it in another parcel project by installing my library(with worker) it says it cannot find __worker.js__ in my new project
<img width="781" alt="Screenshot 2020-01-05 at 4 57 47 PM" src="https://user-images.githubusercontent.com/15448192/71779441-8e9a2a00-2fdc-11ea-86ec-323128cfda1e.png">

**Comment by beautyfree** [comment]
Same

**Comment by mischnic** [comment]
Can someone provide a code sample where this fails? Seems to work for me in a simple example.

(@lgarron ?)

**Comment by lgarron** [comment]
> Can someone provide a code sample where this fails? Seems to work for me in a simple example.
> 
> (@lgarron ?)

https://github.com/lgarron/parcel-2-web-worker-package-import

[`esm-import`](https://github.com/lgarron/parcel-2-web-worker-package-import/blob/main/esm-import.ts) fails with `Uncaught SyntaxError: Cannot use 'import.meta' outside a module`
(See https://github.com/lgarron/web-worker-compat-problems/#problem-7-calculating-relative-paths-requires-importmetaurl, https://github.com/parcel-bundler/parcel/issues/5473, https://github.com/parcel-bundler/parcel/issues/5430)

[`cjs-import`](https://github.com/lgarron/parcel-2-web-worker-package-import/blob/main/cjs-import.ts) fails with `Uncaught SyntaxError: Unexpected token '<'` getting served HTML where JS was expected, because the published package uses `__dirname` but not inline: https://unpkg.com/browse/scrambles@0.1.13/dist/cjs/scrambles.js

I can publish more package versions with other combinations of workarounds. :-P

**Comment by lgarron** [comment]
> the published package uses `__dirname` but not inline

In particular, note that this is required for `node`-compatible CJS code that instantiates a worker. The worker instantiation is not inline because we need to conditionally import the `Worker` implementation on `node` ("conditionally" because we need to *avoid* trying to load it in a browser).

**Comment by lgarron** [comment]
For what it's worth, I'd be happy to drop CJS support and just publish/consume:

```js
new Worker(new URL("./worker.js", import.meta.url));
```

Which would be appropriate for Parcel to compile to non-ESM code for browser targets [while Firefox and Safari still don't support it](https://github.com/lgarron/web-worker-compat-problems/#problem-1-firefox-and-safari-dont-support-module-syntax-in-web-workers).

**Comment by mischnic** [comment]
Ok, so all of that should be covered by #5430

-> https://github.com/parcel-bundler/parcel/issues/5430#issuecomment-770187140

**Comment by jeffpeck10x** [comment]
Not necessarily related, but as a heads up to anybody who finds this and it is not already obvious to, you need `{ type: "module" }` when making a web worker:

```
    const worker = new Worker(
      new URL("./workers/my-worker.ts", import.meta.url)
      { type: "module" }
    );
```

See here:
https://github.com/parcel-bundler/parcel/issues/6261
