### ISSUE TITLE
Parcel 2: HMR not using correct host/port

### ISSUE THREAD

**Issue by slightlyfaulty** [parcel-bundler/parcel#4186]
# 🐛 Bug Report

Commit #3918 changes the HMR runtime to use `location.hostname` and `location.port` for the websocket host/port respectively. This assumes the current page's host/port is that of the Parcel dev server, which is not always the case, e.g. when hot loading assets from a page served via a custom or remote URL.

https://github.com/parcel-bundler/parcel/blob/706a7e647f90c65724f6b3560376c9ffab80eb5e/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L28-L29

## 🤔 Expected Behavior

The HMR runtime should be able to access the websocket from any URL.

## 😯 Current Behavior

The HMR runtime is trying to access the websocket at the current page's location, not the dev server's location.

## 💁 Possible Solution

Make the HMR runtime connect to the websocket at the dev server's (specified) `host` and `port`.

## 🔦 Context

I'm using a docker web server via a custom hostname for development. In Parcel 1 it was never an issue to get HMR working on any page that loads a bundle. In the current build of Parcel 2, HMR only works when loading a bundle from a page served by the Parcel dev server itself.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.116
| Node             | 13.7.0
| npm/Yarn         | Yarn 1.22.0
| Operating System | Linux (Manjaro)

**Comment by wis** [comment]
is there a reason to not also support web pages not served from a server? e.g HTML files opened in the browser from disk (that have a `file://` location.origin/URL-scheme) or a browser extension (that have a different location.origin/URL-scheme, depending on the browser).

I'm currently developing a simple WebExtension boilerplate that uses Parcel, here's how far I got trying to get HMR to work with Parcel V2 watch:
-  followed steps in [Getting Started - CONTRIBUTING.md](https://github.com/parcel-bundler/parcel/blob/v2/CONTRIBUTING.md#getting-started)
- edited **hmr-runtime.js**:
```
  var hostname =
    location.origin === 'file://' ? 'localhost' : location.hostname;
  var port = location.port ? ':' + location.port : ':8080';
  var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
```
I wasn't sure if you can start a Websocket connection from a web page with a non-http URL scheme (for web security reasons), e.g HTML files opened in the browser from disk (that have a `file://` location.origin/URL-scheme) or a browser extension (that have a different location.origin/URL-scheme, depending on the browser), the good news is that you can, it connects to the HMR server of a Parcel V2 _serve command_ (that I ran simultaneously to the watch command, because surprisingly, it appears to me that Parcel V2 watch, unlike V1, has no HMR server yet despite the listing of `--hmr-host` and `--hmr-port` in the output of `parcel watch --help` command), the bad news is that it appears the serve command conflicts with the watch command when ran simultaneously:
```
Uncaught Error: Cannot find module 'cf2ae8451d7db92549d6e9ef2c4c78eb'
    at newRequire (parcel-webextension.184853ea.js:58)
    at newRequire (parcel-webextension.184853ea.js:42)
    at localRequire (parcel-webextension.184853ea.js:80)
    at Object.eval (eval at hmrApply (HMRRuntime.js:187), <anonymous>:5:15)
    at newRequire (parcel-webextension.184853ea.js:68)
    at hmrAcceptRun (HMRRuntime.js:239)
    at WebSocket.ws.onmessage (HMRRuntime.js:75)
newRequire @ parcel-webextension.184853ea.js:58
newRequire @ parcel-webextension.184853ea.js:42
localRequire @ parcel-webextension.184853ea.js:80
eval @ VM19315:5
newRequire @ parcel-webextension.184853ea.js:68
hmrAcceptRun @ HMRRuntime.js:239
ws.onmessage @ HMRRuntime.js:75
```
