### ISSUE TITLE
Node.js app using TypeScript not doing what I expect.

### ISSUE THREAD

**Issue by rajinder-yadav** [parcel-bundler/parcel#430]
**Choose one:** is this a 🙋 feature request? but could be consider as bug.

When I write a simple node.js application using TypeScript, the result is not what I expect.

- I don't need the web server in this care.
- I would just like to see my node code launch, using something like nodemon.

Would be nice to be able to write an API server using parcel. There should be a config to let parcel know if you're building an app that needs a web server, or nodemon, or both.

I could see where someone might want both, nodemon and a webserver running if they are writing an express app.

### package.json

```json
{
  "name": "parcel_app",
  "version": "1.0.0",
  "description": "",
  "main": "main.ts",
  "scripts": {
    "start": "parcel main.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.3.1",
    "typescript": "^2.6.2"
  }
}
```

## main.ts

```ts
const message = 'Hello Parcel';

function greet(s: string): void {
  console.log(s);
}

greet(message);
```

### To run

```
npm start
```

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🤔 Expected Behavior

I expect compiled code to run using node and when I make changes, my TS code is recompiled.

### 😯 Current Behavior

Compiled code with a lot of useless code injected which I don't care for.

### 💁 Possible Solution

Build TS code, launch nodemon and run compiled code, don't inject code.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1
| Node             | 9.3.0
| npm/Yarn         | 5.6.0
| Operating System | MacOS 10.13.2

**Comment by devongovett** [comment]
So far, Parcel has been focused on bundling for browser usage. Bundling for Node is something we might consider for the future, but seems less valuable than browser bundling in my opinion. Why do you need to bundle code for node rather than using something like https://github.com/TypeStrong/ts-node?

**Comment by jtenner** [comment]
Definitely would love to use parcel for both reasons. I imagine being able to point parcel at a library entry point and supercharging by library building speed.

What if I want my library to be an scss framework too? Just point parcel at the entry point! My development is supercharged.

There are very noble reasons to develop this sort of package, the question is, what is the purpose of parcel?

**Comment by jtenner** [comment]
Please delete my comment, I didnt read the report correctly.

**Comment by shawwn** [comment]
Agreed. `parcel foo.js` should act the same as `node foo.js`, or
`babel-node foo.js` if a .babelrc is present.

`parcel foo.ts` should act like `ts-node foo.ts`

`parcel foo.coffee` should act like `coffee foo.coffee`

And passing --watch should re-run those files when changes are detected.

That would give a pretty nice rapid prototyping framework. We could
integrate Karma testing too for convenience.

Also, parcel should be able to be run like `parcel --html foo.js` which
automatically generates `foo.html` similar to:

```
<html>
<body>
  <div id="app"></div>
  <script src="./foo.js"></script>
</body>
</html>
```

That's the default case that most people would want when doing webdev,
anyway.

This is probably better as an RFC so that everyone can throw in their
thoughts.

**Comment by rajinder-yadav** [comment]
I wrote a project generator tool for static webpage dev (think CSS prototyping), node project using TypeScript or plain JS. I am currently using nodemon, browser-sync and other packages using NPM script and it works well. It would greatly simply things using parcel, also other people doing dev using TypeScript would only need to use one tool, right now most are using webpack.

If you want greater adoption, you should make this a high priority.

Speaking for myself I code in both React and Angular, and would never need to care or touch parcel, their CLI tool does everything I need to run, test and build my code. So who is your target audience? People making static websites??

**Comment by dragosbulugean** [comment]
@devongovett I am completely fine with using ts-node for development, but I would also like to be able to bundle a node.js server-side app (TS or Babel) for production -- so we only send one small file to production. That would be super nice. 

I am trying to use it with:
```
parcel build api.ts
```
But it fails for me because it tries to evaluate fs calls. 
If only we could tell parcel to not do it 🥇

**Comment by devongovett** [comment]
See #192 for node bundling support, and #652 for a WIP PR.
