### ISSUE TITLE
Batteries included for svgs?

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#4308]
Hi there,

Firstly - fantastic project. Thanks for your hard work.

I am trying to move from parcel@1 to parcel@2. However, I am getting an issue with SVGs:

Importing `.svg` files are no longer automatically provide their file path. I just get this:

```
Build failed.
Error: No transformers found for "[my root path]/src/icons/capture.svg".
```

Am I supposed to add a `transformer`? I can do that; but I am also thinking that `svg` file path resolution should work out of the box

**Comment by alexreardon** [comment]
I managed to fix it by using the suggested fix here: https://github.com/parcel-bundler/parcel/issues/4222

Although I couldn't see any information about that behaviour in the `readme.md`...

Are there other prefixes that work out of the box? What are they?

**Comment by mischnic** [comment]
Use the `url:` custom pipeline prefix, I explained why in the linked issue.

Here is the full list https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json.

`types.` is used by the `package.json#types` handling. (so rather internal)
`data-url:./img.png` gives you the data-url instead of a url to a new bundle.
`bundle-text:./worker.js` to receive the literal text of the compiled bundle content

**Comment by alexreardon** [comment]
Thank you for your quick reply! I appreciate it

**Comment by Cristy94** [comment]
> Use the `url:` custom pipeline prefix, I explained why in the linked issue.

Where should we use this pipeline prefix? Images should really work by default with zero configuration?

**Comment by mischnic** [comment]
> Where should we use this pipeline prefix? Images should really work by default with zero configuration?

see https://github.com/parcel-bundler/parcel/issues/4222#issuecomment-591377501
This is more problematic with `import x from "./app.css"`, the approach that Chrome takes (return some `CSSStyleSheet` object) is completely incompatible with the object map that all bundler do.
