### ISSUE TITLE
Tree-shaking dynamic imports

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#4318]
# 🙋 feature request

I am wondering if it has ever been considered to enable tree-shaking on dynamic imports. As a starter: If (and only if) _every_ import of a module is easily statically analyzable, the same dead code elimination routines as they are used for static imports could be run.

If it is _not_ easily analyzable, Parcel could always fall back to the current behavior. The resulting bundle sizes should remain same size _or get smaller!_.

# Example

```js
const { logCaps } = await import('./utils.js');
```

```js
//utils.js
export function logCaps(msg) {
  console.log(msg.toUpperCase());
}

export function thisIsNeverCalled(msg) {
  return msg + '!';
}
```

[Example repo](https://github.com/surma-dump/parcel-dead-code-dynamic)

**Comment by kzc** [comment]
Related discussion: https://github.com/rollup/rollup/issues/3417#issuecomment-595650816

**Comment by devongovett** [comment]
With pure ESM this should be possible. We'd need to move the analysis of used imports to the bundling phase instead of the packaging phase though. It currently happens [here](https://github.com/parcel-bundler/parcel/blob/v2/packages/shared/scope-hoisting/src/concat.js#L155). cc @mischnic I think you were running into something related today.
