### ISSUE TITLE
404 Page not found when serving arbitrary file

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/parcel#4429]
# 🐛 bug report

I'm trying to use Parcel 2 in no-config mode, for a very simple use case, serving a file named `test.html`. That fails with a 404 Page not found in the browser. There is no error shown anywhere.

## 🎛 Configuration (.babelrc, package.json, cli command)

node_modules/.bin/parcel serve test.html

## 💁 Possible Solution

Rename the file to `index.html`.

## 🔦 Context

I'm trying to serve different HTML files.

Must I create targets in `package.json`? I've read the README on that and it's not quite clear. For example, what does [dist/browser/index.js](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/README.md#target-configuration) represent? The [Sources](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/README.md#sources) section says at `1.` that specifying the file on the CLI should work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v13.11.0
| npm         | 6.14.3
| Operating System | Linux

**Comment by mischnic** [comment]
This search for which bundle is served as the index:
https://github.com/parcel-bundler/parcel/blob/31c07ce8e81d808554fdbe51ef0ce3497accda5b/packages/reporters/dev-server/src/Server.js#L135-L152

should instead do:
- if there are 2 or more html bundles: 404 (because of the ambiguity, maybe the error page should state this as well)
- if there is only one html bundle: use that

<br>

> Must I create targets in package.json?

No

>  For example, what does dist/browser/index.js  represent?

The output bundle (not input!)
```json
{
	"main": "<<output>>",
	"app": "<<output>>",
	"source": "<<input>>",
	"targets": {
		"app": {}
	}
}
```
`parcel build path/to/package` (with `source` specified) and `parcel build <<input>>` are equivalent.

**Comment by MylesWardell** [comment]
How do you serve a html page inside a react app with parceljs? Was a solution proposed?

**Comment by huangjincq** [comment]
think it may be caused by the low version of node. I can solve the problem by upgrading node version to more than 16.0.0
