### ISSUE TITLE
[Parcel2] Alias doesn't always resolve

### ISSUE THREAD

**Issue by M3kH** [parcel-bundler/parcel#4437]
# 🐛 bug report
I'm compiling a website which has multiple `entrypoints` (eg: ).
I have some `.html` files that live in a subfolder, I try to use `~` but didn't work.
So I try to create an `alias` but got the same issue.

## 🎛 Configuration (.babelrc, package.json, cli command)
I run parcel with `parcel serve exported/*.html`, no special config.

## 🤔 Expected Behavior
Should have resolve the `alias` (default `~` or `custom`) even if the `.html` file is in a nested directory

## 😯 Current Behavior
```
🚨 Build failed.
@parcel/core: Failed to resolve '~style/index.scss' from './exported/blog/20200318.html'
```

## 💁 Possible Solution
I will try to investigate further, nothing now (I'm currently downgrading because of this issue). 

## 🔦 Context
I was trying to deploy a static blog.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-alpha.3.2
| Node             |  v10.16.0
| npm         |  6.13.7
| Operating System | OSX

**Comment by mischnic** [comment]
Works for me: https://github.com/mischnic/parcel-issue-4437

**Comment by fsoikin** [comment]
I have the same problem (I think?)

I have the following alias defined:

```
// package.json
{
   ...
   "alias": {
      "jsx": "./jsx"
   }
   ...
}
```

(don't ask why I need this; I'm very sure that I do)

This works perfectly fine with `--target browser`, but stops working with `--target node`. Parcel simply doesn't build any modules under `./jsx`, as if they were under `node_modules`. Specifying `--bundle-node-modules` does help, so that's a workaround.

**Comment by fsoikin** [comment]
New information: turns out this is related just to `--bundle-node-modules`, not to `--target`.

Evidence: if I use Parcel API and set `target: 'browser', bundleNodeModules: false`, the `./jsx` aliases don't get included. As soon as I switch true `bundleNodeModules: true` it works as expected.

Also, a side note: looks like switching `bundleNodeModules` between `true` and `false` doesn't bust the file system cache. After switching I have to manually nuke the cache for the new value of `bundleNodeModules` to take effect.

**Comment by mischnic** [comment]
> I have the same problem (I think?)

You're using Parcel 1, the original post said Parcel 2.

> Works for me

We can't help you/find the bug without a reproduction case.
