### ISSUE TITLE
Remove hash from images

### ISSUE THREAD

**Issue by n3nikita** [parcel-bundler/parcel#4486]
# 🙋 feature request

I have folder with images and I need to remove hash from image filenames because of the problems with my hosting I need names without hash. How can I achieve it? 

## 🤔 Expected Behavior

`img/logo.svg` --> `logo.svg`

## 😯 Current Behavior

`logo.svg` --> `logo.d6cc4a5c.svg`

## 💁 Possible Solution

I have tried `--no-content-hash` flag but It doesn't help.

**Comment by DeMoorJasper** [comment]
`--no-content-hash` just causes it to hash based on filename instead of content as far as I remember.

This is impossible with Parcel 1, Parcel 2 allows custom naming plugins although we're still figuring out a way to make it easier.

In both cases it relatively bad practise to remove hashes from these assets as it will require you to set the caching policy on your cdn to a very short duration, resulting in more expensive hosting and slower web-apps/sites.

**Comment by basher** [comment]
This issue has been [reported](https://github.com/parcel-bundler/parcel/issues/4346) [before](https://github.com/parcel-bundler/parcel/issues/3982).

@DeMoorJasper I reported the 4346 bug above - I need to use the same reference to an external SVG sprite in my HTML markup - e.g. `<use xlink:href="dist/svg-icon-defs.svg#icon-whatever" />` -  whether I'm in local DEV mode or in any deployed environment such as TEST or PROD.

The hash will change in each environment, and after each build, so the sprite will never be found.

Secondly, any idea how long before Parcel V2 is released?
I really want to stick with Parcel rather than revert to using Webpack.

**Comment by basher** [comment]
Any update on this issue?

I've upgraded to Parcel V2 (nightly), and `--no-content-hash` is no longer supported now.

**Comment by DeMoorJasper** [comment]
@basher Parcel 2 has namer plugins for this, we're still figuring out how to make this easy to customise without having to write an entire plugin though...

So there's not really a point in having `--no-content-hash` anymore, not that it ever was anything but a backwards compatibility feature anyway

**Comment by basher** [comment]
Thanks for the update @DeMoorJasper 

Any guestimates about how long this will take?

Btw, I do appreciate that you guys are probably very busy trying to get V2 released.

**Comment by DeMoorJasper** [comment]
@basher the namer plugins are already a thing. The simplification is not really on our road map atm so probably not before the beta in a couple weeks/months

**Comment by basher** [comment]
Thanks @DeMoorJasper 

I've looked at the docs - e.g. [parcelrc namers entry](https://github.com/parcel-bundler/parcel#parcelrcnamers) - but they don't explicitly state how to utilise existing plugins in this specific scenario for removing hashes.

Can you provide some precise help?

**Comment by DeMoorJasper** [comment]
@basher there's a work in progress version of the real docs https://parcel2-docs.now.sh/plugin-system/namer/

**Comment by basher** [comment]
@DeMoorJasper 
Thanks for your help so far... and sorry if this is a stupid question... but I'm confused about how to actually "_register_" a new plugin with Parcel?

There's very little on Stack Overflow, and browsing some of the existing plugins doesn't help.

What I've done so far:
- I've added a local NPM package - e.g. `.\local_modules\parcel-namer-my-plugin\` folder, which contains `index.js` and `package.json`.
- I've installed local package as a `devDependency` inside my root `package.json`. 
- All the plugin should do is `console.log` some output.

How do I get it to execute when I run `parcel src/ts/index.ts --port 1234`?

**Comment by mischnic** [comment]
Specify it in a `.parcelrc`

```json
{
  "extends": "@parcel/config-default",
  "namers": ["parcel-namer-my-plugin", "..."]
}
```

https://github.com/parcel-bundler/parcel/blob/v2/packages/examples/eslint-example/.parcelrc

**Comment by basher** [comment]
@DeMoorJasper @mischnic 
Thanks both for your help... 

Unfortunately, I can't even get a `console.log` to work when I run Parcel, so the plugin does not appear to execute. Therefore, I'll revert back to including the SVG sprite in the HTML at the top of `<body>` rather than `import '../icons/svg-icon-defs.svg';` from my Parcel entry point.

I could, of course, write a Node script to copy the `icons` folder to `dist`, but that defeats the whole purpose of using a no-config bundler like Parcel.

Can I make a suggestion?

Can you reconsider adding a `--no-content-hash` flag, or maybe an array in `.parcelrc` that lists excluded files/folders, so that it's easy for users to turn off the hashing?

There are scenarios where this is needed - e.g. when the HTML needs to reference a static asset.

**Comment by DeMoorJasper** [comment]
@basher I think we'll eventually end up with some way to configure naming in pkg.json or something with an official namer to make this easier so I do think it's on the timeline as I mentioned in my original reply. But it's not one of our priorities atm as we're focused on getting a beta out and eventually stable version of Parcel 2

**Comment by basher** [comment]
@DeMoorJasper That's great, thanks. It's no hardship for me to have the SVG sprite in the HTML for now.

Parcel is awesome, btw! So much easier than Grunt/Gulp/Webpack. It pretty much does everything I need straight out of the box with very little setup.

**Comment by devongovett** [comment]
Closing because namer plugins are the solution.

**Comment by Javarome** [comment]
@devongovett the solution should be implemented though a namer plugin, but such a "no hash" plugin should be shipped with parcel, as it is a common need. 
As one reason for choosing parcel is the simplicity of configuration (sometimes almost none), you cannot ask users to write plugins for such common needs.

**Comment by justingolden21** [comment]
Wondering if there has been any progress on this; I'm writing a PWA and need to have the same file names for my output. Is there still no way to do this? I just want to combine my js into a file called "main.js" and my css into a file called "styles.css." Surely this isn't an uncommon ask, right?

**Comment by good3n** [comment]
This is just another thing on the list of "shortcomings" with Parcel. I put it in quotes because I'm not entirely sure what vision for Parcel from the dev's perspective is supposed to be. There are some really simple additions that could make it a lot better for a lot more people (see above).

I really do hope this, along with some of the other very popular suggestions/requests in the closed issues are addressed properly some point in the future.
