### ISSUE TITLE
Make plugin run last

### ISSUE THREAD

**Issue by VladimirMikulic** [parcel-bundler/parcel#4516]
Hi!

Is there a way for me as a developer to make my plugin run last after all other plugins had run?

Thank you.

**Comment by DeMoorJasper** [comment]
Which Parcel version are you using?

**Comment by VladimirMikulic** [comment]
v1.12.4

**Comment by DeMoorJasper** [comment]
In that case you can not. Parcel 2 has a config for this but Parcel 1 does not have this.

You can make it register last by making it last in the `devDependencies` but that would probably not solve your issue. Especially not if any of the plugins do anything asynchronous in that same event.

**Comment by VladimirMikulic** [comment]
You are right, there are async operations and this approach wouldn't work.
Anyway, thank you for your response.

**Comment by IsaacHub** [comment]
> Is there a way for me as a developer to make my plugin run last after all other plugins had run?

@VladimirMikulic  This doesn't make any sense, I filed an issue that your plugin deletes files with extension `.br` and `.gz`, This has nothing to do with `parcel-plugin-compress`, That plugin's job is to make `.gz` files, your plugin's job is to move them to a specified directory. 

Your plugin deletes `.js.gz` files instead of moving. what this has to do with order of execution or async/sync operations? **If `*.js.map` can be moved then why not `*.js.gz`?**
