### ISSUE TITLE
Styles not being update when using SCSS partials on different HTML page

### ISSUE THREAD

**Issue by ajayns** [parcel-bundler/parcel#4570]
# 🐛 bug report

Changes made to styles not updated on the dev server unless the site is manually reloaded.

Steps to reproduce:
1. Have 2 HTML files sharing the same stylesheet. (here index.njk, about.njk)
2. Use SCSS partials in the stylesheet.
3. Update one of the style partials while dev server running on `localhost:1234/about` and save.

Similar to https://github.com/parcel-bundler/parcel/issues/1931

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel config,
I use sass + postcss and parcel-plugin-nunjucks.

package.json
```json
{
  "devDependencies": {
    "@babel/core": "7.2.0",
    "autoprefixer": "^9.7.6",
    "nunjucks": "^3.2.1",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-nunjucks": "^2.2.0",
    "postcss-modules": "^2.0.0",
    "sass": "^1.26.5"
  }
}
```

## 🤔 Expected Behavior

As I make changes to any SCSS files, regardless of the page I'm in, it should trigger a refresh and style update.

## 😯 Current Behavior

No changes to style on the page.

In the console, this pops up as well:
```
Uncaught Error: 
Cannot find module '../node_modules/parcel-bundler/src/builtins/css-loader.js'
```
Which seems similar to https://github.com/parcel-bundler/parcel/issues/2936 but I can't see a fix there either.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.16.1
| Yarn         | 1.22.4
| Operating System | macOS 10.14.6

**Comment by ajayns** [comment]
Any ideas on this @mischnic ?

**Comment by mischnic** [comment]
Does seem like the same issue as #2936.

(This is probably https://github.com/parcel-bundler/parcel/issues/2340 in disguise (because css-loader should be part of multiple bundles but Parcel 1 didn't allow that))

I don't have any workarounds apart from these
- https://github.com/parcel-bundler/parcel/issues/2936#issuecomment-513811843
- https://github.com/parcel-bundler/parcel/issues/2936#issuecomment-620025705 (quite a hack but seems to work for some people)
