### ISSUE TITLE
Express Middleware in Parcel 2?

### ISSUE THREAD

**Issue by samanime** [parcel-bundler/parcel#4612]
Is there any kind of middleware for Express built into Parcel 2 yet?

I pulled the repo and the only references seem to be in the (now private) parcel-bundler package.

I also couldn't find any documentation that would seem to indicate it, other than talking about the more programmatic interface, but that still seemed to be pretty self-contained and couldn't be wired with Express directly.

Am I missing something? Any code or samples?

**Comment by DeMoorJasper** [comment]
@samanime there's no more middleware in parcel 2

We moved away from it to streamline our plugin ecosystem and have a plugin type named reporter that could be used to create your own server if you'd really want to have that. Or you could simply run parcel in watch mode and run your own server on the dist directory.

**Comment by adrianmcli** [comment]
This sounds like a pretty big cognitive shift from the middleware approach. The Reporter docs are also quite bare right now: https://parcel2-docs.now.sh/plugin-system/reporter/

Will there be an example of how to migrate from the old Express middleware approach?

**Comment by adrianmcli** [comment]
Regarding the programmatic API, @mischnic [posted](https://github.com/parcel-bundler/parcel/issues/2574#issuecomment-630026649) some [examples](https://parcel2-docs.now.sh/features/parcel-api/) from the new docs.

It's good to see these examples, but I still can't wrap my head around how to migrate from v1 to v2. I suggest that we put out a "Migration Guide" for those who are using the previous API with the Express middleware, illustrating exactly how to replicate the same behavour in a "before and after" manner.

For example, this is what I currently have:

```js
const Bundler = require("parcel-bundler");

const entryFiles = [path.join(__dirname, "./app/index.html")];
const bundler = new Bundler(entryFiles, { logLevel: 1 });

const app = express();
app.use("/", bundler.middleware());
```

I shouldn't need to learn about the plugin ecosystem and the reporter to make this work. Ideally there should be an equivalent code block example so that we can easily migrate to v2.

**Comment by 101arrowz** [comment]
You don't need to use the middleware with the new [proxying feature](https://v2.parceljs.org/features/api-proxy/).

If you want to emulate your above code:

In `server.js`:
```js
const app = express();
app.get('/hello-world', (req, res) => {
  res.send("Hello world!");
});
app.listen(54321);
```

In `.proxyrc`:
```json
{
  "/api": {
    "target": "http://localhost:54321",
    "urlRewrite": {
        "^/api": ""
    }
  }
}
```
That proxy config will make Parcel reroute all requests from `http://localhost:parcel-port/api/your-path` to `http://localhost:54321/your-path`.

**Comment by pykenny** [comment]
I was doing something like this in Parcel 1, in order to server static files from another directory:

```
const bundler = new Bundler(entry, options);   // A parcel-bundler instance
const server = express(); // Express server for static files in another directory

// Serve static files in '/path/for/some/other/static/files'
server.use('/other_statics', express.static('/path/for/some/other/static/files'));
// Set up parcel-bundler middleware
server.use(bundler.middleware());

server.listen(port);
```

Does removing middleware means I must separate them into two scripts (one for Express server, and another for Parcel)? Using proxy feature also sounds like I need to modify `.proxyrc` whenever I change Express server's port.

**Comment by DeMoorJasper** [comment]
@pykenny you can also use javascript in the proxy config, so you can actually start your express server in that script if you want the same-ish behavior as before.
