### ISSUE TITLE
Give all plugins access to config

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#4655]
# 🙋 feature request
Give every plugin type access to a `config` object (options for the plugin itself) in Parcel v2. The plugin configuration will be found and parsed by Parcel in either `package.json` or in `.parcelrc`.

## 🔦 Context

[My plugin for Parcel v1](https://github.com/101arrowz/pwa-manifest/tree/master/packages/parcel-plugin-pwa-manifest) needed access to configuration to function. In Parcel v1, getting config meant either reading directly from the filesystem or reading from `package.json` using `entryAsset.getPackage()`. Not only is this bad practice, it can be managed better in Parcel v2 with the existence of the `.parcelrc` file.

## 💻 Examples

In `.parcelrc`:
```json
{
    "runtimes": [
        "parcel-runtime-thing",
        ["parcel-runtime-with-config", {
            "my": "configuration",
            "is": { "right": "here" },
            "any": [
                 "json object is supported",
                  1234
            ]
        }]
    ]
}
```

In addition to the other parameters provided to the `bundle` method, `parcel-runtime-with-config` will receive a `config` key with the same value as the second element in the above tuple. On the other hand, `parcel-runtime-thing`, will receive `null` for `config`.

**Comment by DeMoorJasper** [comment]
> either reading directly from the filesystem or reading from package.json using entryAsset.getPackage(). Not only is this bad practice

How is this bad practice? I would argue the other way around is bad practice, due to the spread of config in tooling specific config files like parcelrc or webpack.config.js or whatever you lose the ability to re-use configs across bundlers and other tools like tests, ...

For this you should probably add a key to pkg.json or an additional file like you stated it should not have any significant performance impact and we're gonna look into optimising this regardless anyway.

We have good reasons for not allowing this and I doubt this will change.
