### ISSUE TITLE
Parcel 2 - TS declaration files are not generated

### ISSUE THREAD

**Issue by klemenoslaj** [parcel-bundler/parcel#4666]
# 🐛 bug report

Configuring the `types` in `package.json` does not cause Parcel to generate declaration files.
Worth mentioning I am testing parcel in Yarn workspace. This might work in "one package" repository - I did not test that.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "main": "./dist/index.js",
  "source": "./src/index.ts",
  "types": "./dist/index.d.ts"
}
```

## 🤔 Expected Behavior

Parcel should use the configured transformer to generate declaration files.

## 😯 Current Behavior

The build simply fails:

```
@parcel/namer-default: Target "types" declares an output file path of "dist/index.d.ts" which does not match the compiled bundle type "js".
lit-element-monorepo/packages/first-page/package.json:5:12
  4 |   "source": "./src/index.ts",
> 5 |   "types": "./dist/index.d.ts",
>   |            ^^^^^^^^^^^^^^^^^^^ Did you mean "dist/index.d.js"?
```

_Note: for another package it succeeds building, but doesn't produce the declaration files._

## 🔦 Context

In workspaces environment all the packages get linked to the `node_modules` in the root of the repository.
TypeScript expects the library to provide own declaration files, or having the declarations in `@types/library-name`. However with parcel not generating any this is a problem even before publishing the package to npm registry, because typescript is correctly failing in dev-time too:

```
Could not find a declaration file for module `first-page` ...
```

_Question: how are parcel & TypeScript supposed to work in this situation when we're building the package using the configured `sources` and not the pre-built bundle from the `dist`? The imports consistently fail with `Cannot find module 'first-page' or its corresponding type declarations.`. New issue?_

## 💻 Code Sample

- clone [this](https://github.com/klemenoslaj/lit-element-monorepo) repository
- checkout `no-typescript-declarations` branch
- execute `yarn workspace first-page build` - failing with error
- execute `yarn workspace second-page build` - builds but without declarations

_To reproduce the imports like failing in the question in previous section, comment out `@ts-ignore` from `packages/application/src/app.element.ts` lines `92` and `97`._

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.275+d33fcd9c
| Node             | v12.16.1
| npm/Yarn         | 1.22.4
| Operating System | macOS Mojave 10.14.6

**Comment by mischnic** [comment]
Only happens with a custom parcelrc that overrides the `ts` pipeline because when determining the pipeline for `types:index.ts`, the custom parcelrc takes precedence and it is processed like any other ts asset.

The current logic is:
1. select pipeline with matching named pipeline and type
2. otherwise select pipeline with matching type
3. otherwise continue search in parent config

Should be:
1. select pipeline with matching named pipeline and type
2. otherwise select pipeline with matching named pipeline and type in nearest parent config
3. otherwise select pipeline with matching type in current config
4. otherwise select pipeline with matching type in nearest parent config
