### ISSUE TITLE
Add support for glob imports to Parcel 2

### ISSUE THREAD

**Issue by Smiley43210** [parcel-bundler/parcel#4683]
# 🐛 bug report

Parcel 2 does not return transformed URLs when importing raw files specified using a glob pattern from JavaScript with any of
```js
import asset from 'url:/assets/**/*';
import asset from 'url:/assets/*';
import asset from 'url:/assets/*.ext';
```

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**
```js
{
  "name": "test",
  "dependencies": {
    "parcel": "next"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0"
  }
}

```

## 🤔 Expected Behavior

From what I understand from the old Parcel docs, an object containing a mapping of files to transformed URLs should be returned, such as the following:
```js
{
   'file-1': '/file-1.8e73c985.png',
   'file-2': '/file-1.8e73c985.png'
}
```

## 😯 Current Behavior

Parcel fails during bundling with the following error:
```
$ yarn parcel index.html
ℹ Server running at http://localhost:1234
Building index.html...
× Build failed.
@parcel/core: Failed to resolve 'url:/assets/*' from './index.html'
C:\Users\User\Workspace\test\index.html:1:20
> 1 | <html>
>   |       ^
  2 |   <head>
  3 |     <script>
@parcel/resolver-default: Cannot load file './assets/*' in './'.
Did you mean ./assets?
```

## 💁 Possible Solution

Related:
#4222
#4055

## 🔦 Context

I am writing a game using three.js and was trying to import my images so that I can load them as textures.

## 💻 Code Sample

**Folder Structure**
```
/root
 |-- /assets
 |    |-- test.png
 |-- index.html
 |-- package.json
```
**index.html**
```html
<html>
	<head>
		<script>
			import assets from 'url:/assets/*';
			console.log(assets);
		</script>
	</head>
</body>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 (also reproducible on 2.0.0-nightly.277+149c00b7) |
| Node             | v12.17.0 |
| npm/Yarn         | yarn 2.0.0-rc.33 |
| Operating System | Windows 10 1909 |

**Comment by mischnic** [comment]
Parcel 2 doesn't support globs (yet).

**Comment by 0xbkt** [comment]
> Parcel 2 doesn't support globs (yet).

Is there workaround to import multiple files for the time being?

**Comment by mischnic** [comment]
Something like https://www.npmjs.com/package/babel-plugin-transform-glob-import (the only downside: you need to manually clear the cache when changing one of the imported file)

>  Is this also about the resolver?

No, at the moment a resolver plugin can only return a single result, so this would need further further in core.

**Comment by mischnic** [comment]
> No, at the moment a resolver plugin can only return a single result, so this would need further further in core.

Correction: the problem at the moment is that the resolver couldn't add the directory to the watcher.

**Comment by Mstrodl** [comment]
Are there any plans to support this behaviour some time soon? This was one of the things I liked about parcel. I would keep using v1 since it's a lot easier, but it seems it's not very well supported (but neither is v2 it seems)

**Comment by allocenx** [comment]
This would be a must too, especially for modular architecture in components, something like:

`import Modules from 'Modules/**/index.js'`
or
`import * as Modules from 'Modules/**/index.js'`

where **Modules** is an alias within package.json targeting **src/modules** directory.

This [https://github.com/devongovett/babel-plugin-transform-glob-import](https://github.com/devongovett/babel-plugin-transform-glob-import) seems to be the only one working with Parcel v2 but breaks the *import url:...* and also does not work with Parcel's aliases...

**Comment by leoncvlt** [comment]
Another educated thumbs up for this feature, I was amazed when I first witnessed it working in parcel v1 and since then it became a staple in most of my javascript projects' architecture.

It's probably the only thing keeping me from moving to v2 😃

**Comment by RPDeshaies** [comment]
Parcel 2 is a big beast, and it's understandable that some features might not make it or may take some time to be migrated. Especially considering that Parcel is an open source project.

I think that instead of saying things like "we need this or I won't use parcel", it might be a good idea to say the reasons why it would be worth adding to Parcel 2.

A reason I personally see this as an interesting feature is when you are trying to include a wiki or blog post section in an application.

e.g.

```tsx
import wiki from "url:./docs/**/*.md"
console.debug("wiki", wiki)
```

In parcel v1, this (without the `url` flag) would output something like

```
{
  "introduction" : "markdown content", // file
  "getting-started": { // folder
    "step-1": "markdown-content", // file
    "step-2": "markdown-content", // file
    "step-2": "markdown-content", // file
  }
}
```

Perhaps in parcel 2, this could output a similar structure but with links to the bundled resources when used in conjunction with the `url` flag.

**Comment by devongovett** [comment]
This should be addressed by #5933, which introduces a `@parcel/resolver-glob` plugin. It supports loading globs from within JS and CSS files. In JS, they can be synchronous or dynamic imports, and pipelines (e.g. `url:`) are supported. Because it's an actual Parcel plugin instead of a Babel plugin, the watcher and cache should invalidate automatically when a new file matching the glob is added. 😄

**Comment by RPDeshaies** [comment]
This is very cool and so nice to hear! 😄

**Comment by chinoto** [comment]
To make use of this feature right away, set your parcel version to `nightly` (`next` is too old) and add this [`.parcelrc`](https://github.com/parcel-bundler/parcel/blob/bdb43afa4aaab364f4018634bc8c0d6e7fc6c30c/packages/core/integration-tests/test/integration/glob-async/.parcelrc) to the root of your project.

**Comment by BarakChamo** [comment]
Wanted to ask here rather than open a new issue as I've been following this thread and instructions here.

With `parcel` and `@parcel/resolver-glob` set to either `nightly` or `next`, async (e.g. `url:`) imports do not work.

So this works:
`import file from "foo/bar/*.ts"`

but this fails
`const files = import("foo/bar/*.ts")`

with the following error:
`ENOENT: no such file or directory, open 'D:\Projects\test\dist\\*.e674183c.js.1115428497'`

Is there anything to note about project setup  or parcel versions to get async dynamic imports to work?

Thanks!

**Comment by mischnic** [comment]
@BarakChamo Can you open an new issue?

**Comment by BarakChamo** [comment]
@mischnic I'm not sure what happened but the issue went away on `@nightly`, all good here 👍
