### ISSUE TITLE
google-closure-compiler support 🙋

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [parcel-bundler/parcel#479]
🙋 feature request

**Comment by DeMoorJasper** [comment]
Could u please supply a bit more information and maybe fill in the issue template i copied into ur description? :)

**Comment by brandon93s** [comment]
Since this duplicates some of the functionality that parcel already provides, it would be best implemented as a plugin. google-closure-compiler and their [npm module](https://www.npmjs.com/package/google-closure-compiler) could be used to extend from `JSAsset` to provide this additional functionality.
