### ISSUE TITLE
🙋 moment.js zh-cn fail

### ISSUE THREAD

**Issue by echowant** [parcel-bundler/parcel#491]
Using the following code to do the Sinization of the time,
it is failed by parcel. But by webpack，it is ok.
Can you help me?

```
import  moment from 'moment';
import 'moment/locale/zh-cn'
moment.locale('zh-cn');
```
![tim 20180104180226](https://user-images.githubusercontent.com/18191880/34558483-49ac78b0-f179-11e7-857e-915df73ca61c.png)

**Comment by PlayMa256** [comment]
What is the error that parcel throws? Or none?

**Comment by niicojs** [comment]
I do have a similar issue. Parcel works fine, but the second import does not do what it should.
It is supposed to modify the moment global variable to add stuff into it, but I guess it cannot access moment as it's not global?

**Comment by fathyb** [comment]
I think it's related to #418

**Comment by PlayMa256** [comment]
check pr #530 and see if it works.

**Comment by fathyb** [comment]
@PlayMa256 it shouldn't work on this case.

**The problem** :
- `import moment from 'moment'` is resolved to an ES6 module, according to the `module` `package.json` field
- `import 'moment/locale/zh-cn'` is resolved to an UMD module, which uses the moment commonjs module

**What it means** : you are using ES6 moment, the locale uses CommonJS moment, it's two different instances, so the locale will not apply.

**Workaround** (pick one) :
- Use the ES6 locale :
  ```js
  import locale from 'moment/src/locale/zh-cn'

  moment.locale('zh-cn', locale)
  ```
- Use the CommonJS moment :
  ```js
  import moment from 'moment/moment'
  ```

Caused by #299, related to #418

**Comment by niicojs** [comment]
in my case, this is what fix it:
```
import * as moment from 'moment/moment';
import 'moment/locale/fr';
```

**Comment by DeMoorJasper** [comment]
Should have been fixed
