### ISSUE TITLE
Seems multiple bugs in Parcel 2. Not able to run Vue project

### ISSUE THREAD

**Issue by bubnenkoff** [parcel-bundler/parcel#4982]
I tried to use Parcel 2 with Vue and https://github.com/r3code/vue-vis-network but faced with multiple issues.
I created repose to simplify reproduce it https://github.com/bubnenkoff/parcel2-issues
The problem that today I even not able to run `npm install` because I am getting error:
`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@parcel%2fconfig-default - Not found`

But yesterday all works. I hope that I make repo more or less working, but it may need to several fix.

The first problem was pointed here https://github.com/parcel-bundler/parcel/issues/3364#issuecomment-669615576

If update Vue to 3.0 rc I got cyclic rebuilding of all project.

The main problem was run vue-vis-network with Parcel 2, because it do not have UMD builds.

I used latest versions of Parcel.

**Comment by mischnic** [comment]
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@parcel%2fconfig-default - Not found

npmjs.org is currently having network problems: https://status.npmjs.org/
> Issues accessing npmjs.com and installing scoped packages

**Comment by 101arrowz** [comment]
Your reproduction repo has a few issues.

The `.parcelrc` causes all files to be transformed by the raw transformer, which basically does nothing and causes the app not be bundled at all. If you remove the `.parcelrc`, the app bundles but fails at runtime because you're trying to use Vue 2, but Parcel (at least for now) [only supports Vue 3 beta](https://v2.parceljs.org/languages/vue/) or later. Switching to Vue 3, the app works but your dependencies are Vue 2 only, so nothing really appears on screen.

You can ask the developers of the dependencies you're using to start porting their codebases to Vue 3, but as of right now you can't do anything but use Parcel 1.

**Comment by 101arrowz** [comment]
@bubnenkoff Did you resolve the issue?

**Comment by bubnenkoff** [comment]
I will wait for Vue 3.0 release
