### ISSUE TITLE
Babel error when using `parcel build` with `solid-js`

### ISSUE THREAD

**Issue by amoutonbrady** [parcel-bundler/parcel#5025]
# 🐛 bug report

I'm trying to use parcel 2 with [solid-js](https://github.com/ryansolid/solid) but get an error while building the project.

In development mode, it works really well but when I use `parcel build index.html`, it get stuck at the scope hoisting process. It provides babel with an `undefined` variable and crashes the build. See error below.

edit: Downgrading to parcel 1 and using the `--experimental-scope-hoisting` works and produce the following:

```bash
❯ yarn build --experimental-scope-hoisting
yarn run v1.22.4
$ parcel build src/index.html --experimental-scope-hoisting
✨  Built in 1.76s.

dist/src.da3d517b.js    7.67 KB    1.33s
dist/index.html           248 B    595ms
Done in 2.45s.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
{
  "name": "parcel2",
  "main": "dist/index.html",
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html",
    "build:no-scope": "parcel build src/index.html --no-scope-hoist"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  },
  "dependencies": {
    "solid-js": "^0.18.14"
  }
}
```

## 🤔 Expected Behavior

Compile without error or pointing out what the error is.

## 😯 Current Behavior

Following the script above: `yarn dev` works, `yarn build:no-scope` works but produce a larger than expected bundle (I think it doesn't do any tree shaking) and `yarn build` crash with the following error:

```bash
❯ yarn build
yarn run v1.22.4
$ parcel build src/index.html
🚨 Build failed.
@parcel/packager-js: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got undefined
TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got undefined
    at Object.validate (/home/alexandre/Lab/parcel2/node_modules/@babel/types/lib/definitions/utils.js:132:11)
    at validateField (/home/alexandre/Lab/parcel2/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/home/alexandre/Lab/parcel2/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/home/alexandre/Lab/parcel2/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/home/alexandre/Lab/parcel2/node_modules/@babel/traverse/lib/path/removal.js:57:10)
    at NodePath.remove (/home/alexandre/Lab/parcel2/node_modules/@babel/traverse/lib/path/removal.js:36:8)
    at pathRemove (/home/alexandre/Lab/parcel2/node_modules/@parcel/scope-hoisting/lib/utils.js:125:8)
    at remove (/home/alexandre/Lab/parcel2/node_modules/@parcel/scope-hoisting/lib/shake.js:183:29)
    at /home/alexandre/Lab/parcel2/node_modules/@parcel/scope-hoisting/lib/shake.js:39:79
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.
```

In comparison, here's the build with the `--no-scope-hoist` flag:

```bash
❯ yarn build:no-scope
yarn run v1.22.4
$ parcel build src/index.html --no-scope-hoist
✨ Built in 2.71s

dist/index.html                252 B    1.26s
dist/parcel2.b7235cef.js    19.16 KB    1.26s
Done in 3.31s.
```

## 💁 Possible Solution

I dug the source of the error a bit but couldn't really pin point what's going on. It comes from the scope hoisting mechanism which you can observe from the stack trace above.

## 🔦 Context

I'd like to use parcel 2 as my main (and only) bundler for all my project going forward. [solid-js]() has a small community and there are no official favorite solution to build projects. I believe parcel can be that tool and I'd like to push it as much as I can to grow the community.

## 💻 Code Sample

You can find a very small reproduction here: [https://github.com/amoutonbrady/parcel2-solid-scope-hoist-reproduction](https://github.com/amoutonbrady/parcel2-solid-scope-hoist-reproduction)

```bash
git clone https://github.com/amoutonbrady/parcel2-solid-scope-hoist-reproduction
cd parcel2-solid-scope-hoist-reproduction
yarn # or npm install
yarn dev # should work flawlessly
yarn build # fail with above error
yarn buld:no-scope # should work but produce bigger bundle
```

## 🌍 Your Environment

| Software         | Version(s) |
| ------------------- | ------------- |
| Parcel           | ^2.0.0-beta.1 (nightly doesn't help either) |
| Node             | v14.8.0 |
| npm/Yarn         | yarn: 1.22.4 ; npm: 6.14.7 |
| Operating System | Linux (but reproduced on Windows 10 as well) |

**Comment by rturnq** [comment]
After also running into this issue, I dug into it a bit and ended up debugging my parcel build. I was able to determine the exception was being caused by this line of code from the `solid-js` package: https://github.com/ryansolid/solid/blob/df4111f7ed1c190b9c7e62b077d6204b86d1e11f/packages/solid/src/reactive/scheduler.ts#L127

From what I can tell, that line is incrementing a global variable and is part of a function `requestCallback` which is exported by the library but is unlikely for someone to import (it is undocumented atm). For whatever reason, when the scope hoisting/tree shaking process operates on this expression within an object property assignment it breaks. If I remove the `++` and increment the variable after the object creation, everything works. This must just be some corner-case.

I don't think this issue is specific to solid-js, I imagine this case will crop up elsewhere.

@amoutonbrady If you include `requestCallback` in your code in such a way that it doesn't get tree-shaken, you should be able to build with scope hoisting enabled. For example
```js
import { requestCallback } from 'solid-js';
requestCallback(() => {});
```
This does appear to add a little over a 1KB which otherwise should get removed but it is better than the ~20KB extra when scope hoisting is disabled.
