### ISSUE TITLE
Changing `--target ...` CLI flag doesn't clear cache

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5210]
# 🐛 bug report

Running with `--target x` and then with `--target y` doesn't do anything because we completely reuse the cache.

**Comment by devongovett** [comment]
We could add it to the cache key here: https://github.com/parcel-bundler/parcel/blob/7717e2547f510c89ea57bbfec62147bfb912ba49/packages/core/core/src/AssetGraphBuilder.js#L96

But that would invalidate the entire cache rather than reusing the parts we can. Should be covered when we add an OptionsRequest to the graph.

**Comment by jjenzz** [comment]
We've been experiencing cases where old versions of our packages are bundled after we've made changes too. I'm not sure if it is related but thought I'd raise just in case.
