### ISSUE TITLE
Not using "main" and other common package.json fields by default

### ISSUE THREAD

**Issue by samsch** [parcel-bundler/parcel#5243]
# 💬 RFC

The main / module / browser fields in package.json should be ignored by default.

Using them could be behind a cli flag, or require the "targets" field in package.json.

## 🔦 Context

Common setup:

```bash
npm init -y
npm i parcel@next
npm i <project packages>
# write basic entrypoint files, including possibly index.js in root
npx parcel watch ./src/entryfile.js --dist-dir ./dist --no-autoinstall
```
Running this I would expect to build entryfile.js and output it in /dist, but since `npm init` adds a `"main"` field, Parcel surprisingly ignores `--dist-dir`.

Having this surprising functionality makes it more difficult to guide new users through setup, and requires inspecting package.json to ensure it doesn't have a common (ignored) field just for regular operation.

**Comment by mischnic** [comment]
> but since npm init adds a "main" field

`yarn add ...` automatically creates a package.json file, so I've never run into this myself.
Ideally `npm init` wouldn't add a `"main"` field (which is unused anyway for most projects which aren't libraries - and for libraries it's probably the wrong path anyway - furthermore Node actually defaults to `index.js` if no `"main"` field exists, so this is really unnecessary)

**Comment by samsch** [comment]
I really think this is a problem on Parcel's side though.

Another usecase I'm actually hitting right now: I've got a repo that I intend to publish as a library package and using "main" is more suitable than the default index.js fallback. But I also use Parcel in the package repo itself for testing and development for code that's not even directly related to the "main" entrypoint.

It's too easy to accidentally configure Parcel with "main".

It seems like compiling libraries where "main"/"module"/"browser" make sense related to Parcel is a pretty uncommon task. Most libraries don't need to be bundled. The common case for Parcel is non-library projects I would assume. To me, it makes more sense to have using standard "main"/"module"/"browser" fields for a non-standard task be opt-in instead of opt out.

**Comment by fregante** [comment]
Using `main` as a default may be ok; The problem generally steams from generic errors that force you to google "why isn't dist dir working." If the error was "File `index.js` defined in package.json’s `main` key not found" it would be a little easier to proceed.

**Comment by mischnic** [comment]
> File index.js defined in package.json’s main key not found

But the point is that `main` is the *output* (the bundle), not the *input* (the source file). 

And npm always adding the field when most projects don't actually add the file afterwards doesn't make it better...

**Comment by fregante** [comment]
D'oh, that's right. Then I think `--dist-dir` should override it regardless.

**Comment by samsch** [comment]
Recent issues which wouldn't happen with this change:
https://github.com/parcel-bundler/parcel/issues/6046
https://github.com/parcel-bundler/parcel/issues/6013
https://github.com/parcel-bundler/parcel/issues/5996

Also helps avoid the case fixed here:
https://github.com/parcel-bundler/parcel/pull/5941

**Comment by adjenks** [comment]
@samsch I think this is related too: https://github.com/parcel-bundler/parcel/issues/5785

**Comment by mischnic** [comment]
Somewhat related: https://github.com/parcel-bundler/parcel/issues/6110

**Comment by adjenks** [comment]
Related discussion I had started: https://github.com/parcel-bundler/parcel/discussions/6147

**Comment by devongovett** [comment]
I don't believe we plan on changing this. "main"/"module"/"browser"/"types" are meant for building libraries, which will be consumed by other tools (e.g. node or another bundler) later. It would be expected that if you built the library with Parcel you'd want other tools to consume the _output_ from Parcel rather than the original source code (which might be written in another language like TypeScript). The "source" field can be used to configure source code.

We've improved the diagnostics around this so that the error messages are more helpful, and prevent you from doing dangerous things. For example, the above fields only allow certain file extensions, and we prevent you from overwriting your source code as of #5941. Hopefully this is enough to prevent confusion.

**Comment by haberdashPI** [comment]
This may perhaps be more of a question, but I'm running into a similar problem and I don't see how to do it because of this limitation.

In my use case I want to use parcel to build the docs (and the docs *only*) of my package. The package.json naturally sets a different value for `"maine"` because it's for the source not the docs. What's the best way to handle this situation?

**Comment by mischnic** [comment]
See https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser:

```json
{
  "main": "unrelated.js",
  "targets": {
    "main": false
  }
}
```
