### ISSUE TITLE
--hmr-host is not available

### ISSUE THREAD

**Issue by ranisalt** [parcel-bundler/parcel#5268]
# 🐛 bug report

I'm trying to configure the host that hot module replacement responds, since I am developing in a remote machine but accessing from local browser.

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero configuration

## 🤔 Expected Behavior

Running `parcel serve ... --host 0.0.0.0 --hot-host 12.34.56.78` should make the hot module replacement connect to the socket in `wss://12.34.56.78:1234` instead of `wss://127.0.0.1:1234` or `wss://0.0.0.0:1234`

## 😯 Current Behavior

It errors with
```
error: unknown option '--hot-host'
```

Even if prepending `--hot` it does not work:
```
error: unknown option '--hot-host'
```

However, the README states those flags exist, and I see that [`HMRRuntime.js`](https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/hmr/src/HMRRuntime.js) tries to use these. I assume that `--hot-port` will also not work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0-nightly.429
| Node             | v14.12.0
| npm/Yarn         | v1.22.5
| Operating System | Ubuntu 20.04.1 LTS

**Comment by mischnic** [comment]
`--hmr-port` does exist (though it's not listed on https://v2.parceljs.org/features/cli/#parameters-related-to-the-dev-server%2Fwatch-mode-(serve-and-watch) ):

https://github.com/parcel-bundler/parcel/blob/296bc57f63c581d38bbda27ed9ebb895a67127e2/packages/core/parcel/src/cli.js#L101

Looks like `--hmr-host` isn't exposed in the CLI...

**Comment by ranisalt** [comment]
I didn't know about `serve --help`, I always resorted to the README/website :laughing: will try to do something

**Comment by nextlogic-ono** [comment]
I agree it needs `--hmr-host`.

I'm running parcel behind a reverse proxy of another host, so specifying `--host` as the exposed host will fail saying that it cannot bind to that IP address.

What would work is the host for binding should be different from the host that parcel connects to from the browser.

Also, 
`parcel watch --host 127.0.0.1`
doesn't work as it still keeps on listening to all the interfaces as I assumed this will change the IP it binds to according to the documentation.

Ideally, 
`parcel watch --host 127.0.0.1 --hmr-host wss://host.browser.connects.to:443`
would make parcel listen to `127.0.0.1` while the browser connects to `wss://host.browser.connects.to:443` with its HMR.
(I'm specifying the full URL, since it implies even though parcel is running without https locally, the exposed reverse proxy host has ssl termination and needs to be connected with https. Perhaps `--hmr-connect` would be a better name.)

**Comment by remotezygote** [comment]
The above PR should satisfy this issue for closing.

**Comment by nextlogic-ono** [comment]
It's not handling the issue of using a different port by the example I posted above by sharing the port the hmr listens to and the port the browser connects to.

**Comment by remotezygote** [comment]
Does https://github.com/parcel-bundler/parcel/pull/8137 help?

**Comment by nextlogic-ono** [comment]
> Does #8137 help?

Yes, sorry missed about 8137.

**Comment by 101arrowz** [comment]
> It's not handling the issue of using a different port by the example I posted above by sharing the port the hmr listens to and the port the browser connects to.

Do you need the HMR port and serving port to be different? Check if https://github.com/parcel-bundler/parcel/pull/8137#issuecomment-1138832303 fixes your issue.
