### ISSUE TITLE
HMR doesn't work when use js annotation?

### ISSUE THREAD

**Issue by MOONLIGHTV** [parcel-bundler/parcel#545]
index.js link to index.html
`document.querySelector('.logo').textContent='parcel';`

Then run 

> parcel index.html

if I change the index.js like this:
`document.querySelector('.logo').textContent='parcel-111';`
It works good,but if I annotated js code like this:
`//document.querySelector('.logo').textContent='parcel-111';`

Nothing happened.

**Comment by DeMoorJasper** [comment]
So u are having the issue that it doesn't remove to textcontent if u comment it out?

This is sort of expected behaviour, don't know if the current behaviour should be changed however

**Comment by devongovett** [comment]
When an HMR update comes in, Parcel replaces the existing module with the new code, and re-executes it. There is no way for it to know what happened before in order to "undo" whatever side effects it may have had. However, you can do that yourself. For example, the following clears the text content right before the old module is disposed. Then the new module will execute afterward.

```javascript
if (module.hot) {
  module.hot.dispose(function () {
    document.querySelector('.logo').textContent = '';
  });
}
```
