### ISSUE TITLE
No packager found for .xml

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#5472]
# 🐛 bug report

This is an odd one. Sorry for the weird error description.

My build is failing with the following error:

![Screen Shot 2020-12-14 at 11 54 35](https://user-images.githubusercontent.com/234957/102079080-ee5f9e80-3e03-11eb-9258-2f8db0877a70.png)

Very non-descriptive :-/

I was able to reduce the index.html to the following:

```html
<!DOCTYPE html>
<meta charset="utf-8" />
<body>
  <footer>
    <a href="/index.xml" rel="me">
      rss
    </a>
  </footer>
</body>
```

Here is `index.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>surma.dev</title>
  <link href="https://staging.surma.dev/index.xml" rel="self"/>
  <link href="https://staging.surma.dev"/>
  <updated>2020-01-27T00:00:00.000Z</updated>
  <id>https://staging.surma.dev</id>
  <author>
    <name>Das Surma</name>
    <email>surma@surma.link</email>
  </author>
  
  <entry>
    <title>Case study: Moving a Three.js-based WebXR app off-main-thread</title>
    <link href="https://staging.surma.dev/things/omt-for-three-xr/"/>
    <updated>2020-01-27T00:00:00.000Z</updated>
    <id>https://staging.surma.dev/things/omt-for-three-xr/</id>
    <content type="html">lol</content>
</feed>
```

If I remove the `<a>` tag, it builds fine. However, if I isolate those two files to a separate folder, it builds fine even _with_ the `<a>` tag. I delete `.parcel-cache`, but it doesn’t change anything.

Any idea what could be causing this?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v14.9.0
| npm/Yarn         | npm@6.14.9
| Operating System | MacOS 10.15.7

**Comment by mischnic** [comment]
Seems to work for me (both beta1 & nightly): https://github.com/mischnic/parcel-issue-5472

**Comment by surma** [comment]
That's what i mean. It works if I copy them to a new folder. But it doesn't in the context of my projects, despite me deleting .parcel-cache and all other files in the build folder.

Is there any other cache folders i could try deleting?

**Comment by mischnic** [comment]
Sorry, I missed that line.

The only cache is .parcel-cache in the project root (= where the lockfile or .git is). Do you have any configuration files that could affect this?

**Comment by mischnic** [comment]
If this is a public repo, you could also push a branch so that I can reproduce this.

**Comment by surma** [comment]
Thanks for offering to help, @mischnic! Really appreciate it.

Pushed a tag: https://github.com/surma/surma.dev/releases/tag/parcel-issue-5472
Run `npm run build` to get the error.

Eleventy populates `.tmp`, and parcel is supposed to productionize `.tmp`. There’s quite a lot of files in `.tmp`, but even if I remove all other files and only leave the files as listed above, the error remains.

**Comment by mischnic** [comment]
This star: https://github.com/parcel-bundler/parcel/blob/ed6b43b673071038fccc637dac50fb9f0a15c7e3/packages/configs/default/index.json#L65

is glob matched against `'...../surma.dev/dist/.tmp.HASH_REF_64af61dcb924af7cbdaad9f95a5133fb.xml'`. But this doesn't include dot files..

```js
import micromatch from 'micromatch';

// false
console.log(
  micromatch.isMatch(
    '/surma.dev/dist/.tmp.HASH_REF_64af61dcb924af7cbdaad9f95a5133fb.xml',
    '*'
  )
);
```

It should be true in this case, which is why Parcel didn't find a packager...

With more recent nightly versions, the xml file is called `index.html` in your case.  But this could still happen...

**Comment by mischnic** [comment]
So a reproduction would be
```
{
	"main": ".output.js",
	"scripts": {
		"build": "parcel build index.js"
	},
	"dependencies": {
		"@babel/core": "^7.12.10"
	}
}
```
and an empty `index.js`.

**Comment by surma** [comment]
Should `dist` (or rather: The output folder) be excluded from any matches?

**Comment by mischnic** [comment]
No, at this point, Parcel has determined that there should be a bundle at the specified path containing some assets. It tries to determine which packager plugin should handle the `Set<Asset> => Bundle` translation based on the bundle filepath + type.

Globs exclude dotfiles because this is usually what you want when invoking `cp * ../something`, but in this case we don't care if it's a dotfile or not (because either the user or a namer plugin specified this name, see https://github.com/parcel-bundler/parcel/issues/5474).
