### ISSUE TITLE
Vue warning: compileTemplate now requires the `id` option.

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5629]
# 🐛 bug report

There's a warning when running the integration tests (and probably also when actually using the Vue transformer in a project):

```
[@vue/compiler-sfc] compileTemplate now requires the `id` option.`.
```

## Possible solution

Looking at 
https://github.com/vuejs/vue-next/blob/13fc8ff9dd7007e4ef7d2f0b6e5c973013ccc8b8/packages/compiler-sfc/src/compileTemplate.ts#L189-L212

I would say this should instead use `id` and not `compilerOptions.shortId`?
https://github.com/parcel-bundler/parcel/blob/6e81ebff219f13e2049638923b8819f0a63d40be/packages/transformers/vue/src/VueTransformer.js#L252-L254

But I don't actually know what `id` does...

cc @101arrowz

**Comment by 101arrowz** [comment]
Vue has a feature called scoped CSS that is like CSS modules but easier to use. To make it work, it applies styles to elements that match your provided selector AND have the scope ID as a `data-` attribute. Basically, each element gets a `data-v-abcdef` attribute and scoped CSS targets `.your-selector[data-v-abcdef] { ... }`.

Vue must have changed their API to require the `id` field instead of `scopeId`. Trivial to change: replace `scopeId` with `id`. Optionally remove the `data-v` prefix, since it's removed by Vue anyway.

**Comment by cemenson** [comment]
I'm happy to do this if that's ok?
