### ISSUE TITLE
Proxy: Error in browser shows original not target host.

### ISSUE THREAD

**Issue by jraedisch** [parcel-bundler/parcel#5725]
Version: @parcel/core@2.0.0-nightly.554+c50e6555

TL;DR

When proxy target is not running, the error message in the browser shows the origin, not the target host, which is misleading.

Long:

I have a .proxyrc.json

```
{
  "/api": {
    "target": "http://foobar/",
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```

When target is not running, I get the err in browser:

`Error occured while trying to proxy to: localhost/upload`

when opening 

`http://localhost/api/upload`

which is misleading. I would prefer

`Error occured while trying to proxy to: foobar/upload`

Tracked the error down to https://github.com/chimurai/http-proxy-middleware/blob/master/src/handlers.ts but do not know, what to change for a PR, and for which project.

**Comment by mischnic** [comment]
We simply use that package as a dependency
https://github.com/parcel-bundler/parcel/blob/b70830daef0c5673c4974c8f7de72c4ec2a7517a/packages/reporters/dev-server/src/Server.js#L29

so that would need to be changed in https://github.com/chimurai/http-proxy-middleware. I'm not familiar with the code either, so you'd have to ask someone from that project.

**Comment by jraedisch** [comment]
As proposed, I created an issue here: https://github.com/chimurai/http-proxy-middleware/issues/496
