### ISSUE TITLE
Making a require conditional requires clearing the cache

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5833]
# 🐛 bug report

Wrapping an existing dependency in an if statement doesn't wrap the dependency (with a cached build).

## 💁 Possible Solution

`dep.meta.shouldWrap` is overwritten when reading the dependency from cache?

## 💻 Code Sample

```js
// if (Date.now() < 0) {
	const x = require("./something");

	console.log(x);
// }
```

1. `parcel build index.js`
2. Comment in the first and last line
3. `parcel build index.js`. `something` is still being executed. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 560d06051b36b3f5703848bba801996f351c4ab4

**Comment by devongovett** [comment]
Still an issue?

**Comment by mischnic** [comment]
Yes, output of step 1:
```js
var $30c2bb3b4d10773c$exports = {};
console.log("!");


console.log($30c2bb3b4d10773c$exports); // }
```

output of step 2 (the imported asset isn't wrapped):
```js
var $30c2bb3b4d10773c$exports = {};
console.log("!");


if (Date.now() < 0) {
    const x = $30c2bb3b4d10773c$exports;
    console.log(x);
}
```

**Comment by devongovett** [comment]
I think this is the problem: https://github.com/parcel-bundler/parcel/blob/413a09364646811f6067be80065c15d7b6270236/packages/core/core/src/AssetGraph.js#L468-L471

Looks like it was added in https://github.com/parcel-bundler/parcel/commit/3edfae01ba3bbecc0e9b9f642c188b27b7d6e301

I guess it needs to somehow merge the meta properties added by the resolver with the properties returned by the transformer? We'd need to store these separately I suppose so that either request can re-run without the other re-running and the result should be the same. 🤔
