### ISSUE TITLE
Reduce the number of Parcel dependencies that are added to package.json (a.k.a dependency hell)

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5875]
### Summary

New Parcel versions add many dependencies to the package.json (a.k.a dependency hell).

# 🐛 bug report

The reason that I used to use Parcel over other bundlers such as Rollup and Webpack was that I didn't need to maintain a billion packages to be able to build my projects. 

But in the recent versions Parcel also has removed this advantage by adding all the small packages to the top-level package.json 

Just see how many packages I need to maintain for a single project build:
```diff
+    "@parcel/babel-plugin-transform-runtime": "^2.0.0-nightly.2222",
+    "@parcel/babel-preset-env": "^2.0.0-nightly.600",
+    "@parcel/optimizer-cssnano": "^2.0.0-nightly.600",
+    "@parcel/optimizer-htmlnano": "^2.0.0-nightly.600",
+    "@parcel/packager-css": "^2.0.0-nightly.600",
+    "@parcel/packager-ts": "^2.0.0-nightly.600",
+    "@parcel/transformer-css": "^2.0.0-nightly.600",
+    "@parcel/transformer-less": "^2.0.0-nightly.600",
+    "@parcel/transformer-postcss": "^2.0.0-nightly.600",
+    "@parcel/transformer-typescript-types": "^2.0.0-nightly.600",
+    "@parcel/validator-typescript": "^2.0.0-nightly.600",
```

### Comparison of Parcel with other build systems:

Compare this to other languages and see how maintaining a JavaScript project is harder!

- `C++`: the only thing I need to install to be able to build C++ projects is `clang`.
- `Rust`: I just need to have `rustup` and `cargo` installed.
- `Go`: I just need to have `go` installed
- ...

## 🤔 Expected Behavior

Avoid adding all the internal dependencies to package.json 

## 😯 Current Behavior

See the above

## 💁 Possible Solution

Manage the needed dependencies internally

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.598
| Node             | N/A
| npm/Yarn         | N/A
| Operating System | N/A

**Comment by devongovett** [comment]
This is not a very nicely written issue. Please be more considerate in the future.

I think we cannot win here. Many people complain about the node_modules install size of Parcel. You are complaining that not enough is built in. Everyone wants just what they use and no more, but the only way to actually achieve this is to install the necessary plugins on demand. Yes you see a few more dependencies in your package.json, but upgrading is no more difficult (yarn upgrade --scope @parcel).

Overall, this is far more extensible. As we add support for more languages to Parcel, no one pays the cost unless they use them. If we included everything by default Parcel would just keep getting bigger and bigger with no bound. We try to include the most commonly used plugins by default (the JS pipeline), but perhaps more presets (eg JS library, React app, Vue app, etc.) would be useful?

**Comment by folknor** [comment]
I'd rather have an empty package.json and 200 megabytes in node_modules that I don't use. I can't imagine a situation where I'd care about downloading excessive node_modules. But I'm sure others can, and do :-)

In any case, `many people` is what people tend to say when they can't actually cite or quote sources, and over time their impression has grown to this conclusion by random off-hand comments.

Has there been a survey of what users prefer?

Finally, if there wasn't an RFC here, I'd never have said anything - and certainly I'd never have opened this ticket. It's up to the maintainers what they want to do, and I am uncomfortable voicing my opinion at all.

**Comment by aminya** [comment]
> This is not a very nicely written issue. Please be more considerate in the future.

Sorry if it read badly. I have edited the text to soften the language.

**Comment by aminya** [comment]
> I think we cannot win here. Many people complain about the node_modules install size of Parcel. You are complaining that not enough is built in. Everyone wants just what they use and no more, but the only way to actually achieve this is to install the necessary plugins on demand. Yes you see a few more dependencies in your package.json, but upgrading is no more difficult (yarn upgrade --scope @parcel).

The node_modules size issue is already fixed by [`pnpm`](https://pnpm.js.org/) and other package managers. We should the wrong solution for another problem. Pnpm uses symlinks to share the dependencies between different projects. That means only one copy of a file is kept.

**Comment by mischnic** [comment]
> The node_modules size issue is already fixed by pnpm and other package managers. We should the wrong solution for another problem. Pnpm uses symlinks to share the dependencies between different projects. That means only one copy of a file is kept.

pnpm (and maybe Yarn 2 with PnP) aren't that widely spread though. 

> Currently, developing projects in other languages is easier! Clang builds C++, C, Fortran, and it includes clang-tidy, clang-format, etc. You install it once; you enjoy it forever.

The big difference is that they are installed globally, not per project. Which isn't the norm in the npm ecosystem.

> If really the size is an issue, why not use auto-install? Parcel already has a great internal auto-install. If you really want, an internal parcel-dependencies.json file can be kept to install the dependencies on-demand.

I don't understand. This is exactly what we did and lead to this issue.

Or do you mean installing the dependencies but not adding them to `package.json`? That wouldn't really be compatible with npm/Yarn/...

**Comment by devongovett** [comment]
> The node_modules size issue is already fixed by pnpm 

That's not really solving the problem. Sure it deduplicates, but why even pay the install/build cost in the first place? Some modules (e.g. sharp for image processing) are very large and slow to build. Why should we install that if you don't use it? What about more "obscure" languages like Elm or CoffeeScript? Why should we install their entire compiler build chain when the majority of projects don't use them.

In addition, many companies require developers to audit their dependencies for security purposes. The more dependencies you have the harder this gets, especially over time, as you have to manage dependencies you don't even use. You start getting tons of warnings and have to upgrade stuff just because of that. It's really annoying.

In general size is not the main concern. It's build performance, especially in CI. Installing large projects can take several minutes. See https://twitter.com/swyx/status/1290410811802804226 for a comparison. I should note, that I also didn't see the problem at first: https://twitter.com/devongovett/status/1290675672667402241. However, the install time (especially for CI) and security aspects have convinced me, especially if we can still keep things easy to use with auto install.

> If really the size is an issue, why not use auto-install?

I'm confused by this comment. That is exactly what we are doing! We are trying to get the best of both worlds. Yes, the base Parcel install doesn't include some plugins, but they are auto installed on demand. This only happens once, the first time they are loaded. After that they get installed by your package manager when doing a fresh install of your app because they are in your package.json/lock file. This keeps the number of dependencies low, but also keeps Parcel easy to use because all the build dependencies you need are installed on demand.

I should also note that this is not that different from what we did before. For example, `@babel/core`, `postcss`, and `less` were always dependencies of your project. The difference is now the Parcel plugin is a dependency as well (or instead depending on whether the compiler it uses is a peer dependency).

I'm not really sure what your complaint is here. Is it just that you don't like seeing the dependencies in your package.json? That seems like a fairly minor complaint compared to the benefits of the approach I just outlined.

**Comment by aminya** [comment]
> pnpm (and maybe Yarn 2 with PnP) aren't that widely spread though.
> The big difference is that they are installed globally, not per project. Which isn't the norm in the npm ecosystem.

That's their problem? If someone insists on using plain package managers, they should realize that the node_modulkes size is an issue. They can't have all the good things at once. Either use a better package manager or deal with the size.

This is very different problem. Asking the developers to contribute to the dependency hell is not the solution for node_module size. The solution is to stop using bad package managers.

> Or do you mean installing the dependencies but not adding them to package.json? That wouldn't really be compatible with npm/Yarn/...

Yes, installing the packages without adding them to package.json. These dependencies are like Parcel's dependencies, but they are added on demand.

**Comment by aminya** [comment]
> I'm not really sure what your complaint is here. Is it just that you don't like seeing the dependencies in your package.json? That seems like a fairly minor complaint compared to the benefits of the approach I just outlined.

That is my issue. I don't want to maintain what Parcel uses internally, like how I don't care what dependencies LLVM, go, Rust, etc, are using.

**Comment by devongovett** [comment]
I don't think the comparison to those other tools is appropriate since they are mostly meant to handle a single language. It's not like you're writing a plugin for the Rust compiler to also handle Java.

I can understand the initial aversion to seeing more dependencies, but these really _are_ your dependencies. They were just hidden before. Listing them in your package.json allows you to control their versions independently.

This may come in handy in the future. For example, when Babel 8 comes out, you might not be ready to switch right away as it may contain breaking changes. However, you may still want other unrelated Parcel bug fixes or features in the meantime. If the dependency were in Parcel itself, you would be blocked and need to upgrade Babel before you could upgrade Parcel. In fact, whenever any plugin released a major version, we'd also need to bump the major version of Parcel. When it's in your project, you can upgrade Parcel but keep Babel on an older version, and the Parcel version doesn't depend on plugin versions.

Fewer dependencies in your package.json may seem simpler at first, but it will cause huge problems down the road as you maintain your project and upgrade your dependencies over time.

Luckily, upgrading all Parcel dependencies at once is usually pretty easy, e.g. `yarn upgrade --scope @parcel`. If you want, you can also create a config package that _does_ include the dependencies you want, and use it in your projects in place of the default config.

**Comment by aminya** [comment]
> If you want, you can also create a config package that does include the dependencies you want, and use it in your projects in place of the default config.

Yeah, it seems making a fork of Parcel is the way to go.

I am still getting hurt by #5671 and #5617. So, I have more reasons to create a fork to provide a zero-configuration, zero-maintenance build tool.

**Comment by devongovett** [comment]
I mean, you don't have to fork all of Parcel. You can just create a config like the default config, including just the plugins you want. Then you can specify it in your project like this:

```
parcel build . --config parcel-config-XYZ
```

Or by extending it in a local .parcelrc.

**Comment by devongovett** [comment]
What if we added the HTML and CSS pipelines as default installed dependencies but kept non web-standard languages (eg sass, coffeescript, etc.) as auto installed on demand? Do you think that would alleviate this issue for you?

**Comment by aminya** [comment]
Yes! That makes the situation better at least for the majority of the developers. I think that Typescript is also a standard these days, so having TypeScript support would be nice.
