### ISSUE TITLE
Plugin development is a bit difficult locally

### ISSUE THREAD

**Issue by jtenner** [parcel-bundler/parcel#590]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🙋 Support `npm link`ed plugins!

### 🎛 Configuration (.babelrc, package.json, cli command)

The configuration isn't important here, but because I can't link a plugin, I can't test to see if it works before submitting my package to npm.

### 🤔 Expected Behavior

Well, by the description of the problem, it should be supported, I would think! 

### 😯 Current Behavior

It currently does not support linked plugins.

### 💁 Possible Solution

I haven't enough information on how `npm link` works, but it would be great to learn, since I'm trying to design something similar in nature to parcel (not a js packager).

### 🔦 Context

I am trying to accomplish creating a plugin locally so that I can start to help parcel support different sorts of file types.

### 💻 Code Sample

This is not necessary.

### 🌍 Your Environment

Windows 10, latest node, latest npm. I do not use yarn personally.

**Comment by elsassph** [comment]
I had the same problem - there are different ways to handle that:

1. Using `npm link`

- create a test project,
- install your local plugin (this copies your plugin in your test project):

        npm install C:\path\to\plugin

- use `npm link` to replace the installed copy by a symlink to your plugin sources:

        # in plugin directory
        npm link
        # in your test project directory
        npm link parcel-plugin-myplugin

Now you can edit your plugin sources.

**Comment by elsassph** [comment]
2. Alternative option that I'm using because I'm hacking parceljs:

In your sandbox project, create 2 scripts:

```javascript
// start.js
const Bundler = require('parcel-bundler');

process.env.NODE_ENV = process.env.NODE_ENV || 'development';

// you may be messing quite a bit in a new plugin so you may want to add error capture
process.on('unhandledRejection', (reason, p) => {
    console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
});

// manually set up the bundler
const bundler = new Bundler('./src/index.html');

bundler.addPackager('ext', require.resolve('./MyPackager'));
bundler.addAssetType('ext', require.resolve('./MyAsset'));

bundler.serve(1234, false);
```

**Comment by jtenner** [comment]
I used npm link on a local version of `parcel-bundler` it worked nicely. Closing because I managed to figure out how to test it without it being a dependency of the project. I still think `npm link plugin` should work though.

**Comment by mischnic** [comment]
Parcel gets the list of dependencies in package.json and loads listed plugins. Therefore plugins linked to node_modules but not listed in package.json won't get loaded. My workaround is: linking the plugin into node_modules and then manually adding it to the package file:
```json
"dependencies":{
  "parcel-plugin-emscripten": "something"
}
```
(Just be sure not to run `yarn` without removing this line, because technically it's not a valid version.)

**Comment by mischnic** [comment]
What about specifying a plugin linked inside node_modules with a cli argument?
`parcel --plugin myplugin src/index.html` for`parcel-plugin-myplugin`.

**Comment by DeMoorJasper** [comment]
I'm not sure if this has been resolved?"

**Comment by dobesv** [comment]
It seems like @jtenner would have to say for sure, but there have been solutions presented such as using `npm link` or installing using `file:`.

**Comment by elsassph** [comment]
I think a proper answer should be to have a wiki page describing the dev process options as evoked here.

**Comment by jtenner** [comment]
I didn't mean to hold this open. Installing the package from the github repo was enough to fix the issue.

**Comment by ozanmuyes** [comment]
As @elsassph pointed out using [`npm link`](https://docs.npmjs.com/cli/link.html) solves the issue. But I think it's worth to mention the issue is **not** Parcel related.

Although `npm link` page describes what it is and gives an example, here is the process in a nutshell;

1. Create your local plugin directory
  i.e. `mkdir parcel-plugin-yourplugin && cd parcel-plugin-yourplugin && npm init -y` and then write the plugin
2. Run `npm link` command on the **plugin directory** first
  This creates global link on your development environment, so you don't have to push your plugin to npm
3. Navigate to your test project directory (which depends/dev-depends on `parcel-bundler`)
4. Run `npm link parcel-plugin-yourplugin`
  Please note the plugin name, you have to write it this time as if you were downloading it from npm

After those steps any (file) change on 'parcel-plugin-yourplugin' directory will be reflected on you test projects 'node_modules' directory, this is simply because your plugin directory in the test project's 'node_modules' is a symbolic link.

**Comment by SalvatorePreviti** [comment]
i wrote this supersimple package that seems to solve the problem for my case - https://github.com/SalvatorePreviti/parcel-plugin-local-plugins - the only limitation of course is that if you change the plugin source code you need to restart parcel.
