### ISSUE TITLE
`serviceWorker.register(new URL(...))` generates failing code

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6103]
# 🐛 bug report

See https://github.com/parcel-bundler/parcel/discussions/6098

## Code sample

index.html: `<script src="index.js"></script>`
index.js:  `navigator.serviceWorker.register(new URL("./sw.js", import.meta.url));`
sw.js: `console.log("sw")`

## Current behaviour

`Uncaught ReferenceError: parcelRequire427e is not defined`

## Expected behaviour

Works...

Interestingly, `navigator.serviceWorker.register("./sw.js");` works correctly.

**Comment by devongovett** [comment]
Appears to work on the SWC branch...

**Comment by loynoir** [comment]
Same issue. Got very dirty workaround
```ts
class serviceWorkerWrapper {
    constructor(x:URL) {
        navigator.serviceWorker.register(x);
    }
}

const Worker_backup = Worker;
window['Work' + 'er'] = serviceWorkerWrapper;
const sw = new Worker(new URL('./foobar/sw.js', import.meta.url));
window['Work' + 'er'] = Worker_backup;
```


Have a few questions.

The commonjs alike way 
1. kindof work 
2. generated file is not polluted by wrapper.
3. BUT might not generate file at top most.

So, are there any way to generate top most file?
```js
const sw = navigator.serviceWorker.register('./foo/sw.js')
```

The esm alike way
1. able to be top most
2. BUT seems got damage from wars among some wrapper and tree shaking?

So, are there any way to avoid wrapping file, if user explicit specify? 
```js
// BOOM!: parcelRequire not defined
const sw = navigator.serviceWorker.register(new URL('./foo/sw.js', import.meta.url))
```

**Comment by mischnic** [comment]
I don't understand your problem.

You should just use `navigator.serviceWorker.register('./foo/sw.js')` until the version with `new URL` is fixed

**Comment by loynoir** [comment]
Sorry, day 1 on parcel. And my english is poor. Plus github newbee.
Sincerely apology :)

1. AST-ly `navigator.serviceWorker.register('./foo/sw.js')` 
Generate file like '/dist/foo/sw.js', **not topmost** so service worker scope is under '/foo'.
Unable to handler **topmost** **/bar** request, but only '/foo/bar' request.
But I want '/dist/sw.hash.js'. Able to handler topmost '/bar' request.

2. AST-ly `new Worker()` 
do **not inject code**, and generate **topmost** '/dist/worker.hash.js'.
And generated topmost '/dist/worker.hash.js' is excactly **same logic** as './foo/sw.js'

3. Because of logic same, and my need to make topmost scope.
I'm just using dirty workaround before official fix, which make ast parser trust is `new Worker` but actually do `navigator.serviceWorker.register`.
PS: very very very dirty workaround, but simple test seems working.

Besides, might fix `new URL` by picking some logic from `new Worker()`?

**Comment by devongovett** [comment]
Should be fixed in latest?

**Comment by mischnic** [comment]
With `<script src="index.js"></script>`: it works

With `<script type="module" src="index.js"></script>`, there's an invalid/unused `export {$d8cfa3f2d92ec355$exports as default};` in the serviceworker.

**Comment by devongovett** [comment]
I think that's related to #6454
