### ISSUE TITLE
 `yarn build-native` throws error

### ISSUE THREAD

**Issue by shawsourav** [parcel-bundler/parcel#6316]
# 🐛 bug report

On running `yarn build-native` in the parcel monorepo, I get an error stating

`error: failed to run custom build command for `ring v0.16.20``

## 🤔 Expected Behavior

This should work as expected and stated in https://github.com/shawsourav/parcel/blob/v2/CONTRIBUTING.md

## 😯 Current Behavior

Build fails

## 💁 Possible Solution

Not sure

## 🔦 Context

I was going through the Contributing page and this command `yarn build-native` didn't work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2
| Node             | 12.20.0
| npm/Yarn         | 6.14.0
| Operating System | Mac OS Catalina v10.15.7

**Comment by mischnic** [comment]
Does it work if you comment this out?

https://github.com/parcel-bundler/parcel/blob/daece49d003ba804bbdaa3a7ed3d6aaf446f166d/scripts/build-native.js#L46-L50

**Comment by shawsourav** [comment]
@mischnic Yeah that worked 😄  Wondering what was the issue here 🤔  Is it a config issue from my side or a bug?

**Comment by devongovett** [comment]
@gorakong @wbinnssmith did you figure this out?

**Comment by LironHazan** [comment]
@devongovett 
Hey, it happened to me as well few minutes ago,
Basically the panic was due to the environment variable locations

`thread 'main' panicked at 'failed to execute ["/Library/Developer/CommandLineTools/**Toolchains**/XcodeDefault.xctoolchain/usr/bin/clang"`

I debugged my xcodeDir and as you can see it doesn't include the **Toolchains** dir 

```
C02Y504VJHD3:CommandLineTools lironh$ pwd
/Library/Developer/CommandLineTools
C02Y504VJHD3:CommandLineTools lironh$ ls                                 
Library SDKs    usr
```

So I resolved it as follows:

```
  process.env.CC = `${xcodeDir}/usr/bin/clang`;
  process.env.CXX = `${xcodeDir}/usr/bin/clang++`;
```

And ring compiled successfully,
I'll open a PR with the fix and if that's ok (thanks for making Parcel btw - I love it :))
