### ISSUE TITLE
'node:' module prefix causes "Unknown pipeline: node" errors

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6402]
# 🐛 bug report

'Came upon this issue while trying to use the `gravatar-url` module. (issue originally reported here: https://github.com/sindresorhus/gravatar-url/issues/8)

This works...
```
$ cat /tmp/index.html
<script type="module">
  import crypto from 'crypto';
</script>

$ parcel /tmp/index.html
ℹ️ Server running at http://localhost:49267
✨ Built in 486ms
```

This does not ...
```
$ cat /tmp/index.html
<script type="module">
  import crypto from 'node:crypto';
</script>

$ parcel /tmp/index.html
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/core: Unknown pipeline: node.
/private/tmp/index.html:1:20
> 1 | <script type="module">
>   |                    ^^^^
  2 |   import crypto from 'node:crypto';
  3 | </script>
```

The only difference here is the 'node:'-prefix on the module name in the second example.  Per https://nodejs.org/api/esm.html#esm_node_imports, this is a valid import name since node@14 and has been back-ported to node@12.

## 🌍 Your Environment

```
$ envinfo

  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 252.34 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 7.15.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.2312 => 2.0.0-nightly.2312
    @parcel/packager-raw-url: 2.0.0-nightly.2312 => 2.0.0-nightly.2312
    @parcel/transformer-sass: 2.0.0-nightly.690 => 2.0.0-nightly.690
    @parcel/transformer-svg-react: 2.0.0-nightly.2312 => 2.0.0-nightly.2312
    @parcel/transformer-webmanifest: 2.0.0-nightly.2312 => 2.0.0-nightly.2312
    @types/react-dom: 17.0.3 => 17.0.3
    @types/react-router-dom: 5.1.7 => 5.1.7
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0
    @typescript-eslint/parser: 4.20.0 => 4.20.0
    blueimp-md5: 2.18.0 => 2.18.0
    bootstrap: 5.0.1 => 5.0.1
    checkcss: 1.0.2 => 1.0.2
    eslint: 7.21.0 => 7.21.0
    eslint-config-standard: 16.0.2 => 16.0.2
    eslint-plugin-import: 2.22.1 => 2.22.1
    eslint-plugin-node: 11.1.0 => 11.1.0
    eslint-plugin-promise: 4.3.1 => 4.3.1
    eslint-plugin-react: 7.22.0 => 7.22.0
    eslint-plugin-react-hooks: 4.2.0 => 4.2.0
    firebase: 8.4.2 => 8.4.2
    firebaseui: 4.8.0 => 4.8.0
    nanoid: 3.1.22 => 3.1.22
    parcel: 2.0.0-nightly.688 => 2.0.0-nightly.688
    react: ^16.13.1 => 16.14.0
    react-bootstrap: 2.0.0-alpha.2 => 2.0.0-alpha.2
    react-dom: ^16.13.1 => 16.14.0
    react-router-bootstrap: 0.25.0 => 0.25.0
    react-router-dom: 5.2.0 => 5.2.0
    sass: 1.32.12 => 1.32.12
    simplur: 3.0.1 => 3.0.1
    typescript: 4.2.3 => 4.2.3
```

**Comment by mischnic** [comment]
The existing handling for Node builtin modules is here (for resolving dependencies during build):

https://github.com/parcel-bundler/parcel/blob/760fc61c601641270e7ac7d4320682a074afebf8/packages/utils/node-resolver-core/src/NodeResolver.js#L441-L449

so it just compares the module name against the official list. It should account for `node:*` in there as well.
Unit tests are here: https://github.com/parcel-bundler/parcel/blob/760fc61c601641270e7ac7d4320682a074afebf8/packages/utils/node-resolver-core/test/resolver.js#L150

We should probably also reserve the `node:` pipeline so that it can't be specified in a parcelrc and it's just ignored during that `Unknown pipeline: ` check.

---

For dev dependencies (e.g. if PostCSS decides to use them in the future), this is handled here (the logic is similar):
https://github.com/parcel-bundler/parcel/blob/760fc61c601641270e7ac7d4320682a074afebf8/packages/core/package-manager/src/NodeResolverBase.js#L121-L123
