### ISSUE TITLE
Bug: Source maps don't work with hot reload

### ISSUE THREAD

**Issue by ozgrozer** [parcel-bundler/parcel#643]
In the console I get an output like `index.jsx:6 "test1"` and that's okay.
But when I save the file, it turns like `VM335:18 "test2"`.
I have to refresh the page to see this one `index.jsx:6 "test2"`.

So source maps don't work unless I refresh the page.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0
| Node             | 9.2.0
| npm/Yarn         | 5.6.0/1.3.2
| Operating System | MacOS 10.13.2

**Comment by DeMoorJasper** [comment]
This is currently the expected behaviour, flagged as feature. This is quite hard with the current implementation of hot module reload

**Comment by devongovett** [comment]
We evaluate the new code with `new Function`, so maybe we could generate an inline base64 source map for only the changed asset and put a source mapping URL comment in the code we eval?

**Comment by mischnic** [comment]
> so maybe we could generate an inline base64 source map for only the changed asset and put a source mapping URL comment in the code we eval?

I've got this nearly working, but there is one oddity:
```js
eval(`console.log("test");
console.log("hello");
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNjcmlwdC5qcyJdLCJuYW1lcyI6WyJjb25zb2xlIiwibG9nIl0sIm1hcHBpbmdzIjoiQUFFQUEsT0FBTyxDQUFDQyxHQUFSLENBQVksTUFBWjtBQUlBRCxPQUFPLENBQUNDLEdBQVIsQ0FBWSxPQUFaIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlc0NvbnRlbnQiOlsiXG5cbmNvbnNvbGUubG9nKFwidGVzdFwiKTtcblxuXG5cbmNvbnNvbGUubG9nKFwiaGVsbG9cIik7Il19`);
```
correctly prints:
```
test       script.js:3
hello      script.js:7 
```

But hmr-runtime uses `new Function` and
```js
new Function(`console.log("test");
console.log("hello");
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNjcmlwdC5qcyJdLCJuYW1lcyI6WyJjb25zb2xlIiwibG9nIl0sIm1hcHBpbmdzIjoiQUFFQUEsT0FBTyxDQUFDQyxHQUFSLENBQVksTUFBWjtBQUlBRCxPQUFPLENBQUNDLEdBQVIsQ0FBWSxPQUFaIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlc0NvbnRlbnQiOlsiXG5cbmNvbnNvbGUubG9nKFwidGVzdFwiKTtcblxuXG5cbmNvbnNvbGUubG9nKFwiaGVsbG9cIik7Il19`)();
```
prints:
```
test       script.js:7
hello      script.js:7 
```
???

**Comment by connorjclark** [comment]
@mischnic do you think `hmr-runtime` could use `eval` in the meantime?

**Comment by connor4312** [comment]
Continuing https://github.com/parcel-bundler/parcel/issues/5313#issuecomment-721613894

> As far as I can tell, neither Firefox nor Chrome support sourcemap comments in new Function() at this point

Chrome supports this on a protocol level.

![](https://memes.peet.io/img/20-11-c198f050-cf1a-4617-9bc0-b0cbf9b00721.png)

Because it's supported there, we have already been able to use function sourcemaps in widely scenarios in VS Code and its JS debugger (for example, vscode has web worker extensions which are all invoked with new Function()).

So if Parcel emitted sourcemaps in this scenario, Parcel users would be able to successfully debug using HMR in VS Code. And it puts a little pressure on the chrome devtools team to implement support for it within their UI 🙂

**Comment by mischnic** [comment]
> Firefox nor Chrome support sourcemap

Neither of them actually show the correct line, they do try to map *something*.

WIP PR: https://github.com/parcel-bundler/parcel/pull/5316

**Comment by connor4312** [comment]
Thanks for looking at this, let me know if you'd like me to lend a hand with anything 🙂

**Comment by mischnic** [comment]
A workaround for the browser bugs would be somehow evaluating the new code via a `<script>` tag.

**Comment by webcodion** [comment]
Hi!

This is still an issue for me. Page reload prints:
![image](https://user-images.githubusercontent.com/94392183/148611040-138281d2-a1c8-4926-b0d5-da202f5d3728.png)

HMR prints:
![image](https://user-images.githubusercontent.com/94392183/148611076-7ca59774-1255-46c3-948d-ad5d977e49d3.png)

Any workaround for this?

Webpack HMR works correctly.

Thank you!

**Comment by devongovett** [comment]
Investigated this a bit. There are some challenges here. The situation hasn't changed much since @mischnic commented in 2019. Chrome and Firefox support `sourceMappingURL` and `sourceURL` in `eval`, but not in `new Function`. So we can do something like this to work around that:

```js
let id = '_' + Math.random().toString(36).slice(4);
(0, eval)(`function ${id}(require, module, exports) {${asset.output}}`);
let fn = window[id];
delete window[id];
```

Unfortunately, while Safari seems to support this as well for `console` calls, it does not set stack traces to use the right source URLs. https://bugs.webkit.org/show_bug.cgi?id=137297

I think the only option then would be to load a `<script>` element over HTTP (inline scripts also have the same problem in Safari). But that means the HMR runtime would need to become async, which would be a big change. Rather than sending the content of the updated modules over the web socket and evaluating, we'd need to send an update via web socket, and then download a script before applying the updates. Not sure how much that would affect performance as well...
