### ISSUE TITLE
Config files do not invalidate cache

### ISSUE THREAD

**Issue by wavebeem** [parcel-bundler/parcel#66]
Create a new Parcel application with CSS modules and start it via `parcel index.html` but DO NOT create a `.postcssrc` config file yet.

Quit the Parcel server then create a `.postcssrc` file with `{ "modules": true }` as the content.

Start the Parcel server again.

Note that CSS modules do *not* work correctly at this point.

In order to make CSS modules work now you must `rm -rf .cache` and restart the Parcel server.

Example repo:

https://gist.github.com/wavebeem/c3afffcb4d757bf9d771fe1f0a9cf7e4

**Comment by thejameskyle** [comment]
We should probably come up with a better story on how to create cache keys.

Maybe `Asset` can expose a function to add information to the cache key

**Comment by wavebeem** [comment]
I haven't dug into Parcel internals at all yet, but is there any concept of dependent files that will trigger a rebuild?

**Comment by thejameskyle** [comment]
@wavebeem Can you expand upon that?

**Comment by DeMoorJasper** [comment]
Like u can see above i gave this issue a go a few days ago the main things i came up with, while trying and erroring to accomplish this:
* Configs should get exposed from the asset through for example a function that generates the config (including/excluding the defaults) { Should expose both config folder/location and content }
* Add a seperate file with every config location + hash of the config contents in ``.cache`` to later on compare this to any modified config files.
* Whenever an asset does a cache check, check if this config is in the cache if it is check with the getConfig function of the asset
* Configs should get added to the FileWatcher, onChange every Asset belonging to that config should change.
* The configHandler/Watcher/Checker wathever it should be called, should be instantiated from Bundler and get triggered at the same time cache writes & reads happen

I added this to this issue because i'll barely have any more time to work on this issue this week and someone might be able to do it before i get back into this issue.
