### ISSUE TITLE
parcel hangs on build on random file

### ISSUE THREAD

**Issue by alligatorjazz** [parcel-bundler/parcel#6760]
# 🐛 bug report
parcel hangs on a seemingly random file on every build. identical to the problem auchers described [here](https://github.com/parcel-bundler/parcel/issues/4698), but the included fix (--no-source-maps) didn't work for me.

## 🎛 Configuration (.babelrc, package.json, cli command)
```js
  "name": "ocia",
  "version": "2.0.0",
  "description": "the oviedo citizens in action official website",
  "main": "js/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build index.html --no-source-maps",
    "dev": "parcel index.html --no-source-maps"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/alligatorjazz/ocia.git"
  },
  "author": "Damian T. Thomas, Damian D. Thomas",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/alligatorjazz/ocia/issues"
  },
  "homepage": "https://github.com/alligatorjazz/ocia#readme",
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0"
  }
}
```
## 🤔 Expected Behavior
parcel should build the site and begin hosting.

## 😯 Current Behavior
hangs on building a random file while trying to build the site. the file it stops on is seemingly random.
<img width="574" alt="Screen Shot 2021-08-24 at 4 53 18 PM" src="https://user-images.githubusercontent.com/34864881/130692284-47b3c64b-caf4-463d-97fb-c33ddd37cc2e.png">

## 💁 Possible Solution

because the results appear random, i have no idea.

## 🔦 Context

i simply cannot build the server.

## 💻 Code Sample

https://github.com/alligatorjazz/ocia/tree/teardown/src -- public version of the project

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.16.1
| npm/Yarn         | 7.20.3
| Operating System | MacOS Catalina 10.15.7

**Comment by mischnic** [comment]
The repo you linked doesn't exist or isn't public

**Comment by alligatorjazz** [comment]
> The repo you linked doesn't exist or isn't public

my bad - should be fixed now.

**Comment by mischnic** [comment]
Please provide a smaller repo. Cloning this would download ~1GB.

**Comment by alligatorjazz** [comment]
discovered while trying to make the repo smaller that the culprit was a video in the index page that for some reason would make parcel hang. commenting it out allowed the build to proceed, and then when i changed the name of the video parcel worked as intended.

**Comment by sznowicki** [comment]
@mischnic please reopen, I'll try providing a repro soon. For now the details I found:

Once I upgraded from parcel@2.0.0-rc.0 to 2.0.0 I've noticed huge increase in the build time. From ~8 seconds up to two minutes or more (in slower CI instance it's even > 300 seconds).

I tried to figure out what are other differences but it really seems like it's Parcel

- parcel@2.0.0-rc.0: ✨  Done in 28.03s.
- parcel@2.0.0: ✨  Done in 170.14s.

I tried to narrow down affecting code and it seems it's the `url:` import that makes a difference.

```
import genericImage from 'url:../../img/transition-generic.svg';
```

The SVG contains quite big base64 image. Once I comment it out the build time drops to: 20.74s.

Only with this line line commented out! It's also worth noting there are more imports to different SVGs along with one png and mp4 video next to that one. Only this seems to be an offender. Also only this one has significant PNG inside.

This is all weird since I wouldn't expect parcel doing any processing of those files when I import them as `url:`.

Also as with @alligatorjazz I notice build hangs on random file, for a long time, then builds some more (logs with different files), hangs again and so on.

I'll analyse this little more today and provide some feedback too but please reopen.

**Comment by sznowicki** [comment]
[Repro-repo done](https://github.com/sznowicki/repro-parcel-issue-6760).

This is very very minimal but with even bigger SVG which makes it way too long to build on 2.0.0.

Notes from the repro:

## Benchmarks
OS: macOS 12.0.1 (also happens on macOS 11.6)

- `master` branch build time: on my machine, with this exact SVG it seems like it takes forever, killed after several minutes
- `rc` branch build time: 2.69s.

Also worth noting killing that hanged process is not possible with simple `ctr + c`. One must go to the activities app and force kill it.

**Comment by levino** [comment]
I think I have this issue too. Or at least a very similar one. `parcel build` just takes forever. How would I go about debugging this? `parcel build --log-level verbose` does not log anything.

**Comment by LeoniePhiline** [comment]
I've got the same issue, and no more leads as how to debug this.
@levino did you progress in any way?

**Comment by levino** [comment]
It resolved itself from checking out the repo again, updating the deps, removing `node_modules` or something. I suggest to first remove the parcel cache and then try again.
