### ISSUE TITLE
allow use of browser's build in module loader in v2

### ISSUE THREAD

**Issue by cekvenich2** [parcel-bundler/parcel#6831]
You can open browser developer tool to see it. At worst - you should give us an option to disable this 'improvement'. (to be sure, in ie 11 it is an improvement, but not on modern browser that support modules.). Lets say I have 3 entry points, but a large app will have many landing pages for A/B testing, SEO and more. A user loads page 1. That loads a module a. Module a loads modules b, c, d, e, f. Most pages have many many modules. When I build w/ Snowpack and Vite, they are left alone as imports. 
The user then goes to page 2. The page 2 has module z. Module z loads modules b, c, d, e and f. But because snowpack and vite can and do leave it as modules: it only loads z. It does not reload b, c, d, and e. So 5 times smaller, if they are all same size, but likely supporting modules are larger. Then user opens page 3 that has module k. Module k imports b, c, d and e. In Snowpack and vite, it only loads module k. It does not load b, c, d and e. It uses browser's native module load. Now compare to parcel v2. A use goes to same 3 pages. And each time b, c, d and e are loaded. 10 times larger than snowpack and vite. So please allow us to use native module loader and not force a combined load. Should I file a feature request?

**Comment by devongovett** [comment]
This depends on the size of the modules. If the modules are very small, duplicating them can actually be better to avoid the overhead of many small HTTP requests. Gzip compression is also more effective this way.

However, it is possible to change this already using the configuration shown here: https://v2.parceljs.org/features/code-splitting/#shared-bundles (specifically, setting `minBundleSize` to 0. This should result in the following bundles:

1. a (depends on 2 and 3)
2. b, c, d, e
3. f
4. z (depends on 2 and 3)
5. k (depends on 2)

This is more optimal because only a maximum of 3 http requests are made on initial load, rather than 6. And for subsequent loads, only the new code is loaded just like in your example.

**Comment by cekvenich2** [comment]
@devongovett If we go by who ever talks louder maybe you win. But what if we put it in a browser with dev tools? Build in snowpack. Build in parcel 2. One of them will be 10 times smaller. Because other builders like vite use browser's native module imports.

**Comment by devongovett** [comment]
As I explained above, it will not. Did you actually try that configuration option? If you are just going to make claims without actually trying things you're just wasting my time.

**Comment by cekvenich2** [comment]
I did try that option. You want to bet some $? I'll paypal you $1 if you are right, you send me paypal $1 if I'm right - as duplicated by others, code we post on git: using native module imports is smaller by 10X or more for developing regular app. as explained here: https://github.com/parcel-bundler/parcel/issues/6822

**Comment by cekvenich2** [comment]
I'll make a git project if you agree to paypal me $1 if I win. Anyone will be able to duplicate the results because science. Even if you don't believe, there it is. src type=module is better. If I 'cheat' then you don't have to pay. I'll follow your example above. The difference will be at least 10x in size.

**Comment by cekvenich2** [comment]
Even if not here and now: someone will compare snowpack, vite vs parcel sizes when multiple entry points or when one module is changed. It is 10x on browsers that support modules.
