### ISSUE TITLE
parcel2 rc0 does not check "devDependancies" for the existence of transformer-react-refresh-wrap

### ISSUE THREAD

**Issue by stevejhiggs** [parcel-bundler/parcel#6955]
# 🐛 bug report

when running `parcel build` with @parcel/transformer-react-refresh-wrap in "devDependencies" I get informed that the package is not present in my package.json.

## 🤔 Expected Behavior

This check should pass regardless of if @parcel/transformer-react-refresh-wrap is in "dependencies" or "devDependencies".

## 😯 Current Behavior

This check only passes  if @parcel/transformer-react-refresh-wrap is in "dependencies". If it's in "devDependencies you get:

```
@parcel/resolver-default: External dependency "@parcel/transformer-react-refresh-wrap" is not declared in package.json.

  /code/personal/parcel2-react-types-bug/package.json:14:3
    13 |   },
  > 14 |   "dependencies": {
  >    |   ^^^^^^^^^^^^^^
    15 |     "react": "17",
    16 |     "react-dom": "17"
```

## 🔦 Context

I'm currently trying to build a library using parcel 2 and while build works, watch is failing.

## 💻 Code Sample

https://github.com/stevejhiggs/parcel2-react-types-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.17.3
| npm/Yarn         | Yarn
| Operating System | OSX

**Comment by twhitbeck** [comment]
If I understand correctly, this is important for when you're building a react library.

**Comment by stevejhiggs** [comment]
I just checked and this is still an issue in nightly 845

**Comment by stevejhiggs** [comment]
Looking at https://github.com/parcel-bundler/parcel/blob/1b980caf31e324fd2285d4301067191e4ad99243/packages/utils/node-resolver-core/src/NodeResolver.js#L381 it would appear that the check of devDependencies is missing.

**Comment by stevejhiggs** [comment]
Resolved the issue. My watch script in package.json was:

`"watch": "parcel watch"`

But it should have been:

`"watch": "parcel"`

**Comment by JanMisker** [comment]
I have the same problem, but I'm not sure whether removing the `watch` from the `"parcel watch"` is the solution. In my understanding the `watch` is different from running parcel without any arguments.

As mentioned by @twhitbeck it indeed happens when developing a React library, not an app. 
I found this repository that has a similar problem, https://github.com/burhanuday/react-library-parcel 
Clone it and run `npm run watch` and you get the same error as stated above.

I tried running with `--no-hmr` but no difference.

**Comment by karelklima** [comment]
Happens to me as well using version 2.0.1.

My use case - a library in a monorepo with multiple packages, one of them has React as a peer dependency.

When I run `parcel watch packages/*` from the root folder, I'm running to the same error mentioned above. The error disappears once I add the package as a dependency to package.json to the specific module that is dependent on React. I would expect that I should be able to add the aforementioned package as a dev dependency to the root package.json (similar to e.g. `@parcel/transformer-typescript-types`), but that does not work.

Omiting the `watch` in the command does not do any good as Parcel behaves differently and compiles everything in the monorepo root folder, instead of building packages separately.

**Comment by jameskerr** [comment]
I've got the same issue. 

```
packages/react-arborist % yarn parcel watch
Port "1234" could not be used
🚨 Build failed.

@parcel/core: Failed to resolve
'@parcel/transformer-react-refresh-wrap/lib/helpers/helpers.js' from
'./node_modules/@parcel/config-default/node_modules/@parcel/transformer-react-refresh-wrap/lib/ReactRefreshWrapTransformer.js'

@parcel/resolver-default: External dependency
"@parcel/transformer-react-refresh-wrap" is not declared in package.json.

  /Users/jkerr/brimdata/react-arborist/packages/react-arborist/package.json:11:3
    10 |   "homepage": "https://react-arborist.netlify.app",
  > 11 |   "dependencies": {
  >    |   ^^^^^^^^^^^^^^
    12 |     "memoize-one": "^6.0.0",
    13 |     "react-dnd": "^14.0.3",

  💡 Add "@parcel/transformer-react-refresh-wrap" as a dependency.
```

Then in my package json I've got:

```
"devDependencies": {
    "@parcel/transformer-react-refresh-wrap": "^2.4.0",
```

I've developing a react library as well. Geez, I love parcel compared to all the other build toolchains out there.

**Comment by stevejhiggs** [comment]
I just updated the attached repro case to parcel 2.5.0 and the issue no longer occurs, using `parcel watch` with my typescript react library behaves as expected
