### ISSUE TITLE
Relative to root assets path problem

### ISSUE THREAD

**Issue by kirillunlimited** [parcel-bundler/parcel#7110]
# 🐛 bug report
After migrating to v2 I have a problem with assets paths: they used to have "relative to root" structure like this `/js/init.js`. But after I switched to Parcel v2 I started to get an error. If I switch path to "relative to current folder" structure like this `./js/init.js`, then it works fine. But this behavior breaks the multi-page structure of my project where pages from sub-directories should be able to access assets in the root.

You can check this behavior in a simple project that I created to demonstrate this problem: https://github.com/kirillunlimited/parcelv2-path-problem

## 🎛 Configuration (.babelrc, package.json, cli command)
No .babelrc
CLI command: `parcel src/**/*.html`

## 🤔 Expected Behavior
Parcel should process `/js/init.js` paths for every .html file and take assets from the root like Parcel v1.

## 😯 Current Behavior
```
@parcel/core: Failed to resolve '/js/init.js' from './src/index.html'

@parcel/resolver-default: Cannot load file '../js/init.js' in './src'.
💡 Did you mean './js/init.js'?
💡 Did you mean './js/app.js'?
```

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.17.6
| Yarn         | 11.22.11
| Operating System | MacOS BigSur 11.6

**Comment by kirillunlimited** [comment]
I think I got it: now I should point to the file relative to the root of the project, not relative to my target `dist` folder. This is quite a major change!

Maybe this behavior can be changed somehow? For example something like the `source` field in package.json? Something that can tell Parcel about how to resolve asset paths in htmls?

UPDATE
It looks like the change above also broke `parcel build`, it works successfully only in serve/watch mode.
Also I noticed that `--target` option is not working in watch/serve mode, so I need to add every option to my cli parcel command (like --dist-dir and etc.) but that's not a big deal.

Anyway, I created a simple project with demo of this problem: https://github.com/kirillunlimited/parcelv2-path-problem.

**Comment by psychicbologna** [comment]
I am experiencing this one too, it's very frustrating. I was refactoring my portfolio from create-react-app to Parcel and it all came crashing down. My project isn't too different from yours as far as dependencies, although I'm using npm instead of yarn. I was trying to tinker with the [--public-url param](https://parceljs.org/features/cli/#parameters) but it didn't seem to do anything.

![image](https://user-images.githubusercontent.com/11902346/159403068-efca7ad4-2d4c-47a1-9c5c-70611cef7c35.png)

[Project in question](https://github.com/psychicbologna/fukufolio)
