### ISSUE TITLE
watch and reload php files in parcel 2

### ISSUE THREAD

**Issue by GrzegorzNecka** [parcel-bundler/parcel#7181]
# 🙋 feature request

it is possible to implement in parcel v2 a mechanism that allows you to watch and reload php files in interval. parcel v1 contained a plugin https://www.npmjs.com/search?q=parcel%20%20watch-reload whose resolved this problem. I have a project on wordpress and I would like parcel to monitor php files.

Thanks for answer

**Comment by sznowicki** [comment]
I had similar problem in the past (not PHP, just triggering parcel builds based on non js files related events) and `nodemon` was my way to go.

With `nodemon` you can configure what to watch and what to do when files that being watched did change.

**Comment by onetrev** [comment]
I'm running into this issue as well. @sznowicki do you have a snippet you can post showing how this works? I played around with `nodemon` for an hour or two, but for a PHP based application like WordPress running in a **LEMP stack environment** I don't think it's possible. I could easily be wrong, haha. This problem was also mentioned in a [discussion](https://github.com/parcel-bundler/parcel/discussions/5144).

I'm facing the same issue. I can't find a way to trigger a reload with Parcel 2. Sure, I can setup Chokidar to watch my PHP files for changes, that works fine, but that doesn't help if you can't trigger a reload. 

It's a bummer because other than this issue I've found Parcel is incredibly easier to use than webpack. My webpack config file was 150 lines 🤯, and the same thing was accomplished with Parcel in a single CLI command. However, maybe the one thing webpack was good for was it only took one line to get it to reload when specified file types changed: 

`watchFiles: ['**/*.php'],`

It seems like this shouldn't be hard to accomplish, and that it would be something many others must run up against (seeing how popular WP is), so if anyone has any insight, please share!?

**Comment by hexcross** [comment]
Missing this feature is the reason why I'm forced to continue with gulp. It must be easy to add support for this.

**Comment by onetrev** [comment]
Hey @hexcross you can use this little [BrowserSync trick](https://github.com/hirasso/parcel-plugin-watch-reload/issues/14#issuecomment-770752849) to get the PHP watch functionality that you want. I've done that and it works well enough, definitely better than not using Parcel. :)
