### ISSUE TITLE
🐛Removing "import 'xxx.css'" doesn't work when files are watched

### ISSUE THREAD

**Issue by leonisme** [parcel-bundler/parcel#723]
This is a 🐛 bug report

### 😯 Current Behavior

Here's a HTML file, a Javascript file and a CSS file:

index.html
```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <h1>abc</h1>
    <script src="./index.js"></script>
</body>
</html>
```

index.js
```
import './index.css'
```

index.css
```
h1 {
 color: red
}
```

After building these files in watch mode, I changed index.js:

```
// import './index.css'
```

Though index.css isn't imported from index.js now, built index.html still imported the CSS file.

### 💁 Possible Solution

If it is in watch mode(including HMR), it's not suitable to use HTMLPackager to insert sibling bundles into HTML bundle, we can add scripts(for inserting link or script tags into head tag) into packaged js file while packaging js bundle . Link or script tags will be inserted into head tag or removed from head tag when code is running in browser. @devongovett

**Comment by freethejazz** [comment]
I'm running into a similar, potentially more impactful issue, where the removal of any style declaration will not load appropriately. I believe the root cause is the same (i.e., stylesheets being appended on change but not removed). You can duplicate this with the steps above by simply removing the color declaration in the h1 rule instead of commenting out the import. This could result in a significant difference between what parcel shows and the actual rendered css if the page were loaded cleanly.
