### ISSUE TITLE
Imported css files being dropped by parcel build

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#7332]
# 🐛 bug report

Hi legends,

I am using parcel@2.0.1 and I am importing a css file directly into a typescript file:

import '@package/styles.css';

All is well running parcel dev but when I run parcel build the css file is not included in any of the build files and the build site is totally broken as a result 🥺

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

Css file should not be dropped 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16.11
| npm/Yarn         | 1.x
| Operating System | Mac latest

**Comment by mischnic** [comment]
- If you use an HTML entry point, the CSS is added in a link tag to the HTML next to that script.
- If you are building a library with Parcel, the import is retained in the JS (which is what you're asking?)
- Otherwise, it's removed and there are (for example) `index.js` and `index.css` files created in the distdir. So if you want to use Parcel's output, you need to include both of them in your app. Including `import "./style.xyz.css";` in the JS would cause an error in the browser, and loading it dynamically at runtime (by including a runtime that inserts the style-link tag in the current page) would be detrimental to page load because it would not happen in parallel.

> I run parcel build the css file is not included in any of the build files

So the question is: what exactly do you expect to happen?

**Comment by arthurmmedeiros** [comment]
I'm experiencing the same issue here, but in my case I have the css files loaded only when I use Async imports, and I need them to load with sync imports.

Because of this [bug](https://github.com/parcel-bundler/parcel/issues/5683) I'm trying to replace all my async imports with sync ones. 

The problem seems to be similar to the described above, some of my react components have a correspondent .scss file, and these won't load with sync imports.

Any workaround for this? The bug I mentioned doesn't seem to have a solution, and I'm kind of stuck if I can't switch to sync imports.

UPDATE
Renaming my css files to .modules.css solved the case. Why don't we need it when we are using async imports?

**Comment by alexreardon** [comment]
@mischnic I am using an index.html entry point. Sadly no style sheet is being generated for the:

import "@package/styles.css";

When running parcel build

I'll put together a reproduction case early next week 👍

**Comment by alexreardon** [comment]
I am going to close this issue for now as I think the root issue is something incorrect in the package I am using. I tried out importing twitter bootstrap from a typescript and everything worked fine.

```ts
import 'bootstrap/dist/css/bootstrap.css';
```

I'll let y'all know if I get any more information about our incorrect package setup
