### ISSUE TITLE
🙋 feature request: built-in SSR for using bundler middleware

### ISSUE THREAD

**Issue by dbkaplun** [parcel-bundler/parcel#737]
- [ ] Add an [`ssr` option](https://github.com/parcel-bundler/parcel/blob/391e17f60fb4bf5a73ddd352883647fe6541d1cc/src/Bundler.js#L70-L91) that, when enabled, renders React components into their including .html files, calling `getInitialProps({req})` before rendering [a la next.js](https://github.com/zeit/next.js/tree/b50c596d0644da3759809dcd10b7144ffcd1d54b#fetching-data-and-component-lifecycle)
- [ ] Extend [server](https://github.com/parcel-bundler/parcel/blob/391e17f60fb4bf5a73ddd352883647fe6541d1cc/src/Server.js#L24-L35) to call a `render` method on assets if `ssr: true`
- [ ] Add a built-in `render` method to `HTMLAsset` that traverses linked assets, finds occurrences of [`ReactDOM.render/createPortal`](https://reactjs.org/docs/react-dom.html) in JS/JSX files, and uses [`ReactDOMServer`](https://reactjs.org/docs/react-dom-server.html) to render to a string and replace the contents of the HTML.

See also: #355

**Comment by devongovett** [comment]
The problem with this request is that Parcel is not specific to react. So we must design our features in a generic way that considers all possible frameworks.

That being said, if there is a way to have parcel enable this in a generic way so that e.g. plugins could implement SSR for react and other frameworks, that would be awesome. Let's figure out what that looks like.

**Comment by lbguilherme** [comment]
Just would like to add that for SSR to be useful, it is quite complicated. It must:

- Resolve the route to render the correct component (react-router)
- Understand how the application store state and transfer that state as well (rehydrate)
- Wait for APIs/Database calls from the components so that the rendered result actually have some content
- Do all of that with HMR?

---

And `parcel serve` is not a production server in any way, I don't think it should handle SSR. Maaaybe parcel would output a separated bundle suitable to run on Node that is a server with SSR for that application. But that sounds too much.

**Comment by dbkaplun** [comment]
FWIW [Rogue](https://github.com/alidcastano/rogue.js) does this with Parcel+React.

**Comment by DeMoorJasper** [comment]
I've also recently released https://github.com/DeMoorJasper/blazingly which is an experiment to create a universal and powerfull SSR server and cli tool for parcel (in the future blazingly will be stable and extendable)

I've also been chatting with the maintainer of Rogue on how to write Rogue as a blazingly extension

**Comment by stoffern** [comment]
@DeMoorJasper i think there is a problem doing boilerplates or boilerplated-tools all the time.
This is why i created https://github.com/velop-io/server .
> Supports multiple React apps, SSR, Webpack, HotReloading, Relay, Authenticated routes, FoundRouter, Graphql, custom routes +++ out of the box!

**Comment by DeMoorJasper** [comment]
@stoffern I was actually thinking of rewriting certain parts of blazingly to make it extendable, probably similar to how other SSR projects are doing it.
Perhaps I'll find some time this weekend, to dig into these improvements.

My main worry about supporting everything is that I dont's want to make the install gigantic, which is quite a bad thing, definitely as I'd like to make blazingly usable in production eventually (which isn't really possible if the install is ginormous, def on small cloud based servers).
The concept of blazingly in production is actually to create server and client bundles to run, so that the actual runtime of blazingly can be quite small and not responsible for anything except just running some scripts in a sandbox and serving some files (this could potentially also be hosted on a cdn)

**Comment by stoffern** [comment]
take a look at https://github.com/velop-io/server then
