### ISSUE TITLE
Typescript's parameter decorators not working

### ISSUE THREAD

**Issue by enrico-calzavara** [parcel-bundler/parcel#7425]
# 🐛 bug report
Typescript's parameters decorators are not correctly transpiled using parcel's default transpiler (SWC).

## 🎛 Configuration (.babelrc, package.json, cli command)

main.ts
```ts
import {Container, inject, injectable} from "inversify";

interface Warrior {
    fight(): string;
    sneak(): string;
}

interface Weapon {
    hit(): string;
}

interface ThrowableWeapon {
    throw(): string;
}

@injectable()
class Katana implements Weapon {
    public hit() {
        return "cut!";
    }
}

@injectable()
class Shuriken implements ThrowableWeapon {
    public throw() {
        return "hit!";
    }
}

@injectable()
class Ninja implements Warrior {

    private _katana: Weapon;
    private _shuriken: ThrowableWeapon;

    public constructor(
        @inject("Weapon") katana: Weapon,
        @inject("ThrowableWeapon") shuriken: ThrowableWeapon
    ) {
        this._katana = katana;
        this._shuriken = shuriken;
    }

    public fight() { return this._katana.hit(); }
    public sneak() { return this._shuriken.throw(); }

}

const myContainer = new Container();
myContainer.bind<Warrior>("Warrior").to(Ninja);
myContainer.bind<Weapon>("Weapon").to(Katana);
myContainer.bind<ThrowableWeapon>("ThrowableWeapon").to(Shuriken);

export { myContainer };
```
package.json
```json
{
  "name": "parcel2-app",
  "version": "1.0.0",
  "browserslist": [
    "defaults"
  ],
  "description": "",
  "scripts": {
    "build": "npx parcel build index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "inversify": "^4.13.0",
    "reflect-metadata": "^0.1.13"
  },
  "devDependencies": {
    "parcel": "^2.0.1",
    "typescript": "4.1"
  }
}
```
tsconfig.json
```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "isolatedModules": true,
    "lib": ["es6", "dom"],
    "module": "commonjs",
    "moduleResolution": "Node",
    "sourceMap": true,
    "target": "es5",
    "types": ["reflect-metadata"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

## 🤔 Expected Behavior

I just expect main.ts to be correctly transpiled (and then optimized) without using tsc as I'm not using anything beyond experimentalDecorators option, as stated in the migration guide.

## 😯 Current Behavior

Terser is breaking because parameter decorators are not transpiled, but just emitted as they are:

```
     36 |     public constructor(
  > 37 |         @inject("Weapon") katana: Weapon,
  >      |         ^ Unexpected character '@'
     38 |         @inject("ThrowableWeapon") shuriken: ThrowableWeapon
     39 |     ) {

  💡 It's likely that Terser doesn't support this syntax yet.

```

## 💁 Possible Solution

As Parcel is using SWC, could this be something related to [this swc issue](https://github.com/swc-project/swc/issues/1456)?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 12.22.1
| npm/Yarn         | 7.9.0
| Operating System | macOS 10.15.7

Thank you!

**Comment by astegmaier** [comment]
SWC does support transpiling constructor parameter decorators (see [PR #775](https://github.com/swc-project/swc/pull/775)), but you have to turn on the `decoratorMetadata` option. (compare [this playground where decoratorMetadata is true](https://play.swc.rs/?version=1.2.119&code=H4sIAAAAAAAAA0srzUsuyczPU0gpzc2tdElNzi9KLMkv0tBUqK7l4krOSSwuVvCtdAbT1VwKQJCcn1dcUlSaDFLlgKpLoSCxKDHXEKy3FgD9gu3SWgAAAA%3D%3D&config=H4sIAAAAAAAAA02PSw7DMAhE78I623aRdbc9BHJI5Mo2FhCpVuS7N863Oz4z82CBjzroF8goStIqLcnwCz1YyaROfDbowHQdjRiUOhjIsaCxKPQmM9UOArPSJYg%2B%2BbG0MMcxC6neK0xTOJWr0QSTjiyxqQNN6MrrjN%2FT%2F3hvMhzQ8MIaykS23kr6gHqDD5jXNw9zw%2B1B8eiW7bfN9oRaf5RpjUYFAQAA) to [this playground where it is false](https://play.swc.rs/?version=1.2.119&code=H4sIAAAAAAAAA0srzUsuyczPU0gpzc2tdElNzi9KLMkv0tBUqK7l4krOSSwuVvCtdAbT1VwKQJCcn1dcUlSaDFLlgKpLoSCxKDHXEKy3FgD9gu3SWgAAAA%3D%3D&config=H4sIAAAAAAAAA02PSw6DMAxE7%2BI123bButsewgoGpUriyDZSI5S7l%2FAp7PyZeWMv8FEH%2FQIZRUlapSUZfqEHK5nUic8GHZiuoxGDUgcDORY0FoXeZKbaQWBW%2BguiT34sDeY4ZiHVa4VpCqdyNZpg0pElNnWgCV15nfidfst7k%2BGAhjc7ykS2Hkv6gHolH2le3zzMLW8nxaNbtuc22xNq%2FQEm%2BJ2TBgEAAA%3D%3D)).

I can think of three ways of solving this issue for parcel:
1. Turn on `emitDecoratorMetadata` by default. (probably not the best idea as I'm assuming that `swc` defaults to `false` for a reason).
2. Key off of whether the user's `tsconfig.json` has `emitDecoratorMetadata` set, and pass this along to `swc`.
3. Provide some way for the user to customize `.swcrc`.

Does anyone on the core team have thoughts about which of these is best?

In the meantime, @enrico-calzavara - you should be able to work around it by using `@parcel/transformer-typescript-tsc` instead of the default `swc` (see [docs](https://parceljs.org/languages/typescript/#tsc)).

**Comment by mischnic** [comment]
There's a comment why this is disabled at the moment: https://github.com/parcel-bundler/parcel/blob/17404e9a9ee6323b973a681017937a4bc6966277/packages/transformers/js/core/src/lib.rs#L265-L266

I don't know if the situation has changed since that code was written

**Comment by deontologician** [comment]
So just to clarify (since I ran into this as well) this can't be fixed by adding a manual `.swcrc` to the project directory?

**Comment by Amorites** [comment]
> There's a comment why this is disabled at the moment:
> 
> https://github.com/parcel-bundler/parcel/blob/17404e9a9ee6323b973a681017937a4bc6966277/packages/transformers/js/core/src/lib.rs#L265-L266
> 
> I don't know if the situation has changed since that code was written

Hi @devongovett, is there any swc issue to track?

**Comment by Nickersoft** [comment]
Just wanted to bump on this issue - I've been watching it because I'm fading a similar issue... Similar to the last comment, is this being tracked anywhere? Has anyone found a workaround?

**Comment by turbolego** [comment]
I also have issues with `@Injectable`.
Is this package related to this issue? It's under 24 hours old...
TSC with support for emitDecoratorMetadata?

https://www.npmjs.com/package/@parcel/transformer-typescript-tsc

**Comment by Adamfsk** [comment]
SWC now has [great support for decorators](https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion), including stage 3, so the hard coded flag should be removed.

Edit: In the latest versions of `@swc/core`, `useDefineForClassFields` is set to `true` by default, which will break compilation of typescript style decorators in a mixed ts/js project.

To fix this, `jsc.transform.useDefineForClassFields` should be set to false in the config.
