### ISSUE TITLE
process.env.SOME_VAR returns `undefined` in imported package

### ISSUE THREAD

**Issue by Thi-tran** [parcel-bundler/parcel#7782]
# 🐛 bug report

## 🤔 Expected Behavior

`process.env.SOME_VAR` returns value in imported package

## 😯 Current Behavior

`process.env.SOME_VAR` returns `undefined` in imported package, but shows in current package.

## 🔦 Context

Issue affects building applications in micro-frontend environment. Local environment returns undefined in imported package

## 💻 Code Sample

- Defining local environment in current package: 

In .env
`SOME_VAR=true`

`import Page from 'package-A'
`
- Use local environment in imported package

in package-A's component
`console.log(process.env.SOMEVAR)`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.1
| Node             |  16
| npm/Yarn         | Yarn 1.22.10
| Operating System | MacOS 12.0.1

**Comment by Shinyaigeek** [comment]
This issue happens because JSTransformer  replaces environmental varables in JavaScript file and only current package
is processed by JSTransformer, so environmental variables in imported packages are not processed.

I think replacing environmental variables in imported package shoud be done in JSPackger, but the cost of parsing imported package's javascript and replacing environmental variable and genarate javascript from AST will be really high and will cause a serious performance degression, hmm...

**Comment by starpit** [comment]
Is this a bug or a feature? It seems like a pretty normal requirement that running

```shell
MY_ENV=foo launch-my-parcel-code
```

should work, in that this environment variable mapping should be visible to my parcel code, no matter what path of imports is taken to my code... and yet it does not always do so.

**Comment by mischnic** [comment]
For any code bundled by Parcel, it will inline the value of an env variable for expressions like `process.env.SOME_NAME`.

Code not bundled it outside of Parcel's control.
