### ISSUE TITLE
distDir not honored in target configuration for browser or main

### ISSUE THREAD

**Issue by michox** [parcel-bundler/parcel#7837]
# 🐛 bug report

using distDir is not honored by parcel. all output is generated to the dist directory, rather than the views directory. This has happened across both the projects I have been using parcel for.

## 🎛 Configuration (package.json)
```js
 "targets": {
    "main": {
      "distDir": "views"
    },
    "browser": {
      "distDir": "views"
    },
    "node": {
      "distDir": "views/node"
    }
```

## 🤔 Expected Behavior

all files are generated in the specified folders

## 😯 Current Behavior

files for targets browser and main are generated in dist/browser and dist/main respectively

## Workaround

rename targets 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.2|
| Node             | 8.1.0|
| Operating System | Windows 10

**Comment by mischnic** [comment]
In development mode (so running `parcel` or `parcel serve`), Parcel doesn't use the specified targets by default. See https://parceljs.org/features/development/#development-target

Does that explain what you're seeing?

**Comment by thien-do** [comment]
I think what @michox expected is that "main/foo.js" will be built into "views/foo.js", while the way Parcel works is that "main/foo.js" will be built into "views/main/foo.js" in production and "dist/main/foo.js" in development.

I don't think there is way for "main/foo.js" to be built into "views/foo.js" (without the "main" part), right @mischnic ?

**Comment by michox** [comment]
well generally I am not quite sure than what the distDir is supposed to be used for if what @thien-do is saying is correct

**Comment by mischnic** [comment]
What targets do is run the build multiple times, so e.g. with the usual `main` and `module` target you can output both CJS and ESM with a single `parcel build` invocation.
Or create a `modern` and `legacy` target with differing browserslist environments.

And then the `main`, `module` and `browser` targets are meant for libraries (as in: which are published to npm) because they have some specific default options set, so using them for a backend app wouldn't do what you want.
