### ISSUE TITLE
mdx-js/react@^2 compatibility

### ISSUE THREAD

**Issue by arcanis** [parcel-bundler/parcel#8009]
# 🐛 bug report

It seems that `@mdx-js/react` stopped exporting a `mdx` symbol [starting from 2.0](https://cdn.jsdelivr.net/npm/@mdx-js/react@2.1.1/index.js).

## 🎛 Configuration (.babelrc, package.json, cli command)

```
yarn add -D parcel@nightly lodash @babel/core
yarn add react react-dom react-select @mdx-js/mdx @mdx-js/react@1.6.22 @parcel/transformer-mdx@nightly

echo "import page from './page.mdx'; console.log('MDX Built');" | tee index.js
cat > page.mdx <<EOT
  import Select from 'react-select';

  # Hello, *world*!
  <div style={{ padding: '20px', backgroundColor: 'tomato' }}>
    <h3>This is JSX</h3>
  </div>
  <Select />
EOT

yarn parcel build index.js
```

## 🤔 Expected Behavior

Should compile

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/core: node_modules/@mdx-js/react/index.js does not export 'mdx'

  /private/var/folders/2s/1qvdx9f97plgcgy4r6mr26x80000gn/T/tmp.TeiyaVawuP/page.mdx:4:10
    3 |           # Hello, *world*!
  > 4 |           <div style={{ padding: '20px', backgroundColor: 'tomato' }}>
  >   |          ^^^
    5 |             <h3>This is JSX</h3>
    6 |           </div>
```

## 💁 Possible Solution

As a workaround, use `yarn add @mdx-js/react@^1` (but the doc still references `@mdx-js/react` without ranges, so people will have troubles with it). 

## 🔦 Context

Just noticed this in the Yarn E2E tests, doesn't affect us, we'll just use the workaround for now 👍

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Actually, it doesn't autoinstall right now either, so that's the users "fault" anyway.
~~Apart from updating the docs, we should also add~~
```js
await options.packageManager.require(
    '@mdx-js/react',
    asset.filePath,
    {
      range: "^1.0.0",
      saveDev: true,
      shouldAutoInstall: options.shouldAutoInstall,
    },
  );
```
~~here:~~

https://github.com/parcel-bundler/parcel/blob/51153c13b97d6f4392d4291a03597bf99feb2243/packages/transformers/mdx/src/MDXTransformer.js#L8-L12

~~so that you'll see an error from Parcel that the version currently installed is incompatible (if that's the case).~~

Related PR to use mdx 2: https://github.com/parcel-bundler/parcel/pull/7922
