### ISSUE TITLE
config-webextension ignores crome_url_overrides

### ISSUE THREAD

**Issue by TiagoCavalcante** [parcel-bundler/parcel#8070]
# 🐛 bug report

For making "new page" web extensions Chrome, Firefox and other browsers support the property `chrome_url_overrides`, which has the following pattern:
```json
"chrome_url_overrides": {
  "newtab": "/src/extension/chrome/index.html"
}
```

But Parcel is ignoring the file under "new_tab".

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
"build": "parcel build ./public/manifest.json --config @parcel/config-webextension"
```

## 🤔 Expected Behavior

The file `index.html` should appear in the dist folder.

## 😯 Current Behavior

The file `index.html` doesn't get included in the build.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 16
| npm/Yarn         | 8
| Operating System | Elementary OS (Linux)

**Comment by 101arrowz** [comment]
Couldn't reproduce this; `chrome_url_overrides` are rewritten properly for me.

Are you sure your project root is configured properly? Your project root will usually have a `yarn.lock` or `package-lock.json`, and it will look for your file from that directory. It might help to test with a relative file path rather than an absolute path to see if it's an issue with your config.

**Comment by TiagoCavalcante** [comment]
@101arrowz I was in the right folder, this was a cache problem, disabling and enabling the extension again solved my problem.
