### ISSUE TITLE
Using `compressors` makes `parcel serve` do nothing

### ISSUE THREAD

**Issue by ajeetdsouza** [parcel-bundler/parcel#8096]
# 🐛 bug report

If I include [`compressors`](https://parceljs.org/features/production/#compression) in my `.parcelrc` like so:

```json
{
  "compressors": {
    "*": ["@parcel/compressor-brotli"]
  }
}
```

`parcel build` correctly builds all files with the `.br` extension, but `parcel serve` doesn't build anything. Even if I run `parcel build` and then `parcel serve`, it will not serve the Brotli-compressed files correctly. If I add `...` under `compressors` it works, because uncompressed files are also generated. 

## 🤔 Expected Behavior

`parcel serve` should build assets and serve them correctly.

## 😯 Current Behavior

`parcel serve` doesn't do anything other than start a server.

## 💁 Possible Solution

Perhaps we can ignore the `compressors` setting when serving? We could use two different directories for `serve` and `build`.

## 🔦 Context

I'm building a WASM app that only supports modern desktop browsers, so I can safely assume that the said browsers would definitely support Brotli / GZIP compression. For that reason, I don't want to generate uncompressed assets.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.5.0
| Node             | 18.0.0
| npm         | 8.6.0
| Operating System | macOS 12.3.1

**Comment by mischnic** [comment]
The brotli/gz compressors only run in production builds (because it would slow down dev builds unnecessarily), the idea with the currently implementation is that you have this a config like this (or dots instead of the raw one)
```json
{
  "compressors": {
    "*": ["@parcel/compressor-raw", "@parcel/compressor-brotli"]
  }
}
```

and then get both in production builds and only non-compressed ones in dev.

**Comment by ajeetdsouza** [comment]
Would it make sense to instead have different directories for dev and production builds? For instance, Rust does `target/debug` and `target/release`.

**Comment by mischnic** [comment]
How is that related to your original question?

**Comment by ajeetdsouza** [comment]
I'm suggesting a solution.

- `parcel serve` could use a `debug` directory, skipping optional things like uglifying or compression and focusing on compilation speed.
- `parcel build` would use a separate `release` directory. This step would be slower as it does extra computation, but we'd end up with faster code.

**Comment by CxRes** [comment]
@mischnic How would you suggest that we test production builds with compressed outputs (since that is what one shall upload to a server)? Presently, adding a `serveOptions` with compressors only in config results in a 404, I am guessing because the server expects to find a `index.html` and not say `index.html.br`.

In fact, it would be nice to have something like Vite's preview feature where you can serve production builds locally. If I can figure out how to do it, I would be happy to even PR.

**Comment by mischnic** [comment]
I don't think it makes sense to test your production environment with Parcel's dev server. A more realistic approximation is doing a production build (`parcel build`) and then serving the output with some static file server. Because you won't be using Parcel's dev server in production.

**Comment by pastelsky** [comment]
It'd be good if parcel's dev server served gzipped assets (on-the-fly). For large apps, development bundles can run into several MBs, at which point even serving these via localhost / through a tunnel like ngrok becomes a bottleneck.

**Comment by ajeetdsouza** [comment]
This is still a valid issue.
