### ISSUE TITLE
transformer-js: script in isolated HTML page is not run

### ISSUE THREAD

**Issue by ArthurMelin** [parcel-bundler/parcel#8179]
# 🐛 Bug report

JS script file in an isolated HTML page referenced by another JS script / Vue template (as an `import pageUrl from"url:..."` dependency) is not run when said HTML page is loaded (`mainEntry` is set to null in the built bundle prelude).

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "extends": "@parcel/config-webextension"
}
```

```shell
$ parcel watch --target webext-dev --host localhost --hmr-port 8888 src/manifest.json
```

## 🤔 Expected Behavior

The JS script in the HTML page should be marked as the mainEntry of the bundle.

## 😯 Current Behavior

The JS script in the HTML page is not marked as an entry and the script is not run.

## 💁 Possible Solution

I tried looking into the problem myself, but I'mo not familiar enough with the code base to implement my solution, here is what I had in mind:
In [`@parcel/transformer-js isEntry():246`](https://github.com/parcel-bundler/parcel/blob/f2d0a3a27d6e493b23ddc2edbc8a4c0053ff34ab/packages/packagers/js/src/DevPackager.js#L246), I think the `!this.bundleGraph.hasParentBundleOfType(this.bundle, 'js')` check should be modified to stop walking up the bundleGraph if an `isolated` asset is found.

## 🔦 Context

I'm building a webextension, here is the dependency graph:
manifest.json -> content.js -> ContentApp.vue -> [...] -> ContentComponentX.vue -> page.html -> page.js

`manifest.json` is the root of the web extension. It references `content.js` as a content script.
`content.js` is the entry point of my content script, it injects and initializes a Vue application (`ContentApp.vue`) into some pages.
Some components later, there is a `ContentComponentX.vue` that references `page.html` by getting its URL with an `import pageUrl from "url:./page.html"` (e.g. `chrome-extension://<id>/page.html`) and then use it in a `<a href="">` tag that the user can click on.
`page.html` is an internal page of the extension, it contains a `<script>` tag which loads `page.js`.

The issue is: when navigating to `page.html`, the code in `page.js` doesn't run.
The prelude in the bundle generated by Parcel has `mainEntry` set to null.

## 🌍 Your Environment

| Software      | Version(s) |
| ---------------- | -------------- |
| Parcel           | 2.5.0 (2.6.0 crashes because of MV3/HMR bug #8168)
| Node             | v18.2.0
| npm/Yarn         | yarn v1.22.19
| Operating System | Linux x64 5.18.0

**Comment by Mallice** [comment]
This description looks similar to the problem I have.

On my webextension I have a devtools_page that load a devtool panel
--> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels/create

So the bundle graph looks like this:

`manifest.json > [1] devtools_page.html > [2] devtools.ts > [3] panel.html > [4] panel.ts`

Parcel is supposed to isolate the scripts loaded by `devtools_page.html` and the scripts loaded by `panel.html`
But the isolate does not appear to work as expected ??

```html
// [1] devtools_page.html
<script type="module" src="devtools.ts"></script>
```
```typescript
// [2] devtools.ts
  chrome.devtools.panels.create(
    "My Panel",
    null,
    new URL("./panel.html", import.meta.url) // similar to import panel from "url:./panel.html"
      .toString()
      .split(chrome.runtime.id)
      .pop(), // module resolution return absolute path, here relative path is requested
    (panel) => {}
  );
```
```html
//[3] panel.html
<script type="module" src="panel.ts"></script>
```
```typescript
// [4] panel.ts
export {}
console.log("My Panel is working");
```

## What happened:

> If the code is generated using `parcel watch`, there is no error, the only thing is that the panel.js script is not executed

But If the code is generated using parcel build we have a Type Error specifying that `parcelRequire381c` is not defined:
```
panel.d88b4bdc.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at panel.d88b4bdc.js:1:265
```

After looking on generated bundle, `parcelRequire381c` is defined on `devtools.hash.js` but since `devtools.hash.js` and `panel.hash.js` does not share the same window object the reference is lost, my guess is that isolated bundle does not behave as expected and the generated bundles are not properly isolated ?

Only way to workaround is to remove type="module" on `panel.ts` script tag, but it means we cannot import anything on panel.ts like creating a Vue app or other UI Framework.

**Comment by onikienko** [comment]
Had a similar problem. The solution will be to use additional entry points for `html`'s you want to isolate. 

Like that:
```
"start": "parcel watch src/manifest.json src/panel/panel.html --host localhost",
"build": "parcel build src/manifest.json src/panel/panel.html  --no-cache"
```

And @Mallice  script for panel creation will be:

```javaScript
  chrome.devtools.panels.create(
    "My Panel",
    null,
    'panel/panel.html',
    (panel) => {}
  );
```

This approach works and you may use import. But there is a problem if you will use `build` with `--no-source-maps` flag. In that case, you may have mixed js and css. Solutions: make build with source maps or remove them after build with some script like that - https://github.com/onikienko/mv3-parcel-webext-template/blob/main/utils/remove-source-maps.mjs
