### ISSUE TITLE
includeNodeModules does not include types

### ISSUE THREAD

**Issue by michox** [parcel-bundler/parcel#8267]
# 🐛 bug report

I have a module I want to have bundled in my library. I use typescript and would like the types of my module to be included in my distributed types. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "types": "dist/index.d.ts",
  "targets": {
    "main": {
       "includeNodeModules": [
           "my-module"
      ]
}
```

## 🤔 Expected Behavior

types from my-module are fully bundled in dist/index.d.ts

## 😯 Current Behavior

source code is included but types from my-module are imported as `import {methods} from "my-module"' 

## 🔦 Context

I am trying to build a library that will run on both node and browser. Some functions need to be replaced in this scenario but the vast majority stays the same. In order to do so, I was hoping to use a nested module that implements only the relevant changes using the targets feature. Since the nested module makes the system more of a composite project I was hoping to find a setting that would compile everything into one distribution package and found the includeNodeModules option but when I build with it, types are not bundled together. I tried enabling the typescript composite option in the tsconfig but I think the parcel ts compiler does not honor this yet

## 💻 Code Sample

https://github.com/michox/parcel-minimal-example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2|
| npm         | 8.12.1|
| Operating System | Windows 10

**Comment by danieltroger** [comment]
Also suffering from this issue.

**Comment by mischnic** [comment]
I'm not even sure where that decision to not include node_modules happens in the first place 
https://github.com/parcel-bundler/parcel/blob/cbc84b0c1d538b0ec15a3bf01f95da3ed623ebbb/packages/transformers/typescript-types/src/TSTypesTransformer.js#L43-L53

Might also be related to a `"include": ["src/**/*"]` in tsconfig

**Comment by danieltroger** [comment]
I don't have `"include": ["src/**/*"]` in any tsconfig.
I'm just getting started with yarn workspaces (because I need to publish a package) and I have my kid-package which is supposed to basically just contain/export/publish a utility from the outer workspace (if that makes sense? idk) and since the outer one isn't getting published type files that just reference it are obviously useless.

I tried generating them with TSC but it also just gave me a file that references the outer package. So idk how parcel generates them but if it uses TSC it's maybe because TSC just references packages and doesn't actually include their types?

It looks like I will have to create them manually for now and slowly make all dependencies published packages so it works. But if this would get fixed it would be epic.

**Comment by danieltroger** [comment]
Btw just noticed that types outside of the project root (imported with relative imports) also just get referenced and not included in the type output.

**Comment by SkyCodeSky** [comment]
Same here. It would be great to add something like this to `package.json`
```json
  "targets": {
    "types": {
      "includeNodeModules": true
    }
  },
```
Does anybody know if something like this or any other bug fix is in the pipeline?
