### ISSUE TITLE
build with --public-url,it will change href link to other relative path html page too

### ISSUE THREAD

**Issue by DodoMonster** [parcel-bundler/parcel#8318]
When I build with --public-url option in parcel v2

It will also change <a> tag  href attribute link to other relative path html page too

For example,

HTML code
`<a href="./news.html">跳去news</a>`

run npm script 
` "build-cdn": "parcel build ./src/*.html --public-url https://reskr-download.vsplay.com/res_kr/krpf/test"`

build result
`<a href="https://reskr-download.vsplay.com/res_kr/krpf/test/news.html">跳去news</a>`

I just want the --public-url option apply to the assets such as css js images and so on...

How can i fix the bug?

**Comment by Shinyaigeek** [comment]
I think this does not seems to be a bug because an absolute href URL generated from a relative href URL with `—public-url` works fine.

Basically, parcel’s output can be placed into a static server in a lump and works fine, so I think it is better to fix how to serve static assets generated with parcel.
