### ISSUE TITLE
AssertionError: `(0, _assert().default)(node.type === 'file')`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8477]
# 🐛 bug report

A build using the glob resolver fails with an assertion error when reusing the cache.

Happens only when the modified file isn't actually part of the build

## 🤔 Expected Behavior

Works

## 😯 Current Behavior

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(node.type === 'file')

    at /node_modules/@parcel/core/lib/RequestTracker.js:519:35
    at Array.map (<anonymous>)
    at RequestGraph.respondToFSEvents (/node_modules/@parcel/core/lib/RequestTracker.js:517:117)
    at loadRequestGraph (/node_modules/@parcel/core/lib/RequestTracker.js:864:18)
    at async Function.init (/node_modules/@parcel/core/lib/RequestTracker.js:821:17)
    at async Parcel._init (/node_modules/@parcel/core/lib/Parcel.js:256:28)
    at async Parcel.run (/node_modules/@parcel/core/lib/Parcel.js:273:7)
    at async run (/node_modules/parcel/lib/cli.js:376:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

## 💻 Code Sample

https://github.com/mischnic/parcel-issue-8477

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Operating System | macOS

**Comment by marcins** [comment]
I managed to locally work around this problem by changing this: 
https://github.com/parcel-bundler/parcel/blob/c3bbe0a6160186f496ca2f9e9bead9376c0522f1/packages/core/core/src/RequestTracker.js#L768-L775
to something like:

```js
           let above = this.getNodeIdsConnectedTo(
            fileNameNodeId,
            requestGraphEdgeTypes.invalidated_by_create_above,
          )
            .map(nodeId => nullthrows(this.getNode(nodeId)))
            .filter(node => node.type === 'file');
```
.. since just below glob types seem to be processed separately, and checks if they're connected: https://github.com/parcel-bundler/parcel/blob/c3bbe0a6160186f496ca2f9e9bead9376c0522f1/packages/core/core/src/RequestTracker.js#L783-L785

I haven't checked if this passes tests / is valid, but seems to "work for me".

Just putting it down here, if I get a chance I'll try it in the codebase and see how tests go.

**Comment by harsh17087** [comment]
I simply deleted my dist and parcel-cache folder and run npm start again. It worked
