### ISSUE TITLE
Still having issues with "Unsupported" things

### ISSUE THREAD

**Issue by jh3y** [parcel-bundler/parcel#8495]
# 🐛 bug report

I've raised an issue like this before and using `errorRecovery` version `2.7.0` I'm still having issues.

```
Unknown at rule: @position-fallback
```

```
Unsupported pseudo-class or element: selected
```

Config

```
"@parcel/transformer-css": {
  "errorRecovery": true
}
```

## 🤔 Expected Behavior

Should be able to bypass errors and be allowed to run what I've put in my CSS file.

## 😯 Current Behavior

Won't compile because of these "Unknown" rules.

**Comment by devongovett** [comment]
I assume this is closed because you got it working? It should be preserved since v1.13.0 of @parcel/css. If you see this logged it's just a warning rather than an error. https://github.com/parcel-bundler/lightningcss/releases/tag/v1.13.0

I've never heard of this at rule fwiw. Is there any info about it?

**Comment by jh3y** [comment]
I didn't get it working. I migrated my project to Vite instead.

`@position-fallback` is part of the CSS anchoring API spec.

**Comment by devongovett** [comment]
Ok well FYI, it looks like the issue was that you had an old version in your lock file. https://github.com/jh3y/sketchbook/commit/6fb57937eaef68290a22e19cdda0631f7e4bf788#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL332

> "@parcel/css@^1.12.2":

**Comment by jh3y** [comment]
Thanks for taking a look 🙏
