### ISSUE TITLE
🐛 The new --out-file option does not work when the entrypoint filename is not explicitly provided.

### ISSUE THREAD

**Issue by DieterHolvoet** [parcel-bundler/parcel#851]
The new --out-file option does not work when the entrypoint filename is not explicitly provided.

### 🎛 Configuration (.babelrc, package.json, cli command)

Cli command: `parcel build src/backend -o backend.css`
The `backend` folder contains a file `index.scss`.

### 🤔 Expected Behavior

`parcel build src/backend -o backend.css` creates a file called `backend.css`

### 😯 Current Behavior

`parcel build src/backend -o backend.css` creates a file called `f52f66c45540aa8b512238ac8ef6102f.css`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 6.9.1
| npm/Yarn         | 1.3.2
| Operating System | macos High Sierra

**Comment by brandon93s** [comment]
Thanks for reporting!

The check to determine if the file is the entry point breaks down when a folder is provided instead of an entry file:

https://github.com/parcel-bundler/parcel/blob/6e0a7f678b3938f0c59f0a5f0a77c32b9dd48fb5/src/Asset.js#L186

In this scenario, `this.options.mainFile` will be the directory and not the entry point. The `mainAsset` is resolved by the Bundler on initial build, which will contain the desired file:

https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L180

Note that even with the patch, this would only work in scenarios that automatic resolution work (e.g. for 'index' files). It's best to provide an actual entry file as opposed to a directory.
