### ISSUE TITLE
Parcel can't build projects with images

### ISSUE THREAD

**Issue by anteikuRE** [parcel-bundler/parcel#8540]
# 🐛 bug report
### Parcel hates images. 
When I'm trying to `npx parcel build src/index.html `  it stops without any eror, just doing a couple of steps and then stops. After a couple of weeks I found out that if I comment out all links on image in my `index.html` it will build successfully. Idk why this happening only with me but there are something wrong.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  {
  "dependencies": {
    "parcel": "^2.7.0"
  },
  "name": "author",
  "version": "1.0.0",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.7.0"
  },
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

}
```

## 😯 Current Behavior

Parcel drops me out without an error

### Trying to build with image
![1](https://user-images.githubusercontent.com/98753982/195698283-7373f600-9f5d-49c3-bd6c-f6ec7fbce9b3.png)

### Trying to build without image
![2](https://user-images.githubusercontent.com/98753982/195698386-1d062475-eac1-4f01-8cf2-712a1262689e.png)

## 💁 Possible Solution
I don't even know how all this is possible 

## 🔦 Context
this affects my mental health because I want to optimise my projects but can't do it for month

## 💻 Code Sample
https://github.com/anteikuRE/parcel-bug.git

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 16.17.1
| npm         | 8.19.2
| Operating System | win 10

**Comment by mischnic** [comment]
I guess some native module that is used when processing the image causes the process to crash. But it works fine for me on macOS and Windows.

**Comment by anteikuRE** [comment]
Find out that if I use bash console it gives error. Maybe this will help
![55](https://user-images.githubusercontent.com/98753982/195893492-bff78986-0caf-4c2d-b7d5-76d96bb9435e.png)

**Comment by MrFlashAccount** [comment]
Try WSL2 and stop suffering :)

**Comment by grimsteel** [comment]
I'm also experiencing this issue - it looks like it has something to do with oxipng

The oxipng command line utility does not work either so I wonder if shssoichiro/oxipng#427 is related

Edit: The error codes (`echo %errorlevel%`) are the same for both oxipng and parcel: -1073741795

**Comment by grimsteel** [comment]
I did some more digging into oxipng and it turns out that the underlying compression library (cloudflare-zlib-sys) does not work with non AVX CPUs. I followed the instructions in https://github.com/rust-lang/rust/issues/75612#issuecomment-798994496 and built the Parcel image optimizer after modifying cloudflare-zlib-sys (I attached the .node file - it's in the .zip - below) 

After copying it into node_modules/@parcel/optimizer-image Parcel works again with images! It's not a good solution but at least it works

[parcel-image.win32-x64-msvc.zip](https://github.com/parcel-bundler/parcel/files/10147552/parcel-image.win32-x64-msvc.zip)
