### ISSUE TITLE
Parcel renames function parameters even with js optimizers disabled

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [parcel-bundler/parcel#8563]
# 🐛 bug report

Even with the following in `.parcelrc`

```
{
  "extends": "@parcel/config-default",
  "optimizers": {
    "src/js/*.js": []
  }
}
```

Parcel still renames function parameters:

```
const fns = {
    x: () => 0,
    y: (x, z) => {x + z}
};
```

In this situation the actual code delivered to the browser (not in the sourcemap, but the code that is run) changes the parameter `x` to `x1`:

```
const fns = {
    x: () => 0,
    y: (x1, z) => {x1 + z}
};
```

I need the parameters to not be renamed. I can't figure out where this is happening in the Parcel build process, and I can't see a configuration option to disable it.

## 🎛 Configuration (.babelrc, package.json, cli command)

See above for `.parcelrc`

## 🤔 Expected Behavior

Function parameters should not be renamed, especially when js optimizers are disabled. There needs to be a config parameter to disable this.

## 😯 Current Behavior

Function parameters are renamed.

## 🔦 Context

I am using function parameter names to automatically inject dependencies into functions. I need the names not to change.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.7.0 |
| Node             | 8.19.1 |
| npm/Yarn         | 8.19.1 |
| Operating System | Linux |

**Comment by mischnic** [comment]
1. This is caused by swc itself: https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA0vOzysuUUjLK1awVajmUgCCCisFDU0FWzsFAx0wvxLIrzDUUagCC1ZXGCpoK1TVctVaAwCUG%2Bf3OwAAAA%3D%3D&config=H4sIAAAAAAAAA02OsQrDMAxE%2F0VzhpKhQ%2Bau%2FQjhKsHBtoykQI3xv9cOgXSTdO%2FuVGFXB0uFjKIkY9KSDL%2BwgJVM6sRngwlM%2B2nFoNT6grKRdYR0fsxzlwOz0gVMEH3yaxlhjmMWUr0lTFugvyjBpCtLHHSgDV15kWNB4%2F6NyUGtU5E%2Fx3DV86mz%2BAntLrrCvb4v8DT%2BAEx1eRDdAAAA

If you want, you can open an issue with swc: https://github.com/swc-project/swc/issues

3. Optimizers are run per bundle (and not on the the input files), so `"optimizers": { "src/js/*.js"` doesn't do anything as it doesn't match any bundle

**Comment by hiroshi-yamamoto-dublr** [comment]
@mischnic Thanks, I'll file an SWC bug report.
