### ISSUE TITLE
Entry point with self-closing HTML script tag with type="module" attribute (and with certain browserslist) is output without the type attribute

### ISSUE THREAD

**Issue by glennflanagan** [parcel-bundler/parcel#8662]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Default config

## 🤔 Expected Behavior

Output HTML script element should contain the `type="module"` attribute

## 😯 Current Behavior

Entry point HTML file which has `<script  src="src/index.js" type="module" />` is output as 
```html
<script src="/index.5d9a9a91.js"></script>
<script src="/index.23a4b730.js" nomodule defer></script>
```
(Notice no `type="module"` attribute)

Browserslist is set to 
```
> 0.25% and not dead
last 3 major versions
not ie <= 11
```
## 🔦 Context
This manifested itself as an error `Uncaught SyntaxError: Cannot use 'import.meta' outside a module` as I was using a Worker script set up as per the documentation.

To reproduce please check out the below repo `master` branch and run `npm install` then `npm run build && npx serve dist`. You can then check out the `working` branch and run the same commands to see it working.

## 💻 Code Sample

https://github.com/glennflanagan/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0
| Node             | v14.15.1
| npm/Yarn         | 6.14.8
| Operating System | MacOS Big Sur 11.7.1 (20G918)

**Comment by rhcarvalho** [comment]
Perhaps the problem is more general. TL;DR: I think white space within the `<script>` tag also causes the `type="module"` to go missing.

I had in `index.html` (note white space within the `<script>` tag):

```
<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <script type="module" src="index.js">

    </script>
  </body>
</html>
```

And noticed `parcel build` output missing `type="module"`:

```
...<script src="/index.c6b6fac4.js"></script><script src="/index.e2267745.js" nomodule defer></script>...
```

When I removed the spaces between the open and close `<script>` tag, the `type="module"` attribute is now in the `parcel build` output:

```
<script type="module" src="index.js"></script>
```

My observation is that for Parcel to work correctly the HTML entry point must have a script tag that is exactly as above, without inner white space, and not using self-closing tag syntax.

---

Software | Version(s)
-- | --
Parcel | 2.8.0
Node | 18.12.1
pnpm | 7.18.1
