### ISSUE TITLE
Create React App compatibility

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#8780]
# 💬 RFC

[Create React App](https://github.com/facebook/create-react-app) is a very popular all-in-one tool for building React SPAs. It is similar in philosophy to Parcel in many ways – batteries included, minimal configuration needed, etc. However, it is currently not well maintained, slow due to use of older JS-based tools like webpack, babel, postcss, etc., and lacks extensibility (other than completely ejecting). Parcel solves most of these problems, and I think we can help make migrating existing CRA apps to Parcel easier, as well as provide some of the niceties of CRA for building new apps.

There are a few major areas to this effort.

1. **A project scaffolding tool.** CRA makes bootstrapping a new app super easy. You run one command and it sets up a git repo with all the necessary dependencies, a dev server, build command, test command, etc. I think Parcel can go one step beyond this and make a general purpose scaffolding tool that could (eventually) support any framework. It could walk you through some questions (framework to use, TS or not, styling methodology, test framework, etc) and then set up an app for you. The [roadmap](https://github.com/parcel-bundler/parcel/discussions/7345#scaffolding) has some more ideas for this.
2. **A migration tool.** The goal would be to build a tool that could migrate non-ejected CRA apps to Parcel automatically. This means we'd need to generate a similar Parcel setup to the webpack-based one of CRA. Handling ejected apps will be too complex, but since non-ejected apps basically will have no configuration, it should be possible in that case. See below.
3. **Compatibility.** We need to determine what features are missing from Parcel to make bundling CRA apps possible. Most things are automatically handled already, but there are a few things built into CRA that we might not have out of the box. A few things I can think of:
    * Compatibility with the resolver. tsconfig paths, baseUrl, etc. I am already working on this right now. Other things such as default aliases for react-native to react-native-web would need to be provided in migrated apps as well. Should look at the webpack config and generate a similar configuration for Parcel.
    * Handle the builtin Babel and PostCSS plugins that CRA provides (e.g. babel macros, normalize, tailwind, etc.). Don't have to use Babel or PostCSS in the implementation just ensure things still work when migrated to a different implementation. Also don't need to necessarily include all these for new apps built with the scaffolding tool - this is mainly for compatibility with existing apps migrated using the tool.
    * Migrate the public folder HTML file over to an HTML entry for Parcel.
    * Generate a similar jest setup to CRA for migrated apps. Unsure if we want to provide this in the scaffolding tool for new apps or not - maybe it should be one of the questions when starting ("What testing tool do you want to use?").
    * Create a similar eslint setup.
    * etc. We'll find lots of things as we test apps and look through the webpack/babel configs inside CRA. I think the first step will be determining what all of the features are and how to emulate them with Parcel.

**Comment by joemckenney** [comment]
Some ideas/thoughts related to a package scaffolding tool.

We could create a package that is itself a canonical parcel app as the base for scaffolding out parcel apps.  Concretely, a package in the parcel repo (if the plan is for this work to live there) that is a working parcel-powered app.  It can be copied, its code/config can be easily parsed and modified according to the scaffolding parameters.

Some benefits: The canonical parcel-powered app can be spun up.  It can be tested.  Its dependencies can be updated by something like renovate or dependabot.  

This approach may pair nicely with the migration portion of this problem.  If the reference parcel app supports all configurations of a CRA non-ejected app - the migration problem is perhaps simplified.  

Alternatively, instead of a single canonical parcel app, we might create many reference parcel apps corresponding to various CRA configurations.  The migration problem becomes a feature mapping problem, i.e., establish the features of CRA used and map that to the closest reference app.  Reference apps still have all the benefits listed above.

The ideas above are lifted from building package scaffolders at my current company and a reaction to working with scaffolding solutions that are more template driven in the past.

**Comment by devongovett** [comment]
Yeah that sounds nice. One potential thing to think about is if there are a few questions like "What framework do you want to use (React, Vue, etc.)?" "How do you want to style your app (CSS, CSS modules, SASS, Tailwind, etc.)?" "Do you want JS or TS?" etc. there could be a lot of different permutations. But I agree having at least some of these as runnable examples would be great for testing!

**Comment by joemckenney** [comment]
Good input. Framework optionality makes this problem a bit harder.

Maybe a follow-up question - would you imagine the scaffolded app is minimal in the sense that its dependencies/config/etc, are based primarily on the parameters to the scaffolder?

I'm not really an expert on CRA, but based on the little I've read just now and what you posted, it seems like CRA-scaffolded apps are more bloated / less minimal.  They support lots you didn't ask for out of the box.

It would seem that supporting only what you asked for vs. supporting what you asked for and more is an interesting decision point that can potentially influence the scaffolding solution direction quite a bit.

**Comment by devongovett** [comment]
I think the project scaffolding tool for new apps is relatively decoupled from CRA compatibility, so we have some freedom there. It's mainly related because it is a nice feature that CRA has that Parcel currently doesn't. Parcel also already does a lot with very little config, so it's very different from needing to generate a complex webpack/babel config or something. I think the questions would mainly affect what files the scaffolding tool creates. For example, `.ts` instead of `.js`, `.css` vs `.scss`, etc.

As for whether we'd want to have a default option where you just say make me a react app, and it sets up the defaults with no other questions (similar to how CRA works), I'm not sure. Could be useful? But we could also potentially just let you press Enter a few times on some of the questions to pick a default. What do you think?

**Comment by joemckenney** [comment]
> I think the project scaffolding tool for new apps is relatively decoupled from CRA compatibility, so we have some freedom there. It's mainly related because it is a nice feature that CRA has that Parcel currently doesn't. Parcel also already does a lot with very little config, so it's very different from needing to generate a complex webpack/babel config or something. I think the questions would mainly affect what files the scaffolding tool creates. For example, .ts instead of .js, .css vs .scss, etc.

Helpful context.

> As for whether we'd want to have a default option where you just say make me a react app, and it sets up the defaults with no other questions (similar to how CRA works), I'm not sure. Could be useful? But we could also potentially just let you press Enter a few times on some of the questions to pick a default. What do you think?

Hmm I suppose I lean toward being more intentional, so probably questions w/ defaults. It's less to back yourself out of later.

**Comment by arthurvmdantas** [comment]
A project scaffolding tool would greatly help Parcel's adoption. 🤞

> As for whether we'd want to have a default option where you just say make me a react app, and it sets up the defaults with no other questions (similar to how CRA works), I'm not sure. Could be useful?

I believe that something like Vite's template options (Vanilla, React, Vue, Svelte, etc. with or without TypeScript) would be nice to have (and fairly simple to implement, maybe?).

> But we could also potentially just let you press Enter a few times on some of the questions to pick a default. What do you think?

 I lean towards default options pressing "Enter" when not explicitely using a template.

> Yeah that sounds nice. One potential thing to think about is if there are a few questions like "What framework do you want to use (React, Vue, etc.)?" "How do you want to style your app (CSS, CSS modules, SASS, Tailwind, etc.)?" "Do you want JS or TS?" etc. there could be a lot of different permutations. But I agree having at least some of these as runnable examples would be great for testing!

I would say that having fewer options (NextJS always uses CSS modules) and having good documentation on how to add Tailwind, for example, is preferable.

**Comment by joemckenney** [comment]
@devongovett I'm happy to devote some cycles to the scaffolding side of this problem.  After taking last night to comb through other `create-*` style CLIs - it seems like the problem/solution space is pretty well defined.  Not sure what next steps look like or how projects/ideas here typically transition from RFC to in-progress work streams.  Would you like me to write up a plan or RFC analogous to this one but specifically for scaffolding?

**Comment by devongovett** [comment]
@joemckenney awesome! Yeah if you'd like to write a plan for how it will work that might be helpful. Either here or in a separate issue is fine.

**Comment by padunk** [comment]
Hi, hit me up if you need any help.
I'm a noob but I want to contribute to OSS.
I create this package https://www.npmjs.com/package/create-app-now a couple of years ago but not upgrading it since then :)

**Comment by richardkmichael** [comment]
I'm very happy to see this issue.

> However, it is currently not well maintained, slow due to use of older JS-based tools like webpack, babel, postcss, etc., and lacks extensibility (other than completely ejecting). Parcel solves most of these problems

This is exactly why I am migrating a relatively large CRA app to Parcel.

> lacks extensibility (other than completely ejecting)

FWIW, we use [craco](craco.js.org) to override without ejecting.

I am attempting to configure Parcel to build the app exactly as-is -- no changes to the source code or file layout (either source or output) so as not to disrupt teammates or the existing deploy tooling and process.  Ideally, after Parcel is working, I'll simply change the `npm script` definitions.

FWIW, our app seems to build just about perfectly with Parcel out of the box.

I wrote a tiny Parcel resolver plugin (to prepend `src/` to import names).  Also, I received a lot of much appreciated help on Discord for a bundle name collision and was able to adjust a dynamic import to fix the problem. 👍 

I now need to handle the `public/index.html` file, which contains the CRA variable`%PUBLIC_URL%`.   It seems I'll need a Parcel HTML entry for that (unsure about the variable though) -- appreciate that being mentioned in the description. :-)

I wonder if it would help to start with a guide for people coming from CRA?  Maybe this would identify specific situations which tooling will need to handle?  It would also get people going without waiting for a tool (for either scaffolding or migration).  Happy to help on this, if there's interest.

I've been wanting to use Parcel since it first emerged, but lacked a serious use-case.  Looking forward to getting this app moved -- the build time is a remarkable improvement!! ⚡
