### ISSUE TITLE
`package.json` `alias` not expanding?

### ISSUE THREAD

**Issue by rubend056** [parcel-bundler/parcel#8794]
# 🐛 bug report

`alias` glob to an absolute/tilde paths don't get further expanded, or is incorrectly resolved when target isn't on project root:
- This works `parcel build index.html`
- This doesn't `parcel build src/index.html`

I've tried to zero in on the problem as much as possible, Just need the knowledge of the maintainers at this point.

## 🎛 Configuration (.babelrc, package.json, cli command)

`index.html` and `src/index.html` are identical:
```html
<!doctype html>
<html>
<head>
	<link id="preload" rel="stylesheet" href="@styles/preload.css">
</head>
</html>
```

`src/index_absolute_path.html`
```html
<!doctype html>
<html>
<head>
	<link id="preload" rel="stylesheet" href="/src/styles/preload.css">
</head>
</html>
```

`src/styles/preload.css`
```css
.test{
	color:red;
}
```

`package.json`
```json
{
  "devDependencies": {
    "parcel": "^2.8.3"
  },
  "alias": {
    "@styles/*": "/src/styles/$1"
  }
}
```

## 🤔 Expected Behavior

For the alias to get resolved, I've been looking through the tests on `utils/node-resolver-core` but can't seem to find much, a lot of things are pretty cryptic partly because parcel is doing a whole lot of work.

## 😯 Current Behavior

`yarn parcel build index.html`
```
✨ Built in 158ms

dist/index.html            121 B    236ms
dist/index.f45df576.css     81 B     87ms
Done in 0.69s.
```

`yarn parcel build src/index.html`
```
🚨 Build failed.

@parcel/core: Failed to resolve '@styles/preload.css' from './src/index.html'
@parcel/resolver-default: Cannot load file './@styles/preload.css' in './src'.
💡 Did you mean './styles/preload.css'?

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn parcel build src/index_absolute_path.htm`
```
✨ Built in 155ms

dist/index_absolute_path.html            135 B    256ms
dist/index_absolute_path.ffe85a48.css     95 B     56ms
Done in 0.68s.
```

## 💁 Possible Solution

The only solution I that makes sense is:
- Parcel is not expanding the path.

## 🔦 Context

I want to have different targets and be able to move libraries around with aliases instead of having to rename every other file that uses it.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.3
| Node             | v19.3.0
| npm/Yarn         |  1.22.19
| Operating System | Arch Linux

**Comment by devongovett** [comment]
Dependencies in HTML and CSS files are resolved using URL semantics, which means in this case `@styles/preload.css` is treated as a relative path, not an npm module. However, aliases are defined using CommonJS semantics, so `@styles/*` is treated as an npm module, and not a relative path.

It's actually probably a bug that `index.html` works here, as it should be equivalent to `./@styles/preload.css` and not treated as a module. `src/index.html` is handled correctly because it's resolved relative to the package.json, i.e. `./src/@styles/preload.css`.

All that to say there are two ways to get this working:

1. Reference using an absolute path like `/@styles/preload.css` so it is resolved relative to the project root rather than from the HTML file. You'd also need to change the alias so it is defined as `./@styles/*` in the package.json.
2. Explicitly use an npm specifier like `npm:@styles/preload` in your HTML so it is resolved like a module rather than a relative path. Keep the package.json the same in this case.

**Comment by rubend056** [comment]
Wow @devongovett, this makes absolute sense. This is exactly the kind of insight I needed, thanks a lot :+1: . I'll close this issue and mark it as solved when I've tested it :)

**Comment by rubend056** [comment]
I found the easiest solution to be 2. as it leaves the aliases as straightforwards as possible. Again thanks :)

**Comment by scherler** [comment]
I found this issue and can validate using `node:index` works where `@index` or `#index` fails 
![image](https://github.com/parcel-bundler/parcel/assets/596701/63ba4d34-1d6f-4443-9a67-77887f018b26)
