### ISSUE TITLE
Failed to resolve 'process' from './file'

### ISSUE THREAD

**Issue by tristan-f-r** [parcel-bundler/parcel#8879]
# 🐛 bug report
Parcel incorrectly tries to resolve `process` in a typeof check, and tries to install the `process` package to mitigate it:

```js
console.log(typeof process !== "undefined")
```

This type of statement occurs in [`@lezer/lr`](https://github.com/lezer-parser/lr), a common package used in almost all [codemirror](https://codemirror.net/) language packs ([lr/parse.ts#L9](https://github.com/lezer-parser/lr/blob/c6922b8ad86e308c6795c4e52ca9e5918c04c625/src/parse.ts#L9))

## 🤔 Expected Behavior

It should simply continue on as expected

## 😯 Current Behavior

```
@parcel/core: Failed to resolve 'process' from './test.js'

  /home/leodog896/Documents/GitHub/codemirror-lang-snbt/test.js:1:20
  > 1 | console.log(typeof process !== "undefined")
  >   |                    ^^^^^^^
  ```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | v18.7.0
| pnpm         | 7.27.0
| Operating System | Fedora Workstation 37

**Comment by mischnic** [comment]
Even if we change Parcel to not import `process` when doing `typeof process`, the second part of `typeof process != "undefined" && process.env && /\bparse\b/.test(process.env.LOG!)` is certainly going to do that.

So we could improve the handling for your specific code sample, but it wouldn't help with lezer/codemirror.

**Comment by levrik** [comment]
Is there any workaround available? I wanted to give Parcel another try after I didn't get it working shortly after the stable release and again I'm running into a blocker just a few minutes in. I really want to use Parcel but looks like it's still not ready for production-use.

I'm trying to import `pyodide` but it's not building due to this issue.

_Edit:_

Adding the following to `package.json` seems to work.

```json
"alias": {
  "process": false
}
```
