### ISSUE TITLE
Relative --public-url ./  fails with  404  on `serve`

### ISSUE THREAD

**Issue by mihailik** [parcel-bundler/parcel#9019]
# 🐛 bug report

A single `index.html` referring to a single `main.js` fails, refuses to resolve the script.

Inlined `<script>` works. Removing `--public-url` or replacing with absolute URL works.

## 🎛 Configuration (.babelrc, package.json, cli command)

**index.html**
``` html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Parcel DEMO Page</title>
</head>

<body>

  <script>
    const pre = document.createElement('pre');
    pre.style.cssText = 'border: solid 1px tomato; margin: 0.5em; padding: 0.5em; border-radius: 0.5em;'
    pre.textContent = pre.innerText = 'Injected <pre> element from inline JavaScript inside index.html.';
    document.body.appendChild(pre);
  </script>

  <script src="main.js"></script>

</body>

</html>
```

**main.js**
``` js
const pre = document.createElement('pre');
pre.style.cssText = 'border: solid 1px tomato; margin: 0.5em; padding: 0.5em; border-radius: 0.5em;'
pre.textContent = pre.innerText = 'Injected <pre> element from linked JavaScript file main.js.';
document.body.appendChild(pre);
```

**package.json**

``` json
{
  "name": "parcel-public-url-demo",
  "private":true,
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html --public-url ./"
  },
  "devDependencies": {
    "parcel": "^2.8.3"
  }
}
```

## 🤔 Expected Behavior

`npm start`

Running from this repo will show both inline and linked scripts run successfully and show both outputs on the page.

## 😯 Current Behavior

Inline script works, and produces output.

Linked script fails to load with HTTP 404.

![image](https://github.com/parcel-bundler/parcel/assets/4041967/541a7fef-310c-4e76-a20b-880f0cba0c45)

## 🔦 Context

Relative URL is needed for making a build that can be deployed in several ways.

It could be a QA and PROD version of the app.
It could be the same codebase running via different hosting URLs.
Full URL also makes it hard to run from file:// location.

Another use case is running via VSCode CodeSpace, which proxies localhost parcel server into a long pseudo-random URL inside VSCode host.

## 💻 Code Sample

https://github.com/mihailik/parcel-public-url-demo

## 🌍 Your Environment

Tried to run from CodeSpace, or from local machine (MacOS M1 chip)

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 19.9.0
| npm/Yarn         | 9.6.3
| Operating System | Linux

**Comment by DLakomy** [comment]
I encountered the same issue yesterday and this is the first closed issue I've found about my problem. I'd be very happy if there were some answer, as the behaviour is really confusing. The command `serve` can be used with `--public-url`, but in reality it doesn't work (at least not as expected). I'd expect Parcel to just serve the files present in `dist`, as they are in the correct directory. Another server works as expected (tested with the `Live Server` extension for VS Code).

The issue is reproducible exactly as originally described. I've checked with newer versions, as below:

| Software | Version(s) |
| --- | --- |
| npm | 10.2.3 |
| Node | 20.10.0 |
| Parcel | 2.12.0 |

I'd like to ask for reopen and a fix or some explanation.

**Comment by dagnelies** [comment]
same problem here
