### ISSUE TITLE
Regression in 2.9.0: @parcel/bundler-default: Got unexpected undefined for CSS modules

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#9058]
# 🐛 bug report

All of my parcel-using projects started getting this error when trying to upgrade to parcel 2.9.0 (and 2.9.1 as well):

* https://github.com/BTE-Trusted-Entity/socialkyc.io/actions/runs/5121469288/jobs/9209275748?pr=1112
* https://github.com/BTE-Trusted-Entity/didsign/actions/runs/5121417909/jobs/9209157572?pr=154
* https://github.com/BTE-Trusted-Entity/checkout.kilt.io/actions/runs/5100857501/jobs/9169379676?pr=28
* two more in private repositories

## 🎛 Configuration (.babelrc, package.json, cli command)

I think I don’t set any babel configuration, and the only non-paths configuration is:

```json
{
 "context": "browser"
}
```

Since the projects are open-source, you can see all the details in their repositories.

## 🤔 Expected Behavior

The bundler should bundle these projects, since the previous version of bundler managed that.

## 😯 Current Behavior

Both `parcel watch` and `parcel build` fail with the error "@parcel/bundler-default: Got unexpected undefined". It happens either in `DefaultBundler.js:731:72` or in `DefaultBundler.js:707:62`: 

```
$ parcel
Server running at http://localhost:1234
🚨 Build failed.

@parcel/bundler-default: Got unexpected undefined

  Error: Got unexpected undefined
      at nullthrows (didsign/node_modules/nullthrows/nullthrows.js:7:15)
      at didsign/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:731:72
      at Array.map (<anonymous>)
      at createIdealGraph (didsign/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:731:37)
      at Object.bundle (didsign/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:105:19)
      at BundlerRunner.bundle (didsign/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:258:23)
      at async Object.run (didsign/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:126:17)
      at async RequestTracker.runRequest (didsign/node_modules/@parcel/core/lib/RequestTracker.js:633:20)
      at async Object.run (didsign/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:51:7)
      at async RequestTracker.runRequest (didsign/node_modules/@parcel/core/lib/RequestTracker.js:633:20)
```

People have reported other issues about "Got unexpected undefined" but they affect earlier versions, and they do not originate from the default bundler.

## 🔦 Context

The issue seems to be related to me using CSS modules extensively. I was investigating [this failure](https://github.com/BTE-Trusted-Entity/didsign/actions/runs/5121417909/jobs/9209157572?pr=154), and it happens [here](https://github.com/parcel-bundler/parcel/blob/v2/packages/bundlers/default/src/DefaultBundler.js#L962) when the `reachable` only contains two items `[Asset(VerifiedFiles.module.css), Asset(FilesEmpty.module.css)]` and their `id` are both absent from `bundles`.

You might notice that the projects were using parcel@2.7.0 before the attempted upgrade. This is because of parcel bugs in [2.8.0](https://github.com/parcel-bundler/parcel/issues/8624) and [2.8.1](https://github.com/parcel-bundler/parcel/issues/8705) where the build has completed successfully, but the output referred to nonexistent constants.

## 💻 Code Sample

- minimal reproduction: https://github.com/BTE-Trusted-Entity/socialkyc.io/tree/minimal_reproduction
- https://github.com/BTE-Trusted-Entity/socialkyc.io
- https://github.com/BTE-Trusted-Entity/didsign
- https://github.com/BTE-Trusted-Entity/checkout.kilt.io

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.0
| Node             | 18.16.0
| npm/Yarn         | yarn 1.22.19
| Operating System | GitHub Runner Ubuntu 22.04.2

**Comment by mischnic** [comment]
Minimal reproduction: [Archiv.zip](https://github.com/parcel-bundler/parcel/files/11645142/Archiv.zip)

Looks like having two CSS module assets that both have `composes: ... from "./something.module.css";` referring to the same file triggers this.

cc @AGawrys

**Comment by shepmaster** [comment]
Is there anything the community can do to address this bug?

**Comment by keithlayne** [comment]
I think I've run into this issue too - we use a combination of css, scss both with and without modules. We have a shared config that is used to build a bunch of small projects (without package.json) is a directory tree.

I had parcel (and @parcel/*) pinned to 2.8.2 until recently, when I upgraded to 2.9.3. Today I realized _some_ of the subprojects were failing to build with what looks like an identical error to what's mentioned in this issue.

I didn't make the connection until just now that one of the successful builds uses an SCSS file in a style tag, but imports react components that are using (plain) CSS modules. One of the failures has an import using SCSS modules. I know that's not a lot to work off, but maybe it will help.

This was working with 2.8.2. I tried 2.9.0, 2.9.1, and 2.9.2 and got the same errors with those, consistent with the OP.

Since the error is happening (for me) [here](https://github.com/parcel-bundler/parcel/blob/v2/packages/bundlers/default/src/DefaultBundler.js#L962-L963) I just cheated, and used this config as a workaround for now:

```json
  "@parcel/bundler-default": {
    "minBundles": 1000
  }
```

It's unclear to me why this code would be hit. The entrypoint is an html file with a script tag pointing at a tsx file, and a style tag pointing at an scss file. Code splitting doesn't seem relevant here, but that probably just reflects my ignorance.

**Comment by keithlayne** [comment]
Looking again, the graph for at least one of my failures looks something like this:

```mermaid
graph TD;
    A.tsx-->C.tsx;
    A.tsx-->B.tsx;
    B.tsx-->C.tsx;
    C.tsx-->C.module.css
```

Is it possible that multiple unique paths to a CSS module triggers this? Maybe that's similar to the minimal repro above?

*EDIT:* A very simple reproduction of this pattern worked fine.

**Comment by markafitzgerald1** [comment]
I'm seeing something similar to this issue right now on Parcel 2.9.3. I have two separate CSS modules,  both of which `var` reference the same third CSS module (`var(--foo from "./bar.module.css")`). My situation looks very similar to [the above](https://github.com/parcel-bundler/parcel/issues/9058#issuecomment-1575455294) from earlier versions of Parcel.

Here's my `parcel serve` error stack in case that's helpful:
```
🚨 Build failed.

@parcel/bundler-default: Got unexpected undefined

  Error: Got unexpected undefined
      at nullthrows (/...../node_modules/nullthrows/nullthrows.js:7:15)
      at /...../node_modules/@parcel/bundler-default/lib/DefaultBundler.js:731:72
      at Array.map (<anonymous>)
      at createIdealGraph (/...../node_modules/@parcel/bundler-default/lib/DefaultBundler.js:731:37)
      at Object.bundle (/...../node_modules/@parcel/bundler-default/lib/DefaultBundler.js:105:19)
      at BundlerRunner.bundle (/...../node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:258:23)
      at async Object.run (/...../node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:126:17)
      at async RequestTracker.runRequest (/...../node_modules/@parcel/core/lib/RequestTracker.js:633:20)
      at async Object.run (/...../node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:51:7)
      at async RequestTracker.runRequest (/...../node_modules/@parcel/core/lib/RequestTracker.js:633:20)
```

**Comment by shepmaster** [comment]
@markafitzgerald1 this fix [hasn't been released yet](https://github.com/parcel-bundler/parcel/pull/9195#issuecomment-1740798496)

**Comment by markafitzgerald1** [comment]
> @markafitzgerald1 this fix [hasn't been released yet](https://github.com/parcel-bundler/parcel/pull/9195#issuecomment-1740798496)

Ah, that makes sense. Thanks for explaining, @shepmaster. When I saw this issue was Closed I initially figured it would be released. On further inspection (and thought), I now see that the [fix PR](https://github.com/parcel-bundler/parcel/pull/9195) was merged and this Issue was closed in August 2023, but the last [release](https://github.com/parcel-bundler/parcel/releases) (2.9.3) was on June 25, 2023. I'll stay tuned for the next release.

Thanks for testing out the PR fix in the nightly builds!
