### ISSUE TITLE
build mode: a compression mode

### ISSUE THREAD

**Issue by sKawashima** [parcel-bundler/parcel#917]
**Choose one:** is this a  🙋 feature request?

### 🤔 Expected Behavior

Bundled file name: 
- a.js
- b.js
- c.js...

### 😯 Current Behavior
Bundled file name: 
- fb0a84bd5e863e5a395b78e74d401724.js
- f2e0183b09ea83b560a791fc02cb5141.js
- c92d0ea5d3fb2b49f05693014790ca33.js

### 💁 Possible Solution

want a mode that can be bundled with a short file name so that it can be published.

### 🔦 Context

I am not familiar with the module bundle, so I'm happy if you tell me if the file name has a long reason.
However, because it is not detailed, I think that the function that can shorten the file name is useful.

I am using Google translation because I am not good at English. I am sorry if it is difficult to read.

**Comment by davidnagli** [comment]
Is there a reason that you would care about file name length? 🤔 

I can’t really image a case where it could make a difference.

**Comment by brandon93s** [comment]
This is currently by-design as these resource names are never intended to be seen by an end user, just embedded in the page. You may be interested in the discussion over at #872.

**Comment by sKawashima** [comment]
@davidnagli 
Thank you for responding.
I thought that you can reduce the capacity by shortening the source code.

@brandon93s 
Thank you for responding and telling me the existing discussion.
I did not know that various discussions have already been done.

However, I think that it is okay to have a compression mode that compresses mostly.

**Comment by davidnagli** [comment]
> I thought that you can reduce the capacity by shortening the source code.

I’m a bit confused... are you talking about compressing the **file contents**, or the **file name**??

**Comment by sKawashima** [comment]
@davidnagli
Sorry for the confusion.
I thought that as long as the file name got shorter, I thought that the characters used for the link from the source code would be short, but is it different?

**Comment by davidnagli** [comment]
Oh ok now I see what you’re trying to say 😃 👍 

You’re saying that by having smaller file names, you can shave off a few bits in the HTML that references those files.

I mean I guess this *might* be a priority for some, but realistically even if you have a huge project with tons of different child bundles and code splitting such that the bundled html file has a ton of imports, you’re never gonna really save more than a few **bytes**.

I think at this point we shouldn’t really consider the length of the filename as a constraining factor for how we choose to name the files, since there’s no way it’ll ever realistically impact bundle-size in any noticeable way. 

Other features such as tree-shaking will be **much** more impactful to reducing bundle-size.

**Comment by sKawashima** [comment]
Ok, I understand.
I am glad to have a polite answer. Thank you very much.
