### ISSUE TITLE
Spreading of Iterators is Broken

### ISSUE THREAD

**Issue by MazeChaZer** [parcel-bundler/parcel#9261]
# 🐛 bug report

It seems to me that Parcel translates the array spread syntax to `__spreadArray` function calls, so `[...foo]` becomes `__spreadArray([], foo, true)`. `__spreadArray` is defined as follows:

```
var __spreadArray = undefined && undefined.__spreadArray || function(to, from, pack) {
    if (pack || arguments.length === 2) {
        for(var i = 0, l = from.length, ar; i < l; i++)if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
```

But this function does not handle the spreading of iterators. E.g., if you have a `Map`:

```
const foo = new Map([[1, 'a'], [2, 'b'], [3, 'c']]);
```

And you want to get an array of all entries:

```
const bar = [...foo]
```

Then `bar` will be an empty array, instead of the array `[[1, 'a'], [2, 'b'], [3, 'c']]` as it should be.

In JavaScript runtimes that support the spread syntax (NodeJS, Firefox, …) iterators are properly spreaded.

See also [the description of the spread syntax on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax):

> The spread (...) syntax allows an **iterable**, such as an array or string, to be expanded in places where zero or more arguments (for function calls) or elements (for array literals) are expected.

And [Convert Iterables to Array using Spread](https://www.samanthaming.com/tidbits/78-iterables-to-array-using-spread/)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": [
      "@parcel/transformer-typescript-tsc"
    ]
  }
}
```

**Comment by 101arrowz** [comment]
As far as I'm aware this is something that can be fixed by modifying your `tsconfig.json` with [`downlevelIteration`](https://www.typescriptlang.org/tsconfig#downlevelIteration) set to `true`. See the difference between [it turned off](https://www.typescriptlang.org/play?target=1#code/NoOjDsFMHcAIFkCGAHAFMYBGANLATALq7ADM2ALAQQJQFA) and [it turned on](https://www.typescriptlang.org/play?downlevelIteration=true&target=1#code/NoOjDsFMHcAIFkCGAHAFMYBGANLATALq7ADM2ALAQQJQFA).

The reason this only emerges with `@parcel/transformer-typescript-tsc` is that SWC handles this properly regardless of configuration.
