### ISSUE TITLE
benchmark: parcel and webpack

### ISSUE THREAD

**Issue by 466023746** [parcel-bundler/parcel#982]
### My project size
4.7M( no minify ), vue, babel, eslint
dev: has sourcemap, no minify
prod: no sourcemap, has minify

### Here is my benchmark
| env | webpack | parcel | parcel( cache ) |
| --------- | ------ | ------- | -------- |
| dev | 9.75s | 13.48s | 6.43s |
| prod | 17.5s | 22.43s | 3.42s |

### My question is
why parcel no cache is slower than webpack, i has thought the babel for node_modules perhaps the problem, bu i tried cancel the babel for node_modules, no change for the build time, so i come here to ask you guys, any benchmark?
```js
async pretransform() {
    if (this.name.indexOf('node_modules') == -1) {
          await babel(this);
     }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Webpack             | 2.7.0

**Comment by davidnagli** [comment]
Is the code used for the benchmark open source?

**Comment by 466023746** [comment]
sadly no, its private code

**Comment by DeMoorJasper** [comment]
This is really strange, webpack doesn't transform using workers, so it's either that you only have 1 core/thread or you use a lot of dependencies, which webpack just copy pastes (unless configured otherwise), even without workers parcel appears to be faster in most of our tests.
There is however not much debugging we can do to pinpoint the performance issue you have without the project or more information.

**Comment by 466023746** [comment]
i use parcel-plugin-vue, i will test it
