### ISSUE TITLE
PURE annotation misplaced

### ISSUE THREAD

**Issue by snowystinger** [parcel-bundler/parcel#9947]
# 🐛 bug report

Reported in React Spectrum https://github.com/adobe/react-spectrum/issues/6933

A PURE annotation can be misplaced due to a nullish coalescing operator
[Parcel REPL](https://repl.parceljs.org/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5odG1sJTIyJTJDJTdCJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJ2YWx1ZSUyMiUzQSUyMiUzQyFET0NUWVBFJTIwaHRtbCUzRSU1Q24lM0NtYWluJTNFJTNDJTJGbWFpbiUzRSU1Q24lM0NzY3JpcHQlMjBzcmMlM0QlNUMlMjIuJTJGaW5kZXguanN4JTVDJTIyJTIwdHlwZSUzRCU1QyUyMm1vZHVsZSU1QyUyMiUzRSUzQyUyRnNjcmlwdCUzRSUyMiU3RCU1RCUyQyU1QiUyMiUyRnNyYyUyRmluZGV4LmpzeCUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwUmVhY3QlMjBmcm9tJTIwJTVDJTIycmVhY3QlNUMlMjIlM0IlNUNuaW1wb3J0JTIwJTdCJTIwY3JlYXRlUm9vdCUyMCU3RCUyMGZyb20lMjAncmVhY3QtZG9tJTJGY2xpZW50JyUzQiU1Q25pbXBvcnQlMjAlN0JBcHAlN0QlMjBmcm9tJTIwJy4lMkZBcHAuanN4JyUzQiU1Q25sZXQlMjByb290JTIwJTNEJTIwY3JlYXRlUm9vdChkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCU1QyUyMm1haW4lNUMlMjIpKSUzQiU1Q25yb290LnJlbmRlciglM0NBcHAlMjAlMkYlM0UpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlNUIlMjIlMkZzcmMlMkZBcHAuanN4JTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjJpbXBvcnQlMjAqJTIwYXMlMjBSZWFjdCUyMGZyb20lMjAlNUMlMjJyZWFjdCU1QyUyMiUzQiU1Q24lNUNuY29uc3QlMjBNeUNvbnRleHQlMjAlM0QlMjBSZWFjdC5jcmVhdGVDb250ZXh0KG51bGwpJTNCJTVDbiU1Q25mdW5jdGlvbiUyMENvbWJvQm94KHByb3BzKSUyMCU3QiU1Q24lMjAlMjBsZXQlMjBjb250ZW50JTIwJTNEJTIwdXNlTWVtbygoKSUyMCUzRCUzRSUyMCglNUNuJTIwJTIwJTIwJTIwJTNDTXlDb250ZXh0LlByb3ZpZGVyJTIwdmFsdWUlM0QlN0IlN0IlMjBpdGVtcyUzQSUyMHByb3BzLml0ZW1zJTIwJTNGJTNGJTIwcHJvcHMuZGVmYXVsdEl0ZW1zJTIwJTdEJTdEJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMENvbnRlbnQlNUNuJTIwJTIwJTIwJTIwJTNDJTJGTXlDb250ZXh0LlByb3ZpZGVyJTNFJTVDbiUyMCUyMCklMkMlMjAlNUJwcm9wcy5pdGVtcyUyQyUyMHByb3BzLmRlZmF1bHRJdGVtcyU1RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRSU3QmNvbnRlbnQlN0QlM0MlMkZkaXYlM0UlM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMEFwcCgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDQ29tYm9Cb3glMjBpdGVtcyUzRCU3QiU1QjElMkMlMjAyJTJDJTIwMyU1RCU3RCUyMGRlZmF1bHRJdGVtcyUzRCU3QiU1QjklMkMlMjA5JTJDJTIwOSU1RCU3RCUyMCUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyU1QiUyMiUyRnBhY2thZ2UuanNvbiUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyJTdCJTVDbiUyMCUyMCUyMCUyMCU1QyUyMm5hbWUlNUMlMjIlM0ElMjAlNUMlMjJyZXBsJTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCU1QyUyMnZlcnNpb24lNUMlMjIlM0ElMjAlNUMlMjIwLjAuMCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJlbmdpbmVzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMmJyb3dzZXJzJTVDJTIyJTNBJTIwJTVDJTIyc2luY2UlMjAyMDE5JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJ0YXJnZXRzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMmFwcCU1QyUyMiUzQSUyMCU3QiU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTVDJTIyZGVwZW5kZW5jaWVzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMnJlYWN0JTVDJTIyJTNBJTIwJTVDJTIyKiU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUMlMjJyZWFjdC1kb20lNUMlMjIlM0ElMjAlNUMlMjIqJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJlbnRyaWVzJTIyJTNBJTVCJTVEJTJDJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBZmFsc2UlMkMlMjJzb3VyY2VNYXBzJTIyJTNBdHJ1ZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyRl9fcmVwbF9kaXN0JTIyJTJDJTIydGFyZ2V0VHlwZSUyMiUzQSUyMmJyb3dzZXJzJTIyJTJDJTIydGFyZ2V0RW52JTIyJTNBbnVsbCUyQyUyMm91dHB1dEZvcm1hdCUyMiUzQW51bGwlMkMlMjJobXIlMjIlM0F0cnVlJTJDJTIybW9kZSUyMiUzQSUyMmRldmVsb3BtZW50JTIyJTJDJTIycmVuZGVyR3JhcGhzJTIyJTNBZmFsc2UlMkMlMjJ2aWV3U291cmNlbWFwcyUyMiUzQWZhbHNlJTJDJTIyZGVwZW5kZW5jaWVzJTIyJTNBJTVCJTVEJTJDJTIybnVtV29ya2VycyUyMiUzQTAlN0QlMkMlMjJ1c2VUYWJzJTIyJTNBZmFsc2UlMkMlMjJicm93c2VyQ29sbGFwc2VkJTIyJTNBJTVCJTVEJTJDJTIydmlld3MlMjIlM0ElNUIlMjIlMkZzcmMlMkZpbmRleC5odG1sJTIyJTJDJTIyJTJGc3JjJTJGaW5kZXguanN4JTIyJTJDJTIyJTJGc3JjJTJGQXBwLmpzeCUyMiUyQyUyMiUyRnBhY2thZ2UuanNvbiUyMiU1RCUyQyUyMmN1cnJlbnRWaWV3JTIyJTNBMyU3RA==).

## 🤔 Expected Behavior

PURE annotation should be on the `createElement`

**Comment by devongovett** [comment]
Looks to be fixed in latest SWC: [REPL](https://pr-9968.repl.parceljs.org/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwUmVhY3QlMjBmcm9tJTIwJTVDJTIycmVhY3QlNUMlMjIlM0IlNUNuaW1wb3J0JTIwJTdCJTIwY3JlYXRlUm9vdCUyMCU3RCUyMGZyb20lMjAncmVhY3QtZG9tJTJGY2xpZW50JyUzQiU1Q25pbXBvcnQlMjAlN0JBcHAlN0QlMjBmcm9tJTIwJy4lMkZBcHAuanMnJTNCJTVDbmxldCUyMHJvb3QlMjAlM0QlMjBjcmVhdGVSb290KGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJTVDJTIybWFpbiU1QyUyMikpJTNCJTVDbnJvb3QucmVuZGVyKCUzQ0FwcCUyMCUyRiUzRSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlNUIlMjIlMkZzcmMlMkZpbmRleC5odG1sJTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjIlM0MhRE9DVFlQRSUyMGh0bWwlM0UlNUNuJTNDbWFpbiUzRSUzQyUyRm1haW4lM0UlNUNuJTNDc2NyaXB0JTIwc3JjJTNEJTVDJTIyLiUyRmluZGV4LmpzJTVDJTIyJTIwdHlwZSUzRCU1QyUyMm1vZHVsZSU1QyUyMiUzRSUzQyUyRnNjcmlwdCUzRSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGQXBwLmpzJTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjJpbXBvcnQlMjAqJTIwYXMlMjBSZWFjdCUyMGZyb20lMjAlNUMlMjJyZWFjdCU1QyUyMiUzQiU1Q24lNUNuY29uc3QlMjBNeUNvbnRleHQlMjAlM0QlMjBSZWFjdC5jcmVhdGVDb250ZXh0KG51bGwpJTNCJTVDbiU1Q25mdW5jdGlvbiUyMENvbWJvQm94KHByb3BzKSUyMCU3QiU1Q24lMjAlMjBsZXQlMjBjb250ZW50JTIwJTNEJTIwdXNlTWVtbygoKSUyMCUzRCUzRSUyMCglNUNuJTIwJTIwJTIwJTIwJTNDTXlDb250ZXh0LlByb3ZpZGVyJTIwdmFsdWUlM0QlN0IlN0IlMjBpdGVtcyUzQSUyMHByb3BzLml0ZW1zJTIwJTNGJTNGJTIwcHJvcHMuZGVmYXVsdEl0ZW1zJTIwJTdEJTdEJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMENvbnRlbnQlNUNuJTIwJTIwJTIwJTIwJTNDJTJGTXlDb250ZXh0LlByb3ZpZGVyJTNFJTVDbiUyMCUyMCklMkMlMjAlNUJwcm9wcy5pdGVtcyUyQyUyMHByb3BzLmRlZmF1bHRJdGVtcyU1RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRSU3QmNvbnRlbnQlN0QlM0MlMkZkaXYlM0UlM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMEFwcCgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDQ29tYm9Cb3glMjBpdGVtcyUzRCU3QiU1QjElMkMlMjAyJTJDJTIwMyU1RCU3RCUyMGRlZmF1bHRJdGVtcyUzRCU3QiU1QjklMkMlMjA5JTJDJTIwOSU1RCU3RCUyMCUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjIlN0QlNUQlMkMlNUIlMjIlMkZwYWNrYWdlLmpzb24lMjIlMkMlN0IlMjJ2YWx1ZSUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlMjAlMjAlNUMlMjJuYW1lJTVDJTIyJTNBJTIwJTVDJTIycmVwbCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJ2ZXJzaW9uJTVDJTIyJTNBJTIwJTVDJTIyMC4wLjAlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTVDJTIyZW5naW5lcyU1QyUyMiUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUMlMjJicm93c2VycyU1QyUyMiUzQSUyMCU1QyUyMnNpbmNlJTIwMjAxOSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTVDJTIydGFyZ2V0cyU1QyUyMiUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUMlMjJhcHAlNUMlMjIlM0ElMjAlN0IlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCU1QyUyMmRlcGVuZGVuY2llcyU1QyUyMiUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUMlMjJyZWFjdCU1QyUyMiUzQSUyMCU1QyUyMiolNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTVDJTIycmVhY3QtZG9tJTVDJTIyJTNBJTIwJTVDJTIyKiU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTIyJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0FmYWxzZSUyQyUyMnZpZXdTb3VyY2VtYXBzJTIyJTNBZmFsc2UlMkMlMjJkZXBlbmRlbmNpZXMlMjIlM0ElNUIlNUQlMkMlMjJudW1Xb3JrZXJzJTIyJTNBMCU3RCUyQyUyMnVzZVRhYnMlMjIlM0FmYWxzZSUyQyUyMmJyb3dzZXJDb2xsYXBzZWQlMjIlM0ElNUIlNUQlMkMlMjJ2aWV3cyUyMiUzQSU1QiUyMiUyRnNyYyUyRmluZGV4LmpzJTIyJTJDJTIyJTJGc3JjJTJGQXBwLmpzJTIyJTJDJTIyJTJGc3JjJTJGaW5kZXguaHRtbCUyMiUyQyUyMiUyRnBhY2thZ2UuanNvbiUyMiU1RCUyQyUyMmN1cnJlbnRWaWV3JTIyJTNBMyU3RA==)
